src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>Batch-interfaced</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Generate_Account_Number__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Use to activate the trigger (AccountTriggerHandler)  to populate account number (standard object) from account auto number (custom fields)</description>
        <label>Generate Account Number?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Legacy_Created_By__c</fullName>
        <label>Legacy Created By</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_Created_Date__c</fullName>
        <label>Legacy Created Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Legacy_Updated_By__c</fullName>
        <label>Legacy Updated By</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_Updated_Date__c</fullName>
        <label>Legacy Updated Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is auto-populated via trigger. See Section 1.2.8.4. Apex Trigger).</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Activation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Asia1__c.object
<CustomObject>
    <fields>
        <fullName>ASIAONE_Legacy_Id__c</fullName>
        <externalId>true</externalId>
        <label>ASIAONE Legacy Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <label>Display Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Legacy_Created_By__c</fullName>
        <label>Legacy Created By</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_Created_Date__c</fullName>
        <label>Legacy Created Date</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_Updated_By__c</fullName>
        <label>Legacy Updated By</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_Updated_Date__c</fullName>
        <label>Legacy Updated Date</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Creation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error Creation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disabled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_ID_LDAP_ID__c</fullName>
        <label>User ID/LDAP ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Asia1</label>
    <nameField>
        <displayFormat>A1{0000000000}</displayFormat>
        <label>Asia1</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asia1s</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Asia1_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Asia1__c</fullName>
        <label>Asia1</label>
        <referenceTo>Asia1__c</referenceTo>
        <relationshipLabel>Asia1_Subscriptions</relationshipLabel>
        <relationshipName>Asia1_Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Enabled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disabled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Activation Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error Creation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Asia1_Subscription</label>
    <nameField>
        <displayFormat>AS{0000000000}</displayFormat>
        <label>Asia1_Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asia1_Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <picklist>
            <controllingField>Category__c</controllingField>
            <picklistValues>
                <fullName>App Crash / Slow Loading / Sys Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Dispute (Direct Sub)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Dispute (Vendor Sub)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Casual Sales (Buzz, Newsstand, Outlet)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change/Reset Password</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Credit Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Particulars</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Subscription Packages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivate User Id</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gift Redemption Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gift Redemption Status</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Late Delivery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Magazine Late Delivery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Magazine Non Delivery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miscellaneous</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Inserts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newspapers - Gift Redemption Status</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Circulation Related Matters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Delivery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Start (Temp-Stop)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Stop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Stop (Temp Stop)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchase of Backdated Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchase of Receptacle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requests to Vendor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Flag Not Updated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Delivery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>User Id Not Created/Activated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Enquiry</fullName>
        <active>true</active>
        <businessProcess>New Cases from Email Assigned to Enquiry Record Type</businessProcess>
        <description>Default record type for email to case.</description>
        <label>Enquiry</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>User specified</description>
        <label>Email Address 1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Legacy_Created_By__c</fullName>
        <label>Legacy Created By</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_Created_Date__c</fullName>
        <label>Legacy Created Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Legacy_Updated_By__c</fullName>
        <label>Legacy Updated By</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_Updated_Date__c</fullName>
        <label>Legacy Updated Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Recipient_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recipient Indicator</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Email__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <label>Email</label>
</CustomObject>

src/classes/DigitalComplaintControllerTest.cls
/**
@Author Alfred Abrina
@name DigitalComplaintControllerTest
@CreateDate 02/15/2015
@Modified by Ana Fe Dumangas
@Modified by 6/23/15
@Description Test class for DigitalComplaintController
@Version <1.0>
@reference DigitalComplaintController
*/  
@isTest(SeeAllData = TRUE)
private class DigitalComplaintControllerTest {
  
/**
* Test method for data creation 
* @name testDigitalComplaint
*/       
  static testMethod void testDigitalComplaint()
    {  
      Account acc = new Account(Name = 'Test Account', Email__c = 'test@sample.com', Mobile__c = '123456789',
      RecordtypeId = ConstantsSLB.getKeyId('Account_Direct Individual'), 
      Generate_Account_Number__c = TRUE); 
      insert acc;     
      
      Contact con = TestDataFactory.createContact(1)[0];     
      con.AccountId = acc.Id;
      con.RecordTypeId =  ConstantsSLB.getKeyId('Contact_Customer Contact');
      con.Recipient_Indicator__c = true;  
      insert con;      
       
      Asia1__c asia = new Asia1__c();
      asia.ASIAONE_Legacy_Id__c = 'tsh44sa5';
      asia.Legacy_Created_Date__c = '12320514';
      asia.Legacy_Created_By__c = 'lando';
      asia.Legacy_Updated_Date__c = '114409';
      asia.Legacy_Updated_By__c = 'dola4nd';
      asia.Display_Name__c = 'mytest';
      asia.User_ID_LDAP_ID__c = 'alfred2015';
      asia.Password__c = 'newPass';     
      asia.Email__c = 'test@force.com';   
      insert asia;
      
      Asia1_Subscription__c asiasub = new Asia1_Subscription__c();
      asiasub.Asia1__c = asia.id;
      asiasub.Status__c = 'Active';
      insert asiasub;  
                 
      Case cas = TestDataFactory.createCase(1, 'Enquiry')[0];
      cas.AccountId = acc.Id;
      cas.ContactId = con.Id; 
      insert cas;        
    
      String username = 'alfred2015';
      String password = 'newPass';
      String displayName = 'mytest'; 
                  
      DigitalComplaintController dg = new DigitalComplaintController();
      Test.startTest();
      Test.setMock(HttpCalloutMock.class, new BatchServiceFacadeMockTest());
      dg.responseMap = new Map<String, String>();       
      boolean resetPassword = dg.resetPassword(cas, username, asiasub.Id, password, 'SVC', displayName);  
     
      dg.validateNewUsername(username, displayName);
      dg.enableServiceFlag (cas, username, 'SVC');              
 
      dg.disableServiceFlag(cas, username, password, displayName, 'SVC');  
      Map<String, String> mapCont = new Map<String, String>();
      mapCont.put ('Id', asia.Id);
      mapCont.put(GlobalVariableClass.USERNAME, username); 
      mapCont.put(GlobalVariableClass.DISPLAY_NAME, displayName); 
      mapCont.put(GlobalVariableClass.PASSWORD, password);
      mapCont.put(GlobalVariableClass.EMAIL, 'test@force.com');                     
      mapCont.put(GlobalVariableClass.SVC, 'svc');   
      dg.createAccount(cas, mapCont);   
  
        
      dg.createDigitalComplaintItems(cas, username, password, 'SVC', displayName, 'Active');
      dg.getErrors();
 
      Test.stopTest();        
    }
        
    static testMethod void testValidateUsernameFailed()
    {  
      Account acc = new Account(Name = 'Test Account', Email__c = 'test@sample.com', Mobile__c = '123456789',
      RecordtypeId = ConstantsSLB.getKeyId('Account_Direct Individual'), 
      Generate_Account_Number__c = TRUE); 
      insert acc;     
      
      Contact con = TestDataFactory.createContact(1)[0];     
      con.AccountId = acc.Id;
      con.RecordTypeId =  ConstantsSLB.getKeyId('Contact_Customer Contact');
      con.Recipient_Indicator__c = true;  
      insert con;      
       
      Asia1__c asia = new Asia1__c();
      asia.ASIAONE_Legacy_Id__c = 'tsh44sa5';
      asia.Legacy_Created_Date__c = '12320514';
      asia.Legacy_Created_By__c = 'lando';
      asia.Legacy_Updated_Date__c = '114409';
      asia.Legacy_Updated_By__c = 'dola4nd';
      asia.Display_Name__c = 'mytest';
      asia.User_ID_LDAP_ID__c = 'alfred2015';
      asia.Password__c = 'newPass';     
      asia.Email__c = 'test@force.com';   
      insert asia;
      
      Asia1_Subscription__c asiasub = new Asia1_Subscription__c();
      asiasub.Asia1__c = asia.id;
      asiasub.Status__c = 'Active';
      insert asiasub;  
                 
      Case cas = TestDataFactory.createCase(1, 'Enquiry')[0];
      cas.AccountId = acc.Id;
      cas.ContactId = con.Id;      
    //  cas.Sub_Category__c = 'User Id Not Created/Activated';
      insert cas;
              
      String username = 'alfred2015';
      String password = 'newPa';
      String displayName = 'mest'; 
                  
      DigitalComplaintController dg = new DigitalComplaintController();
      Test.startTest();
      Test.setMock(HttpCalloutMock.class, new BatchServiceFacadeMockFail2Test());
           
      Map<String, Boolean > validateNewUser = dg.validateNewUsername(username, displayName);
      System.assertEquals(validateNewUser.get('userNameValidationResult'), false); 
      Test.stopTest();        
      } 
/**
* Test method for data creation 
* @name testEnableServiceFlagFailed
*/       
    static testMethod void testEnableServiceFlagFailed()
    {  
      Account acc = new Account(Name = 'Test Account', Email__c = 'test@sample.com', Mobile__c = '123456789',
      RecordtypeId = ConstantsSLB.getKeyId('Account_Direct Individual'), 
      Generate_Account_Number__c = TRUE); 
      insert acc;     
      
      Contact con = TestDataFactory.createContact(1)[0];     
      con.AccountId = acc.Id;
      con.RecordTypeId =  ConstantsSLB.getKeyId('Contact_Customer Contact');
      con.Recipient_Indicator__c = true;  
      insert con;      
       
      Asia1__c asia = new Asia1__c();
      asia.ASIAONE_Legacy_Id__c = 'tsh44sa5';
      asia.Legacy_Created_Date__c = '12320514';
      asia.Legacy_Created_By__c = 'lando';
      asia.Legacy_Updated_Date__c = '114409';
      asia.Legacy_Updated_By__c = 'dola4nd';
      asia.Display_Name__c = 'mytest';
      asia.User_ID_LDAP_ID__c = 'alfred2015';
      asia.Password__c = 'newPass';     
      asia.Email__c = 'test@force.com';   
      insert asia;
      
      Asia1_Subscription__c asiasub = new Asia1_Subscription__c();
      asiasub.Asia1__c = asia.id;
      asiasub.Status__c = 'Active';
      insert asiasub;  
                 
      Case cas = TestDataFactory.createCase(1, 'Enquiry')[0];
      cas.AccountId = acc.Id;
      cas.ContactId = con.Id;      
      cas.Sub_Category__c = 'User Id Not Created/Activated';
      insert cas;
              
      String username = 'alfred2145';
      String password = 'newPa';
      String displayName = 'mest'; 
                  
      DigitalComplaintController dg = new DigitalComplaintController();
      Test.startTest();
      Test.setMock(HttpCalloutMock.class, new BatchServiceFacadeMockFail2Test());
     
      boolean isSuccess = dg.enableServiceFlag (cas, 'errorUser', 'SVC');              
      System.assertEquals(isSuccess, false);        
      
      Test.stopTest();        
      }  
/**
* Test method for data creation 
* @name testDisableServiceFlagFailed
*/         
    static testMethod void testDisableServiceFlagFailed()
    {  
      Account acc = new Account(Name = 'Test Account', Email__c = 'test@sample.com', Mobile__c = '123456789',
      RecordtypeId = ConstantsSLB.getKeyId('Account_Direct Individual'), 
      Generate_Account_Number__c = TRUE); 
      insert acc;     
      
      Contact con = TestDataFactory.createContact(1)[0];     
      con.AccountId = acc.Id;
      con.RecordTypeId =  ConstantsSLB.getKeyId('Contact_Customer Contact');
      con.Recipient_Indicator__c = true;  
      insert con;      
       
      Asia1__c asia = new Asia1__c();
      asia.ASIAONE_Legacy_Id__c = 'tsh44sa5';
      asia.Legacy_Created_Date__c = '12320514';
      asia.Legacy_Created_By__c = 'lando';
      asia.Legacy_Updated_Date__c = '114409';
      asia.Legacy_Updated_By__c = 'dola4nd';
      asia.Display_Name__c = 'mytest';
      asia.User_ID_LDAP_ID__c = 'alfred2015';
      asia.Password__c = 'newPass';     
      asia.Email__c = 'test@force.com';   
      insert asia;
      
      Asia1_Subscription__c asiasub = new Asia1_Subscription__c();
      asiasub.Asia1__c = asia.id;
      asiasub.Status__c = 'Active';
      insert asiasub;  
                 
      Case cas = TestDataFactory.createCase(1, 'Enquiry')[0];
      cas.AccountId = acc.Id;
      cas.ContactId = con.Id; 
      cas.Sub_Category__c = 'Change/Reset Password';     
      insert cas;        
    
      String username = 'alfred2015';
      String password = 'newPass';
      String displayName = 'mytest'; 
                  
      DigitalComplaintController dg = new DigitalComplaintController();
      Test.startTest();
     
      boolean isDisabled = dg.disableServiceFlag(cas, 'errorUser', password, displayName, 'SVC');  
      System.assertEquals (isDisabled, true);
      dg.getErrors();     
     
      Test.stopTest();        
    }
/**
* Test method for data creation 
* @name testDisableServiceFlagSuccess
*/    
    static testMethod void testDisableServiceFlagSuccess()
    {  
      Account acc = new Account(Name = 'Test Account', Email__c = 'test@sample.com', Mobile__c = '123456789',
      RecordtypeId = ConstantsSLB.getKeyId('Account_Direct Individual'), 
      Generate_Account_Number__c = TRUE); 
      insert acc;     
      
      Contact con = TestDataFactory.createContact(1)[0];     
      con.AccountId = acc.Id;
      con.RecordTypeId =  ConstantsSLB.getKeyId('Contact_Customer Contact');
      con.Recipient_Indicator__c = true;  
      insert con;      
       
      Asia1__c asia = new Asia1__c();
      asia.ASIAONE_Legacy_Id__c = 'tsh44sa5';
      asia.Legacy_Created_Date__c = '12320514';
      asia.Legacy_Created_By__c = 'lando';
      asia.Legacy_Updated_Date__c = '114409';
      asia.Legacy_Updated_By__c = 'dola4nd';
      asia.Display_Name__c = 'mytest';
      asia.User_ID_LDAP_ID__c = 'alfred2015';
      asia.Password__c = 'newPass';     
      asia.Email__c = 'test@force.com';   
      insert asia;
      
      Asia1_Subscription__c asiasub = new Asia1_Subscription__c();
      asiasub.Asia1__c = asia.id;
      asiasub.Status__c = 'Active';
      insert asiasub;  
                 
      Case cas = TestDataFactory.createCase(1, 'Enquiry')[0];
      cas.AccountId = acc.Id;
      cas.ContactId = con.Id; 
      cas.Sub_Category__c = 'Change/Reset Password';     
      insert cas;        
    
      String username = 'alfred2015';
      String password = 'newPass';
      String displayName = 'mytest'; 
                  
      DigitalComplaintController dg = new DigitalComplaintController();
      Test.startTest();
     
      boolean isDisabled = dg.disableServiceFlag(cas, username, password, displayName, 'SVC');  
      System.assertEquals (isDisabled, true);
      dg.getErrors();     
     
      Test.stopTest();        
    }
/**
* Test method for data error 
* @name testGetError
*/            
     static testMethod void testGetError()
     {
         DigitalComplaintController dg = new DigitalComplaintController();     
         System.assertEquals(dg.getErrors(), NULL);
     }
     static testMethod void testChangeResetPassword()
    {  
      Account acc = new Account(Name = 'Test Account', Email__c = 'test@sample.com', Mobile__c = '123456789',
      RecordtypeId = ConstantsSLB.getKeyId('Account_Direct Individual'), 
      Generate_Account_Number__c = TRUE); 
      insert acc;     
      
      Contact con = TestDataFactory.createContact(1)[0];     
      con.AccountId = acc.Id;
      con.RecordTypeId =  ConstantsSLB.getKeyId('Contact_Customer Contact');
      con.Recipient_Indicator__c = true;  
      insert con;      
       
      Asia1__c asia = new Asia1__c();
      asia.ASIAONE_Legacy_Id__c = 'tsh44sa5';
      asia.Legacy_Created_Date__c = '12320514';
      asia.Legacy_Created_By__c = 'lando';
      asia.Legacy_Updated_Date__c = '114409';
      asia.Legacy_Updated_By__c = 'dola4nd';
      asia.Display_Name__c = 'mytest';
      asia.User_ID_LDAP_ID__c = 'alfred2015';
      asia.Password__c = 'newPass';     
      asia.Email__c = 'test@force.com';   
      insert asia;
      
      Asia1_Subscription__c asiasub = new Asia1_Subscription__c();
      asiasub.Asia1__c = asia.id;
      asiasub.Status__c = 'Active';
      insert asiasub;  
                 
      Case cas = TestDataFactory.createCase(1, 'Enquiry')[0];
      cas.AccountId = acc.Id;
      cas.ContactId = con.Id; 
     cas.Sub_Category__c = 'Change/Reset Password';     
      insert cas;        
    
      String username = 'alfred2015';
      String password = 'newPass';
      String displayName = 'mytest'; 
                  
      DigitalComplaintController dg = new DigitalComplaintController();
      Test.startTest();
      Test.setMock(HttpCalloutMock.class, new BatchServiceFacadeMockTest());
      dg.responseMap = new Map<String, String>();       
      boolean resetPassword = dg.resetPassword(cas, username, 'testId', password, 'SVC', displayName);  
      System.Assert(resetPassword, true);

      dg.validateNewUsername(username, displayName);
      dg.enableServiceFlag (cas, username, 'SVC');              
 
      dg.disableServiceFlag(cas, username, password, displayName, 'SVC');  
      Map<String, String> mapCont = new Map<String, String>();
      mapCont.put ('Id', asia.Id);
      mapCont.put(GlobalVariableClass.USERNAME, username); 
      mapCont.put(GlobalVariableClass.DISPLAY_NAME, displayName); 
      mapCont.put(GlobalVariableClass.PASSWORD, password);
      mapCont.put(GlobalVariableClass.EMAIL, 'test@force.com');                     
      mapCont.put(GlobalVariableClass.SVC, 'svc');   
      dg.createAccount(cas, mapCont);   
  
        
      dg.createDigitalComplaintItems(cas, username, password, 'SVC', displayName, 'Active');
      dg.getErrors();
 
      Test.stopTest();        
    }
/**
* Test method for account creation 
* @name testGetError
*/       
    static testMethod void testCreateAccount()
    {  
      Account acc = new Account(Name = 'Test Account', Email__c = 'test@sample.com', Mobile__c = '123456789',
      RecordtypeId = ConstantsSLB.getKeyId('Account_Direct Individual'), 
      Generate_Account_Number__c = TRUE); 
      insert acc;     
      
      Contact con = TestDataFactory.createContact(1)[0];     
      con.AccountId = acc.Id;
      con.RecordTypeId =  ConstantsSLB.getKeyId('Contact_Customer Contact');
      con.Recipient_Indicator__c = true;  
      insert con;      
       
      Asia1__c asia = new Asia1__c();
      asia.ASIAONE_Legacy_Id__c = 'tsh44sa5';
      asia.Legacy_Created_Date__c = '12320514';
      asia.Legacy_Created_By__c = 'lando';
      asia.Legacy_Updated_Date__c = '114409';
      asia.Legacy_Updated_By__c = 'dola4nd';
      asia.Display_Name__c = 'mytest';
      asia.User_ID_LDAP_ID__c = 'alfred2015';
      asia.Password__c = 'newPass';     
      asia.Email__c = 'test@force.com';   
      insert asia;
      
      Asia1_Subscription__c asiasub = new Asia1_Subscription__c();
      asiasub.Asia1__c = asia.id;
      asiasub.Status__c = 'Active';
      insert asiasub;  
                 
      Case cas = TestDataFactory.createCase(1, 'Enquiry')[0];
      cas.AccountId = acc.Id;
      cas.ContactId = con.Id;      
    //  cas.Sub_Category__c = 'User Id Not Created/Activated';
      insert cas;
              
      String username = 'alfred20156';
      String password = 'newPa';
      String displayName = 'mest'; 
                          
      DigitalComplaintController dg = new DigitalComplaintController();
      Test.startTest();
      Test.setMock(HttpCalloutMock.class, new BatchServiceFacadeMockTest());
      dg.responseMap = new Map<String, String>();       
     
      Map<String, String> mapCont = new Map<String, String>();
      mapCont.put ('Id', asia.Id);
      mapCont.put(GlobalVariableClass.USERNAME, username); 
      mapCont.put(GlobalVariableClass.DISPLAY_NAME, displayName); 
      mapCont.put(GlobalVariableClass.PASSWORD, password);
      mapCont.put(GlobalVariableClass.EMAIL, 'test@force.com');                     
      mapCont.put(GlobalVariableClass.SVC, 'svc');   
      boolean isCreated = dg.createAccount(cas, mapCont);   
      System.assertEquals (isCreated, false);

      Test.stopTest();        
      } 
/**
* Test method for data creation 
* @name testDigitalComplaint3
*/           
   static testMethod void testDigitalComplaint3()
    {  
      Account acc = new Account(Name = 'Test Account', Email__c = 'test@sample.com', Mobile__c = '123456789',
      RecordtypeId = ConstantsSLB.getKeyId('Account_Direct Individual'), 
      Generate_Account_Number__c = TRUE); 
      insert acc;     
      
      Contact con = TestDataFactory.createContact(1)[0];     
      con.AccountId = acc.Id;
      con.RecordTypeId =  ConstantsSLB.getKeyId('Contact_Customer Contact');
      con.Recipient_Indicator__c = true;  
      insert con;      
       
      Asia1__c asia = new Asia1__c();
      asia.ASIAONE_Legacy_Id__c = 'tsh44sa5';
      asia.Legacy_Created_Date__c = '12320514';
      asia.Legacy_Created_By__c = 'lando';
      asia.Legacy_Updated_Date__c = '114409';
      asia.Legacy_Updated_By__c = 'dola4nd';
      asia.Display_Name__c = 'mytest';
      asia.User_ID_LDAP_ID__c = 'alfred2015';
      asia.Password__c = 'newPass';     
      asia.Email__c = 'test@force.com';   
      insert asia;
      
      Asia1_Subscription__c asiasub = new Asia1_Subscription__c();
      asiasub.Asia1__c = asia.id;
      asiasub.Status__c = 'Active';
      insert asiasub;  
                 
      Case cas = TestDataFactory.createCase(1, 'Enquiry')[0];
      cas.AccountId = acc.Id;
      cas.ContactId = con.Id; 
      cas.Sub_Category__c = 'Deactivate User Id';     
      insert cas;        
    
      String username = 'alfred2015';
      String password = 'newPass';
      String displayName = 'mytest'; 
                  
      DigitalComplaintController dg = new DigitalComplaintController();
      Test.startTest();
      Test.setMock(HttpCalloutMock.class, new BatchServiceFacadeMockTest());
      dg.responseMap = new Map<String, String>();       
      boolean resetPassword = dg.resetPassword(cas, username, 'testId', password, 'SVC', displayName);  
      System.Assert(resetPassword, true);

      dg.validateNewUsername(username, displayName);
      dg.enableServiceFlag (cas, username, 'SVC');              
 
      dg.disableServiceFlag(cas, username, password, displayName, 'SVC');  
      Map<String, String> mapCont = new Map<String, String>();
      mapCont.put ('Id', asia.Id);
      mapCont.put(GlobalVariableClass.USERNAME, username); 
      mapCont.put(GlobalVariableClass.DISPLAY_NAME, displayName); 
      mapCont.put(GlobalVariableClass.PASSWORD, password);
      mapCont.put(GlobalVariableClass.EMAIL, 'test@force.com');                     
      mapCont.put(GlobalVariableClass.SVC, 'svc');   
      dg.createAccount(cas, mapCont);   
  
        
      dg.createDigitalComplaintItems(cas, username, password, 'SVC', displayName, 'Active');
      dg.getErrors();
 
      Test.stopTest();        
    }
/**
* Test method for data creation error
* @name testDigitalComplaintFail3
*/     
    static testMethod void testDigitalComplaintFail3()
    {  
      Account acc = new Account(Name = 'Test Account', Email__c = 'test@sample.com', Mobile__c = '123456789',
      RecordtypeId = ConstantsSLB.getKeyId('Account_Direct Individual'), 
      Generate_Account_Number__c = TRUE); 
      insert acc;     
      
      Contact con = TestDataFactory.createContact(1)[0];     
      con.AccountId = acc.Id;
      con.RecordTypeId =  ConstantsSLB.getKeyId('Contact_Customer Contact');
      con.Recipient_Indicator__c = true;  
      insert con;      
       
      Asia1__c asia = new Asia1__c();
      asia.ASIAONE_Legacy_Id__c = 'tsh44sa5';
      asia.Legacy_Created_Date__c = '12320514';
      asia.Legacy_Created_By__c = 'lando';
      asia.Legacy_Updated_Date__c = '114409';
      asia.Legacy_Updated_By__c = 'dola4nd';
      asia.Display_Name__c = 'mytest';
      asia.User_ID_LDAP_ID__c = 'alfred2015';
      asia.Password__c = 'newPass';     
      asia.Email__c = 'test@force.com';   
      insert asia;
      
      Asia1_Subscription__c asiasub = new Asia1_Subscription__c();
      asiasub.Asia1__c = asia.id;
      asiasub.Status__c = 'Active';
      insert asiasub;  
                 
      Case cas = TestDataFactory.createCase(1, 'Enquiry')[0];
      cas.AccountId = acc.Id;
      cas.ContactId = con.Id;      
      cas.Sub_Category__c = 'Deactivate User Id';      
      insert cas;
              
      String username = 'alfred';
      String password = 'newPa';
      String displayName = 'mest'; 
                  
      DigitalComplaintController dg = new DigitalComplaintController();
      Test.startTest();
      Test.setMock(HttpCalloutMock.class, new BatchServiceFacadeMockFail2Test());
      Map<String,Object> responseMapTest = new Map<String,Object>();
      
      dg.responseMap = new Map<String, String>();      
      dg.resetPassword(cas, 'hello', 'testId123113', 'fail2', 'SVC', displayName);  
      boolean resetPassword = dg.resetPassword(cas, username, 'testId', password, 'SVC', displayName);  
          
      dg.validateNewUsername('erroruser', 'ErrorDisplay');
      
      dg.responseMap.put('Activate', 'Success');           
      dg.enableServiceFlag (cas, username, 'SVC');              
      dg.disableServiceFlag(cas, username, password, displayName, 'SVC');  
      Map<String, String> mapCont = new Map<String, String>();
      mapCont.put ('Id', asia.Id);
      mapCont.put(GlobalVariableClass.USERNAME, username); 
      mapCont.put(GlobalVariableClass.DISPLAY_NAME, displayName); 
      mapCont.put(GlobalVariableClass.PASSWORD, password);
      mapCont.put(GlobalVariableClass.EMAIL, 'test@force.com');                
      mapCont.put(GlobalVariableClass.SVC, 'svc');  
  
      dg.createAccount(cas, mapCont);   
      
      dg.createDigitalComplaintItems(cas, username, password, 'SVC', displayName, 'Active');     
      Test.stopTest();        
      }  

    }