src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>Batch-interfaced</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Singpost_Address__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Postal Code</label>
        <referenceTo>Singpost_Address__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address_Type__c</fullName>
        <description>This field will be displayed if record type field is Local.
Read-only. Auto-populated by the system based on Postal Code</description>
        <label>Singpost Address Type</label>
        <picklist>
            <picklistValues>
                <fullName>P</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>W</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>H</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>K</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>U</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be displayed if record type field is Local.
User specified</description>
        <label>Postal Code</label>
        <referenceTo>Singpost_Address__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account field that is not read-only to be used in Adjustment Case. Field Value will be copied into Account Standard field and will not be exposed in detail page layout.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Account) (Do Not Use)</relationshipLabel>
        <relationshipName>Cases_Do_Not_Use</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Date_Replaced__c</fullName>
        <label>Date Replaced</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Cases (Order Number)</relationshipLabel>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <label>Qty</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>User specified</description>
        <label>Email Address 1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Recipient_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recipient Indicator</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Delivery_Charge__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Mapping of Subscriber Charge and Vendor Credit based on Delivery Charge Type.

Please note that the Name is a combination of Address Type and Delivery Charge Type in that order.</description>
    <fields>
        <fullName>Subscriber_Charge__c</fullName>
        <description>If value is set to 9999.99, this means the value must be from user input.</description>
        <label>Subscriber Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Delivery Charge</label>
</CustomObject>

src/objects/Email__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <label>Email</label>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delivery_Charge__c</fullName>
        <label>Delivery Charge</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>ARMS field</description>
        <label>ARMS Postal Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriber_Charge__c</fullName>
        <label>Subscriber Charge</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Case__r.Account.Name</formula>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Main_Package_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Main Package ID</label>
        <referenceTo>Package__c</referenceTo>
        <relationshipLabel>Order Line Items (Main Package ID)</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Line_Item__c</fullName>
        <displayFormat>A-{000000}</displayFormat>
        <label>Order Line Item #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items_Direct</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Updated Length  from 16,2 (FDS)  to 5,0 (Sample Tool tip from Eugene)</description>
        <label>Qty</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI{0000000000}</displayFormat>
        <label>Order Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Package__c.object
<CustomObject>
    <fields>
        <fullName>Subscription_Type__c</fullName>
        <label>Subscription Type</label>
        <picklist>
            <picklistValues>
                <fullName>Termed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evergreen</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product_Code__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Product Codes to bypass creation of Delivery Subscription</description>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>8</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Product Code</label>
</CustomObject>

src/objects/Singpost_Address__c.object
<CustomObject>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <label>Singpost Address</label>
    <nameField>
        <label>Postal Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Singpost Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SendEshopCustomerEmailTest.cls
/*
Author: Joyrem Zarmaine D. Ayuman
Date: Oct 15, 2015
Note: Additional for code coverage
*This is test class for SendEshopCustomerEmail
*/

@isTest (seeAllData= true)
public class SendEshopCustomerEmailTest{
    
    static testMethod void TestSendEShop(){
        try {
           // System.debug('Before new user');
            
            User u = TestDataFactory.prepareTestusers();
           
            
            database.insert(u);
            
           // System.debug('Before runAs(u)');
    
            System.runAs(u) {
                List<Account> accList = TestDataFactory.createAccount(1, 'Direct Corporate');   
            insert accList;
                   
            
              
                Singpost_Address__c postal = TestDataFactory.createSingpostAddress(1)[0];
                //insert new List<sObject>{postal,acc, pkg[0]};
                insert postal;             
                    
                Address__c addressRec = TestDataFactory.createAddress(1)[0];
                addressRec.Address_Type__c='P';
                addressRec.Postal_Code__c = postal.Id;
                insert addressRec;
                
                List<Contact> con = TestDataFactory.createContact(1);
                con[0].Address__c = addressRec.Id;
               //con[0].RecordTypeId = ConstantsSLB.getKeyId('Contact_Customer Contact');
                con[0].Recipient_Indicator__c = true;
                con[0].Phone = '1234567';
                con[0].AccountId = accList[0].Id;
                //con[0].Email = 'alfred.abrina@accenture.com';            
                insert con;            
             
            List<Package__c> packageList = TestDataFactory.createPackage(1);
            insert packageList;
            
                                   
            List<Zuora__CustomerAccount__c> billAccountList = TestDataFactory.createBillingAccount(1);
            billAccountList[0].Zuora__Account__c = accList[0].id;   
            
            insert billAccountList;       
            
                   
            List<Order__c> orderList = TestDataFactory.createOrder(1);
            orderList[0].Account__c = accList[0].id;
            orderList[0].Subscriber_Charge__c = 100; 
                
            insert orderList;
                  
                             
            List<Order_Line_Item__c> orderLineItemList = TestDataFactory.createOrderLineItem(1);
            orderLineItemList[0].Order__c = orderList[0].id; 
            orderLineItemList[0].Main_Package_ID__c = packageList[0].id;
            orderLineItemList[0].Start_Date__c = date.today()+2;
                 
            insert orderLineItemList;
            
             List<Zuora__Subscription__c> zsubList = TestDataFactory.createSubscription(1);          
            //zsubList = TestDataFactory.createSubscription(2);
            //set values
            zsubList[0].Zuora__Account__c = accList[0].id;
            zsubList[0].Zuora__CustomerAccount__c = billAccountList[0].id;
            zsubList[0].Qty1__c ='20';  
            zsubList[0].Order_Number__c = orderList[0].id;        
            zsubList[0].Order_Line_Item_Number__c = orderLineItemList[0].id;
            zsubList[0].Delivery_Charge__c = 200;
            zsubList[0].Product_Code__c = 'CD001';                
            zsubList[0].Email__c = con[0].Email;            
            //zsubList[0].Email__c = 'alfred.abrina@accenture.com';        
            zsubList[0].Subscription_Type_1__c = 'Publication';
            zsubList[0].Subscription_Type__c = 'Publication';   
            zsubList[0].Number_of_Copies1__c =  '100';
            zsubList[0].Number_of_Copies__c = 100;
            zsubList[0].Qty__c = 20;
            insert zsubList;
    
                Case cas = new Case();
                cas.AccountId = accList[0].id;
                cas.Order__c = orderList[0].Id;
                cas.Origin = 'Phone';
                cas.Priority = 'Medium';
                cas.Date_Replaced__c = system.today();
                cas.Status = 'New';
                insert cas;
            
                
                //Account acc = new Account(Name = 'Test Account', RecordTypeId = ConstantsSLB.getKeyId('Account_Vendor Subscriber'));
                test.starttest();                      
                SendEshopCustomerEmail sendEshop = new SendEshopCustomerEmail();
                
               // sendEshop(zsubList);  
                
                sendEshop.SendEshopCustomerEmailFailure ('Email Error', 'alfred.abrina@accenture.com', 'CODE001'); 
                
                String success = sendEshop.BodySuccess('Success', 'sSFSubId', 'TestId',  'sOrderId'); 
                System.assertNotEquals(success, 'error');
                String error = sendEshop.BodyFailure('Body Failure', 'Code02');          
                System.assertNotEquals(error, 'success');
               // sendEshop.SendEshopCustomerEmail(zSubs[0]);     
                test.stoptest();           
           }
        }catch(Zuora.zRemoteException e) {System.debug(e);}  
    }                
        
    static testMethod void TestEmailisNotNull(){
        try {
           // System.debug('Before new user');
            
            User u = TestDataFactory.prepareTestusers();
            
            database.insert(u);
            
            System.runAs(u) {
                List<Account> accList = TestDataFactory.createAccount(1, 'Direct Corporate');   
            insert accList;
                   
            
                
                Singpost_Address__c postal = TestDataFactory.createSingpostAddress(1)[0];
                //insert new List<sObject>{postal,acc, pkg[0]};
                insert postal;             
                    
                Address__c addressRec = TestDataFactory.createAddress(1)[0];
                addressRec.Address_Type__c='P';
                addressRec.Postal_Code__c = postal.Id;
                insert addressRec;
                
                List<Contact> con = TestDataFactory.createContact(1);
                con[0].Address__c = addressRec.Id;
               //con[0].RecordTypeId = ConstantsSLB.getKeyId('Contact_Customer Contact');
                con[0].Recipient_Indicator__c = true;
                con[0].Phone = '1234567';
                con[0].AccountId = accList[0].Id;
                con[0].Email__c = 'alfred.abrina@accenture.com';            
                insert con;            
            
                    
            List<Package__c> packageList = TestDataFactory.createPackage(1);
            insert packageList;
            
                                   
            List<Zuora__CustomerAccount__c> billAccountList = TestDataFactory.createBillingAccount(1);
            billAccountList[0].Zuora__Account__c = accList[0].id;   
            billAccountList[0].Zuora__SoldToName__c = 'April';
            insert billAccountList;       
            
                   
            List<Order__c> orderList = TestDataFactory.createOrder(1);
            orderList[0].Account__c = accList[0].id;
            orderList[0].Subscriber_Charge__c = 100; 
                
            insert orderList;
                  
                             
            List<Order_Line_Item__c> orderLineItemList = TestDataFactory.createOrderLineItem(1);
            orderLineItemList[0].Order__c = orderList[0].id; 
            orderLineItemList[0].Main_Package_ID__c = packageList[0].id;
            orderLineItemList[0].Start_Date__c = date.today()+2;
                 
            insert orderLineItemList;
            
             List<Zuora__Subscription__c> zsubList = TestDataFactory.createSubscription(1);          
            //zsubList = TestDataFactory.createSubscription(2);
            //set values
            zsubList[0].Zuora__Account__c = accList[0].id;
            zsubList[0].Zuora__CustomerAccount__c = billAccountList[0].id;
            zsubList[0].Qty1__c ='20';  
            zsubList[0].Order_Number__c = orderList[0].id;        
            zsubList[0].Order_Line_Item_Number__c = orderLineItemList[0].id;
            zsubList[0].Delivery_Charge__c = 200;
            zsubList[0].Product_Code__c = 'CD001';
            zsubList[0].Contact__c = con[0].Id;    
            zsubList[0].Subscription_Type_1__c = 'Publication';
            zsubList[0].Subscription_Type__c = 'Publication';
            zsubList[0].Number_of_Copies1__c =  '100';
            zsubList[0].Number_of_Copies__c = 100;
            zsubList[0].Qty__c = 20;
            zsubList[0].Email__c = 'a@a.com';
            database.insert(zsubList);
    
    
            System.debug('zsub Contact Email1: ' + con[0].Email__c);
            System.debug('zsub Contact Email2: ' + zsubList[0].Contact__r.Email__c);
    
                Case cas = new Case();
                cas.AccountId = accList[0].id;
                cas.Order__c = orderList[0].Id;
                cas.Origin = 'Phone';
                cas.Priority = 'Medium';
                cas.Date_Replaced__c = system.today();
                cas.Status = 'New';
                insert cas;
                
             
                //Account acc = new Account(Name = 'Test Account', RecordTypeId = ConstantsSLB.getKeyId('Account_Vendor Subscriber'));
                test.starttest();                      
    
                
    
                SendEshopCustomerEmail sendEshop = new SendEshopCustomerEmail();
                //sendEshop.SendEshopCustomerEmail(zsubList[0]);
                sendEshop.SendEshopCustomerEmail ();
                //SendEshopCustomerEmail controller = new SendEshopCustomerEmail(Zuora__Subscription__ zsubList[0]);
                
                 
                test.stoptest();           
           }
        
        }catch(Zuora.zRemoteException e) {System.debug(e);} 
    }                
        
    static testMethod void TestEmailisNotNull02(){
        try {            
            User u = TestDataFactory.prepareTestusers();
            
            database.insert(u);
            
            System.runAs(u) {
                List<Account> accList = TestDataFactory.createAccount(1, 'Direct Corporate');   
                insert accList;
                    
                Singpost_Address__c postal = TestDataFactory.createSingpostAddress(1)[0];
                //insert new List<sObject>{postal,acc, pkg[0]};
                insert postal;             
                    
                Address__c addressRec = TestDataFactory.createAddress(1)[0];
                addressRec.Address_Type__c='P';
                addressRec.Postal_Code__c = postal.Id;
                insert addressRec;
                
                List<Contact> con = TestDataFactory.createContact(1);
                con[0].Address__c = addressRec.Id;
               //con[0].RecordTypeId = ConstantsSLB.getKeyId('Contact_Customer Contact');
                con[0].Recipient_Indicator__c = true;
                con[0].Phone = '1234567';
                con[0].AccountId = accList[0].Id;
                con[0].Email__c = 'alfred.abrina@accenture.com';            
                insert con;            
                        
                List<Package__c> packageList = TestDataFactory.createPackage(1);
                insert packageList;
                
                                       
                List<Zuora__CustomerAccount__c> billAccountList = TestDataFactory.createBillingAccount(1);
                billAccountList[0].Zuora__Account__c = accList[0].id;   
                billAccountList[0].Zuora__SoldToName__c = 'April';
                insert billAccountList;       
                
                       
                List<Order__c> orderList = TestDataFactory.createOrder(1);
                orderList[0].Account__c = accList[0].id;
                orderList[0].Subscriber_Charge__c = 100; 
                    
                insert orderList;
                      
                                 
                List<Order_Line_Item__c> orderLineItemList = TestDataFactory.createOrderLineItem(1);
                orderLineItemList[0].Order__c = orderList[0].id; 
                orderLineItemList[0].Main_Package_ID__c = packageList[0].id;
                orderLineItemList[0].Start_Date__c = date.today()+2;
                     
                insert orderLineItemList;
                
                 List<Zuora__Subscription__c> zsubList = TestDataFactory.createSubscription(1);          
                //zsubList = TestDataFactory.createSubscription(2);
                //set values
                zsubList[0].Zuora__Account__c = accList[0].id;
                zsubList[0].Zuora__CustomerAccount__c = billAccountList[0].id;
                zsubList[0].Qty1__c ='20';  
                zsubList[0].Order_Number__c = orderList[0].id;        
                zsubList[0].Order_Line_Item_Number__c = orderLineItemList[0].id;
                zsubList[0].Delivery_Charge__c = 200;
                zsubList[0].Product_Code__c = 'CD001';
                zsubList[0].Contact__c = con[0].Id;    
                zsubList[0].Subscription_Type_1__c = 'Publication';
                zsubList[0].Subscription_Type__c = 'Publication';
                zsubList[0].Number_of_Copies1__c =  '100';
                zsubList[0].Number_of_Copies__c = 100;
                zsubList[0].Qty__c = 20;
                zsubList[0].Email__c = 'a@a.com';
                database.insert(zsubList);
                
                System.debug('zsub Contact Email1: ' + con[0].Email__c);
                System.debug('zsub Contact Email2: ' + zsubList[0].Contact__r.Email__c);
    
                Case cas = new Case();
                cas.AccountId = accList[0].id;
                cas.Order__c = orderList[0].Id;
                cas.Origin = 'Phone';
                cas.Priority = 'Medium';
                cas.Date_Replaced__c = system.today();
                cas.Status = 'New';
                insert cas;
                
                test.starttest();
                
                SendEshopCustomerEmail sendEshop = new SendEshopCustomerEmail();
                //sendEshop.SendEshopCustomerEmail(zsubList[0]); //CLin 25April2016
                
                test.stoptest();           
           }
        
        }catch(Zuora.zRemoteException e) {System.debug(e);}  

    }
      
}