src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Attention_To_Care_Of_Indicator__c</fullName>
        <label>Attention To/Care Of Indicator</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Attention_To_Care_Of_Salutation__c</fullName>
        <label>Attention To/Care Of Salutation</label>
        <picklist>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MRS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MDM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASST. PROF</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NRIC__c</fullName>
        <label>NRIC</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/BatchInterface_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Batch Interface Settings</label>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Attention_To_Care_Of_Indicator__c</fullName>
        <label>Attention To/Care Of Indicator</label>
        <picklist>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Attention_To_Care_Of_Salutation__c</fullName>
        <label>Attention To/Care Of Salutation</label>
        <picklist>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MRS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MDM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASST</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Complaint_Newspaper</fullName>
        <active>true</active>
        <businessProcess>Complaint- Newspaper</businessProcess>
        <label>Complaint - Newspaper</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Cir_Planner_Schedule__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used as reference if requests are within circulation planning schedule.</description>
    <fields>
        <fullName>Mon_Fri_End_Time__c</fullName>
        <label>Mon-Fri End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Mon_Fri_Start_Time__c</fullName>
        <label>Mon-Fri Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sat_PH_End_Time__c</fullName>
        <label>Sat/PH End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sat_PH_Start_Time__c</fullName>
        <label>Sat/PH Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sun_End_Time__c</fullName>
        <label>Sun End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sun_Start_Time__c</fullName>
        <label>Sun Start Time</label>
        <type>DateTime</type>
    </fields>
    <label>Cir Planner Schedule</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>NRIC__c</fullName>
        <description>Batch-interfaced</description>
        <label>NRIC</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_Line_Item__c.object
<CustomObject>
    <description>create( ) API callout from on-prem to request Zuora to generate the data source file, HTTP GET to download the file, and bulk API upload to upload the records in Salesforce.</description>
    <fields>
        <fullName>Charge_Amount__c</fullName>
        <description>The amount being charged to the invoice item. This amount doesn’t include taxes UNLESS the charge’s tax mode is inclusive.</description>
        <inlineHelpText>The amount being charged to the invoice item. This amount doesn’t include taxes UNLESS the charge’s tax mode is inclusive.</inlineHelpText>
        <label>Charge Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Charge_Description__c</fullName>
        <description>A description of the invoice item&apos;s charge.</description>
        <label>Charge Description</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ID__c</fullName>
        <description>The ID of this record.</description>
        <externalId>true</externalId>
        <label>ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_ID__c</fullName>
        <description>The ID of the invoice associated</description>
        <label>Invoice ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <description>The name of the product associated with this invoice item.</description>
        <label>Product Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>The number of units for this invoice item.</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Amount__c</fullName>
        <description>The amount of tax applied to the invoice item’s charge</description>
        <label>Tax Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <description>The per unit price of the invoice item</description>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <label>Invoice Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Key_Id__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To contain the list of Id&apos;s.</description>
    <fields>
        <fullName>Id__c</fullName>
        <label>Id</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Key Id</label>
</CustomObject>

src/objects/Other__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Other</label>
</CustomObject>

src/classes/BT_AB_AGD042DX_AGDEInvoinceTest.cls
/**
  * Class Name: BT_AB_AGD042DX_AGDEInvoinceTest
  * @author: Accenture IDC - Nilesh
  * Date: 11 Feb 2015
  * Requirement/Project Name: SPH Project
  * @description Test Class for BT_AB_AGD042DX_AGDEInvoince
  * 
  */
@isTest (SeeAllData = False)
public class BT_AB_AGD042DX_AGDEInvoinceTest {

        static void defaultCustomSetting()
        {
                    String invoiceId = '0x00x0x00x00x000000x0x000xx00x00';
                    Key_Id__c keyId;
                    Other__c otherC;
                    
                    String[] keyIdNameArray = new String[]{'Account_Direct Individual','Account_Vendor Subscriber','Address_Local','Contact_Customer Contact','Package Item_Base Product','Package Item_Bundle Product','Package Item_Discount','Package Item_Extension Discount','UpdateARMSInfoResultId','NEXT_RECIPIENT_NUMBER','Account_Direct Corporate','Account_Direct SPH Inter-Division','Case_Change of Subscription','Case_Start Sub','Case_Stop','Case_Temp Stop','CSO Asst. Manager/ Manager Queue','CSO TL Queue','Head of Customer Service Queue','Case Renewal of Subscription','Case_Change in Address','Complaint_Newspaper','Case_Complaint Magazine','SubTypeDel','SubTypePostage','SubTypePub'};
                    String[] keyIdIdcArray = new String[]{'012N00000008ic1IAA','012N00000008ibwIAA','012N00000008idiIAA','012N00000008r43IAA','012N00000008jCOIAY','012N00000008jCdIAI','012N00000008jCTIAY','012N00000008jCsIAI','123vd','123457177','012N00000008ic6IAA','012N00000008icBIAQ','012N00000008lpwIAA','012N00000008jvYIAQ','012N00000008k09IAA','012N00000008k0EIAQ','00GN0000000mMcJ','00GN0000000lUNp','00GN0000000mUXw','012N00000008lqG','012N00000008lAoIAI','012N00000008kI8IAI','012N00000008kIDIAY','Delivery','Postage','Publication'};
                    String[] keyIdTypeArray = new String[]{'Record Type','Record Type','Record Type','Record Type','Record Type','Record Type','Record Type','Record Type','Id','Number','Record Type','Record Type','Record Type','Record Type','Record Type','Record Type','Id','Id','Id','Record Type','Record Type','Record Type','Record Type','Name','Name','Name'};
                    
                    for(Integer i = 0 ; i < keyIdNameArray.size(); i++ )
                    {
                    keyId = new Key_Id__c();
                    keyId.Name = keyIdNameArray[i];
                    keyId.Id__c = keyIdIdcArray[i];
                    keyId.Type__c = keyIdTypeArray[i];
                    insert keyId;
                    }
                    
                    String[] orderCNameArray = new String[]{'Order_Type COS_Package','Order_Type COS_Quantity','Order_Type Renewal','Order_Type Start','Order_Type Stop','Product_Category AIO','Product_Category Digital','Product_Category Magazine','Product_Category Print'};
                    String[] orderCValueArray = new String[]{'Change of Subscription Package','Change of Subscription Quantity','Renewal','Start','Stop','All in One (AIO)','Digital','Magazine','Print'};
                    
                    for(Integer i = 0 ; i < orderCNameArray.size(); i++ )
                    {
                    otherC = new Other__c();
                    otherC.Name = orderCNameArray[i];
                    otherC.Value__c = orderCValueArray[i];
                    insert otherC;
                    }
                    
                    Cir_Planner_Schedule__c cirPlannerSchedule = new Cir_Planner_Schedule__c();
                    cirPlannerSchedule.Sat_PH_Start_Time__c = System.Now();
                    cirPlannerSchedule.Sat_PH_End_Time__c = System.Now()+1;
                    cirPlannerSchedule.Mon_Fri_Start_Time__c = System.Now();
                    cirPlannerSchedule.Mon_Fri_End_Time__c = System.Now()+1;
                    cirPlannerSchedule.Sun_Start_Time__c = System.Now();
                    cirPlannerSchedule.Sun_End_Time__c = System.Now()+1;
                    cirPlannerSchedule.Name = 'CIR Plan Schedule';
                    insert cirPlannerSchedule;
                    
                    BatchInterface_Settings__c batchInterfaceSetting = new BatchInterface_Settings__c();
                    batchInterfaceSetting.Name = 'Endpoint Delegator';
                    batchInterfaceSetting.value__C = 'http://devcrsm.sph.com.sg/sqebatch/Batch/BatchAuth2/BatchDelegator';
                    insert batchInterfaceSetting;
        }
        
        static testmethod void executeBatch(){
        
                    defaultCustomSetting();
                    
                    Account testAccount = TestDataFactory.createAccount(1, 'Direct Corporate')[0];
                    testAccount.NRIC__c = 'T1234567R';
                    testAccount.Attention_To_Care_Of_Indicator__c = 'A';
                    insert testAccount;
                    
                    Zuora__CustomerAccount__c testCustomerAccount = TestDataFactory.createBillingAccount(1)[0];
                    testCustomerAccount.AGD_Unit__c = '1';
                    testCustomerAccount.Attention_To_Care_Of_Indicator__c = 'A';
                    testCustomerAccount.Attention_To_Care_Of_Name__c = '1';
                    testCustomerAccount.Attention_To_Care_Of_Salutation__c = 'MR';
                    testCustomerAccount.Zuora__Account__c = testAccount.Id;
                    insert testCustomerAccount;
                    
                    Zuora__ZInvoice__c testInvoice = TestDataFactory.createInvoice(1)[0];
                    testInvoice.Zuora__InvoiceDate__c = date.today();
                    testInvoice.Zuora__BillingAccount__c = testCustomerAccount.id;
                    testInvoice.Zuora__TaxAmount__c = 100;
                    testInvoice.Zuora__TotalAmount__c = 10;
                    testInvoice.Zuora__External_Id__c='1';
                    insert testInvoice;
                    
                    Invoice_Line_Item__c testInvoiceLineItem = new Invoice_Line_Item__c();
                    testInvoiceLineItem.Invoice_ID__c = '1';
                    testInvoiceLineItem.Unit_Price__c = 2;
                    testInvoiceLineItem.Quantity__c = 5;
                    testInvoiceLineItem.Tax_Amount__c = 100.0;
                    testInvoiceLineItem.Charge_Amount__c = 200.0;
                    testInvoiceLineItem.Charge_Description__c = 'EMPTY';
                    testInvoiceLineItem.Product_Name__c = 'Delivery Charge';
                    insert testInvoiceLineItem;
                    
                    Test.StartTest();
                    BT_AB_AGD042DX_AGDEInvoince batch = new BT_AB_AGD042DX_AGDEInvoince();
                    Database.executeBatch(batch, 200);        
                    Test.StopTest();
                    
        }//end of executeBatch
        
        static testmethod void executeBatch2(){
        
                    defaultCustomSetting();
                    
                    Account testAccount = TestDataFactory.createAccount(1, 'Direct Corporate')[0];
                    testAccount.NRIC__c = 'T1234567R';
                    testAccount.Attention_To_Care_Of_Indicator__c = 'A';
                    insert testAccount;
                    
                    Zuora__CustomerAccount__c testCustomerAccount = TestDataFactory.createBillingAccount(1)[0];
                    testCustomerAccount.AGD_Unit__c = '1';
                    testCustomerAccount.Attention_To_Care_Of_Indicator__c = 'A';
                    testCustomerAccount.Attention_To_Care_Of_Name__c = '1';
                    testCustomerAccount.Attention_To_Care_Of_Salutation__c = 'MR';
                    testCustomerAccount.Zuora__Account__c = testAccount.Id;
                    insert testCustomerAccount;
                    
                    Zuora__ZInvoice__c testInvoice = TestDataFactory.createInvoice(1)[0];
                    testInvoice.Zuora__InvoiceDate__c = date.today();
                    testInvoice.Zuora__BillingAccount__c = testCustomerAccount.id;
                    testInvoice.Zuora__TaxAmount__c = 100;
                    testInvoice.Zuora__TotalAmount__c = 10;
                    testInvoice.Zuora__External_Id__c='1';
                    insert testInvoice;
                    
                    Invoice_Line_Item__c testInvoiceLineItem = new Invoice_Line_Item__c();
                    testInvoiceLineItem.Invoice_ID__c = '1';
                    testInvoiceLineItem.Unit_Price__c = 2;
                    testInvoiceLineItem.Quantity__c = 5;
                    testInvoiceLineItem.Tax_Amount__c = 100.0;
                    testInvoiceLineItem.Charge_Amount__c = 200.0;
                    testInvoiceLineItem.Charge_Description__c = 'EMPTY';
                    testInvoiceLineItem.Product_Name__c =  'Postage Charge';
                    insert testInvoiceLineItem;
                    
                    Test.StartTest();
                    BT_AB_AGD042DX_AGDEInvoince batch = new BT_AB_AGD042DX_AGDEInvoince();
                    Database.executeBatch(batch, 200);        
                    Test.StopTest();
                    
        }//end of executeBatch2
        static testmethod void executeBatch3(){
        
                    defaultCustomSetting();
                    
                    Other__c other = new Other__c();
                    other.Name = 'DTL';
                    other.Value__c = '23:59';
                    database.insert(other);
                    
                    Account testAccount = TestDataFactory.createAccount(1, 'Direct Corporate')[0];
                    testAccount.NRIC__c = 'T1234567R';
                    testAccount.Attention_To_Care_Of_Indicator__c = 'A';
                    insert testAccount;
                    
                    Zuora__CustomerAccount__c testCustomerAccount = TestDataFactory.createBillingAccount(1)[0];
                    testCustomerAccount.AGD_Unit__c = '1';
                    testCustomerAccount.Attention_To_Care_Of_Indicator__c = 'A';
                    testCustomerAccount.Attention_To_Care_Of_Name__c = '1';
                    testCustomerAccount.Attention_To_Care_Of_Salutation__c = 'MR';
                    testCustomerAccount.Zuora__Account__c = testAccount.Id;
                    insert testCustomerAccount;
                    
                    Zuora__Subscription__c zSub = TestDataFactory.createSubscription(1)[0];
                    zSub.Zuora__Account__c = testAccount.id;
                    zSub.Zuora__CustomerAccount__c = testCustomerAccount.id;
                    zSub.Zuora__SubscriptionStartDate__c = null;
                    zSub.Zuora__SubscriptionEndDate__c = date.Today() + 5;
                    database.insert(zSub);
                    
                    Zuora__ZInvoice__c testInvoice = TestDataFactory.createInvoice(1)[0];
                    testInvoice.Zuora__InvoiceDate__c = date.today();
                    testInvoice.Zuora__BillingAccount__c = testCustomerAccount.id;
                    testInvoice.Zuora__TaxAmount__c = 100;
                    testInvoice.Zuora__TotalAmount__c = 10;
                    testInvoice.Zuora__External_Id__c='1';
                    insert testInvoice;
                    
                    Invoice_Line_Item__c testInvoiceLineItem = new Invoice_Line_Item__c();
                    testInvoiceLineItem.Invoice_ID__c = '1';
                    testInvoiceLineItem.Unit_Price__c = 2;
                    testInvoiceLineItem.Quantity__c = 5;
                    testInvoiceLineItem.Tax_Amount__c = 100.0;
                    testInvoiceLineItem.Charge_Amount__c = 200.0;
                    testInvoiceLineItem.Charge_Description__c = 'EMPTY';
                    testInvoiceLineItem.Product_Name__c =  'Neither';
                    testInvoiceLineItem.Subscription__c = zSub.id;
                    insert testInvoiceLineItem;
                    
                    Test.StartTest();
                    BT_AB_AGD042DX_AGDEInvoince batch = new BT_AB_AGD042DX_AGDEInvoince();
                    Database.executeBatch(batch, 200);        
                    Test.StopTest();
                    
        }
        static testmethod void executeBatch4(){
        
                    defaultCustomSetting();
                    
                    Other__c other = new Other__c();
                    other.Name = 'DTL';
                    other.Value__c = '23:59';
                    database.insert(other);
                    
                    Account testAccount = TestDataFactory.createAccount(1, 'Direct Corporate')[0];
                    testAccount.NRIC__c = 'T1234567R';
                    testAccount.Attention_To_Care_Of_Indicator__c = 'A';
                    insert testAccount;
                    
                    Zuora__CustomerAccount__c testCustomerAccount = TestDataFactory.createBillingAccount(1)[0];
                    testCustomerAccount.AGD_Unit__c = '1';
                    testCustomerAccount.Attention_To_Care_Of_Indicator__c = 'A';
                    testCustomerAccount.Attention_To_Care_Of_Name__c = '1';
                    testCustomerAccount.Attention_To_Care_Of_Salutation__c = 'MR';
                    testCustomerAccount.Zuora__Account__c = testAccount.Id;
                    insert testCustomerAccount;
                    
                    Zuora__Subscription__c zSub = TestDataFactory.createSubscription(1)[0];
                    zSub.Zuora__Account__c = testAccount.id;
                    zSub.Zuora__CustomerAccount__c = testCustomerAccount.id;
                    zSub.Zuora__SubscriptionStartDate__c = date.Today() + 1;
                    zSub.Zuora__SubscriptionEndDate__c = date.Today() + 5;
                    database.insert(zSub);
                    
                    Zuora__ZInvoice__c testInvoice = TestDataFactory.createInvoice(1)[0];
                    testInvoice.Zuora__InvoiceDate__c = date.today();
                    testInvoice.Zuora__BillingAccount__c = testCustomerAccount.id;
                    testInvoice.Zuora__TaxAmount__c = 100;
                    testInvoice.Zuora__TotalAmount__c = 10;
                    testInvoice.Zuora__External_Id__c='1';
            		//START EGC 4/9/2016 added				
            		testInvoice.ARMS_Interface_Timestamp__c = null; 
            		testInvoice.ARMS_invoice_id__c = '02111111';
            		testInvoice.Zuora__TotalAmount__c = 100;
            		testInvoice.Zuora__InvoiceDate__c = System.today().addDays(30);
            		//END EGC 4/9/2016	        
            		insert testInvoice;
                    
                    Invoice_Line_Item__c testInvoiceLineItem = new Invoice_Line_Item__c();
                    testInvoiceLineItem.Invoice_ID__c = '1';
                    testInvoiceLineItem.Unit_Price__c = 2;
                    testInvoiceLineItem.Quantity__c = 5;
                    testInvoiceLineItem.Tax_Amount__c = 100.0;
                    testInvoiceLineItem.Charge_Amount__c = 200.0;
                    testInvoiceLineItem.Charge_Description__c = 'EMPTY';
                    testInvoiceLineItem.Product_Name__c =  'Neither';
                    testInvoiceLineItem.Subscription__c = zSub.id;
                    insert testInvoiceLineItem;
                    
                    Test.StartTest();
                    BT_AB_AGD042DX_AGDEInvoince batch = new BT_AB_AGD042DX_AGDEInvoince();
                        Database.executeBatch(batch, 200);        
                    Test.StopTest();
                    
        }
        
}