src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Building_Name__c</fullName>
        <label>Building Name</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Batch-interfaced</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>GST_Registration_Number__c</fullName>
        <label>GST Registration Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>House_Block_Number__c</fullName>
        <label>House/Block Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level_Number__c</fullName>
        <label>Level Number</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NRIC__c</fullName>
        <label>NRIC</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <label>Postal Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registered_Name__c</fullName>
        <label>Registered Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Singpost_Address__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Postal Code</label>
        <referenceTo>Singpost_Address__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Street_Name__c</fullName>
        <label>Street Name</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telephone_Office__c</fullName>
        <label>Telephone Office</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telephone_Residence__c</fullName>
        <label>Telephone Residence</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <label>Unit Number</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Group__c</fullName>
        <label>Vendor Group</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Type__c</fullName>
        <label>Vendor Type</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zone_Code__c</fullName>
        <label>Zone Code</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Vendor Profile</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/BT_CO_CMISPOP_ImportVendorProfile__c.object
<CustomObject>
    <fields>
        <fullName>blockHouseNumber__c</fullName>
        <label>blockHouseNumber</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>buildingName__c</fullName>
        <label>buildingName</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>email__c</fullName>
        <label>email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>faxNumber__c</fullName>
        <label>faxNumber</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>gstRegistrationNumber__c</fullName>
        <label>gstRegistrationNumber</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>handphoneNumber__c</fullName>
        <label>handphoneNumber</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>level__c</fullName>
        <label>level</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>nricPassport__c</fullName>
        <label>nricPassport</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pagerNumber__c</fullName>
        <label>pagerNumber</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>postalCode__c</fullName>
        <label>postalCode</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>registeredName__c</fullName>
        <label>registeredName</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>streetName__c</fullName>
        <label>streetName</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>telephoneOffice__c</fullName>
        <label>telephoneOffice</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>telephoneResidence__c</fullName>
        <label>telephoneResidence</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>unitNumber__c</fullName>
        <label>unitNumber</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vendorCode__c</fullName>
        <label>vendorCode</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vendorGroup__c</fullName>
        <label>vendorGroup</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vendorName__c</fullName>
        <label>vendorName</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vendorStatus__c</fullName>
        <label>vendorStatus</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vendorType__c</fullName>
        <label>vendorType</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zoneCode__c</fullName>
        <label>zoneCode</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <label>BT_CO_CMISPOP_ImportVendorProfile</label>
    <nameField>
        <label>BT_CO_CMISPOP_ImportVendorProfile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BT_CO_CMISPOP_ImportVendorProfile</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>User specified</description>
        <label>Email Address 1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>NRIC__c</fullName>
        <description>Batch-interfaced</description>
        <label>NRIC</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recipient Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Street_Name__c</fullName>
        <formula>Address__r.Street_Name__c</formula>
        <label>Street Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telephone_Office__c</fullName>
        <label>Telephone Office</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telephone_Residence__c</fullName>
        <label>Telephone Residence</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <formula>Address__r.Unit_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unit Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Group__c</fullName>
        <formula>Account.Vendor_Group__c</formula>
        <label>Vendor Group</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Email__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <label>Email</label>
</CustomObject>

src/objects/Singpost_Address__c.object
<CustomObject>
    <fields>
        <fullName>Building_Name__c</fullName>
        <description>User Specified</description>
        <label>Building Name</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>House_Block_Number__c</fullName>
        <label>House/Block Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Name__c</fullName>
        <label>Street Name</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Singpost Address</label>
    <nameField>
        <label>Postal Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Singpost Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src orig/classes/BT_AT_CMI073DX_ImportVendorProfile_Test.cls
/*
 * Class Name: BT_AT_CMI073DX_ImportVendorProfile_Test
 * @author: Kevin H. Evasco
 * Date: 09/03/2014
 * Project/Requirement: SPH Integration - CMI073DX Interface
 * @description A test class for BT_AT_CMI073DX_ImportVendorProfile 
 *
 * History:
 * 08/21/2014 Kevin Evasco Created Skeletal Apex Trigger Test Class
 * 02/07/2015 Michelle Tumbaga updated test class to add record insert for Account, Singpost_Address__c and Contact
 */

@isTest
private class BT_AT_CMI073DX_ImportVendorProfile_Test {   
    /* @description This method executes during class instantiation.  
     * @param SC a ScheduleContext which is a predefined parameter
     * @return void
     */ 

    static testMethod void testInterfaceApexTrigger() {
        //instantiate record creation -- Start
        List<BT_CO_CMISPOP_ImportVendorProfile__c> interfaceRecordList = new List<BT_CO_CMISPOP_ImportVendorProfile__c>();
        List <Singpost_Address__c> postAdd = TestDataFactory.createSingpostAddress(1);
        List <Account> testAccount = TestDataFactory.createAccount(1, 'Vendor');        
        //List <Contact> testContact = TestDataFactory.createContactRecType(1, 'Vendor Contact');        
        //instantiate record creation -- End
    
        insert postAdd;
        
        Test.StartTest();

        //set ImportVendorProfile fields without Vendor Name -- Start
        BT_CO_CMISPOP_ImportVendorProfile__c interfaceRecord = new BT_CO_CMISPOP_ImportVendorProfile__c();
        interfaceRecord.Name = 'CMI073DX';
        interfaceRecord.vendorCode__c = 'Code1';
        interfaceRecord.vendorGroup__c = 'G';
        //set ImportVendorProfile fields without Vendor Name -- End
        
        interfaceRecordList.add(interfaceRecord);

        //set ImportVendorProfile fields without Postal Code -- Start
        interfaceRecord.Name = 'CMI073DX';
        interfaceRecord.vendorCode__c = 'Code1';
        interfaceRecord.vendorGroup__c = 'G';
        interfaceRecord.vendorName__c = 'Test Vendor Name';
        //set ImportVendorProfile fields without Postal Code -- End
        
        interfaceRecordList.add(interfaceRecord);
        
        //set ImportVendorProfile fields -- Start
        interfaceRecord.Name = 'CMI073DX';
        interfaceRecord.vendorCode__c = 'Code1';
        interfaceRecord.vendorGroup__c = 'G';
        interfaceRecord.vendorName__c = 'Test Vendor Name';
        interfaceRecord.vendorStatus__c = '1';
        interfaceRecord.vendorType__c = 'TY';
        interfaceRecord.zoneCode__c = '2';
        interfaceRecord.postalCode__c = postAdd[0].Name;
        interfaceRecord.blockHouseNumber__c = 'block1';
        interfaceRecord.buildingName__c = 'Building Name';
        interfaceRecord.email__c = 'testemail@sph.com.sg';
        interfaceRecord.faxNumber__c = '654-3210';
        interfaceRecord.gstRegistrationNumber__c = 'Registration12345';
        interfaceRecord.handphoneNumber__c = '654-3210';
        interfaceRecord.level__c = 'LV1';
        interfaceRecord.nricPassport__c = 'NRIC123';
        interfaceRecord.pagerNumber__c = '6543-210-98';
        interfaceRecord.registeredName__c = 'Test REG Name';
        interfaceRecord.streetName__c = '888';
        interfaceRecord.telephoneOffice__c = '654-3210';
        interfaceRecord.telephoneResidence__c = '654-3210';
        interfaceRecord.unitNumber__c = '1234';
        //set ImportVendorProfile fields -- End
        
        interfaceRecordList.add(interfaceRecord);

        insert testAccount;

        //Set Contact fields -- Start
        /*for(Contact cont: testContact) {
            cont.Recipient_Indicator__c = TRUE;
            cont.AccountId = testAccount[0].Id;
        } //Set Contact fields -- End
        
        insert testContact;*/
        
        //match the Account fields with ImportVendorProfile fields on Account update
        //update Account -- Start
        testAccount[0].Vendor_Type__c  = interfaceRecordList[2].vendorType__c;
        testAccount[0].Vendor_Group__c  = interfaceRecordList[2].vendorGroup__c;
        testAccount[0].Zone_Code__c  = interfaceRecordList[2].zoneCode__c;
        //testAccount[0].NRIC__c  = interfaceRecordList[2].nricPassport__c;
        //testAccount[0].Registered_Name__c  = interfaceRecordList[2].registeredName__c;
        testAccount[0].Unit_Number__c  = interfaceRecordList[2].unitNumber__c;
        testAccount[0].Level_Number__c  = interfaceRecordList[2].level__c;
        testAccount[0].House_Block_Number__c  = interfaceRecordList[2].blockHouseNumber__c;
        testAccount[0].Street_Name__c  = interfaceRecordList[2].streetName__c;
        testAccount[0].Building_Name__c  = interfaceRecordList[2].buildingName__c;
        testAccount[0].PostalCode__c  = interfaceRecordList[2].postalCode__c;
        testAccount[0].Telephone_Residence__c  = interfaceRecordList[2].telephoneResidence__c;
        testAccount[0].Telephone_Office__c  = interfaceRecordList[2].telephoneOffice__c;
        //testAccount[0].Email__c  = interfaceRecordList[2].email__c;
        testAccount[0].GST_Registration_Number__c  = interfaceRecordList[2].gstRegistrationNumber__c;
        //update Account -- End
        
        update testAccount;

        //match the Account fields with ImportVendorProfile fields on Account create
        //insert Account -- Start
        list<Account> testAccount2 = TestDataFactory.createAccount(1, 'Vendor');
            testAccount2[0].Vendor_Type__c  = interfaceRecordList[2].vendorType__c;
            testAccount2[0].Vendor_Group__c  = interfaceRecordList[2].vendorGroup__c;
            testAccount2[0].Zone_Code__c  = interfaceRecordList[2].zoneCode__c;
            //testAccount2.NRIC__c  = interfaceRecordList[2].nricPassport__c;
            //testAccount2.Registered_Name__c  = interfaceRecordList[2].registeredName__c;
            testAccount2[0].Unit_Number__c  = interfaceRecordList[2].unitNumber__c;
            testAccount2[0].Level_Number__c  = interfaceRecordList[2].level__c;
            testAccount2[0].House_Block_Number__c  = interfaceRecordList[2].blockHouseNumber__c;
            testAccount2[0].Street_Name__c  = interfaceRecordList[2].streetName__c;
            testAccount2[0].Building_Name__c  = interfaceRecordList[2].buildingName__c;
            testAccount2[0].PostalCode__c  = interfaceRecordList[2].postalCode__c;
            testAccount2[0].Telephone_Residence__c  = interfaceRecordList[2].telephoneResidence__c;
            testAccount2[0].Telephone_Office__c  = interfaceRecordList[2].telephoneOffice__c;
            //testAccount2.Email__c  = interfaceRecordList[2].email__c;
            testAccount2[0].GST_Registration_Number__c  = interfaceRecordList[2].gstRegistrationNumber__c;
        //insert Account -- End
        
        insert testAccount2;
        Test.StopTest();
    }
}