src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Vendor Profile</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Recipient_Contact__c</fullName>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Recipient Contact</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Delivery_Charge__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Mapping of Subscriber Charge and Vendor Credit based on Delivery Charge Type.

Please note that the Name is a combination of Address Type and Delivery Charge Type in that order.</description>
    <label>Delivery Charge</label>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_Balance__c</fullName>
        <label>Credit Balance</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Delivery_Charge__c</fullName>
        <label>Delivery Charge</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Informed_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Informed Customer?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Recipient_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recipient Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.Recipient_Indicator__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Recipient Contact)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src orig/classes/StopSubOrderEntry_VendorCont_Test_Old.cls
@isTest(SeeAllData=true)
Public class StopSubOrderEntry_VendorCont_Test_Old{
    
    Public Static testMethod void StopSubOrderEntry_VendorController_Test() {

        List<Account> acct = TestDataFactory.createAccount(1, 'Vendor');
        acct[0].Name = 'Account1';
        insert acct;
        
        List<Contact> con = TestDataFactory.createContact(1);
        //Contact con = new Contact(
            con[0].AccountId = acct[0].id;
            //LastName = 'LastName1');
        insert con;
        
        List<Order__c> ord = TestDataFactory.createOrder(1);
        ord[0].Account__c = acct[0].id;
            //Credit_Balance__c = 300.00,
            //Delivery_Charge__c = 100.00,
            //Informed_Customer__c = true,
            //Recipient_Contact__c = con.id);
        Insert ord;    
        
        
        
        //List<Contact> con = TestDataFactory.createContact(1);
        //Insert con;
        try{
        Test.StartTest(); 
             PageReference pageVendorView = new PageReference('/apex/StopSubOrderEntry_Vendor_View?accountId='+ord[0].Account__c+'&orderId=' + ord[0].Id + '&recordtypeId=' + ord[0].recordtype);
                Test.setCurrentPage(pageVendorView);
                    
        StopSuborderEntry_VendorController stopSuborder = new StopSuborderEntry_VendorController();
        //stopSubOrder.getAccount();
        //stopSubOrder.getContact();
        //stopSubOrder.getOrder();
                
        Test.StopTest();
        }catch(exception e){}
    }
}