src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is auto-populated via trigger. See Section 1.2.8.4. Apex Trigger).</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Activation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Vendor Profile</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/BatchInterface_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Batch Interface Settings</label>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account field that is not read-only to be used in Adjustment Case. Field Value will be copied into Account Standard field and will not be exposed in detail page layout.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Account) (Do Not Use)</relationshipLabel>
        <relationshipName>Cases_Do_Not_Use</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Cases (Order Number)</relationshipLabel>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field is only populated for Change of Vendor.</inlineHelpText>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Vendor)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Complaint_Newspaper</fullName>
        <active>true</active>
        <businessProcess>Complaint- Newspaper</businessProcess>
        <label>Complaint - Newspaper</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Cir_Planner_Schedule__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used as reference if requests are within circulation planning schedule.</description>
    <fields>
        <fullName>Sat_PH_End_Time__c</fullName>
        <label>Sat/PH End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sat_PH_Start_Time__c</fullName>
        <label>Sat/PH Start Time</label>
        <type>DateTime</type>
    </fields>
    <label>Cir Planner Schedule</label>
</CustomObject>

src/objects/Key_Id__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To contain the list of Id&apos;s.</description>
    <fields>
        <fullName>Id__c</fullName>
        <label>Id</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Key Id</label>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provisioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Vendor Assignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Void</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order_Line_Item_Vendor__c.object
<CustomObject>
    <description>The Order Line Item Object will represent the item selected during Order Entry. 
The record looks up to Order record.</description>
    <fields>
        <fullName>Earliest_Start_Date__c</fullName>
        <label>Earliest Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Line Items (Vendor)</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Vendor Subscription can only select Newspapers</errorMessage>
            <filterItems>
                <field>Publication__c.Publication_Type__c</field>
                <operation>equals</operation>
                <value>N</value>
            </filterItems>
            <filterItems>
                <field>Publication__c.Platform_Type__c</field>
                <operation>equals</operation>
                <value>Print</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription_Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription (Vendor)</label>
        <referenceTo>Subscription_Vendor__c</referenceTo>
        <relationshipLabel>Publications</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sun__c</fullName>
        <label>Sun</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Line Item (Vendor)</label>
    <nameField>
        <displayFormat>OLIV{0000000000}</displayFormat>
        <label>Order Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items (Vendor)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Other__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Other</label>
</CustomObject>

src/objects/Publication__c.object
<CustomObject>
    <fields>
        <fullName>Earliest_Start_Date__c</fullName>
        <label>Earliest Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Platform_Type__c</fullName>
        <label>Platform Type</label>
        <picklist>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tablet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Smartphone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All in One (AIO)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Publication_Type__c</fullName>
        <description>[KCampang 9162014] Created for Stop Subscription based on QL-292 File: Publication Table v0.5</description>
        <label>Publication Type</label>
        <length>1</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Published_Days__c</fullName>
        <label>Published Days</label>
        <length>7</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Sub_Delivery_Method__c</fullName>
        <label>Vendor Sub Delivery Method</label>
        <picklist>
            <picklistValues>
                <fullName>Vendor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mailing Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vendor or Mailing Agent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <label>Publication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Subscription_Vendor__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions (Vendor)</relationshipLabel>
        <relationshipName>Subscriptions_Vendor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Subscriptions (Vendor)</relationshipLabel>
        <relationshipName>Subscriptions_Vendor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions (Vendor) (Vendor)</relationshipLabel>
        <relationshipName>Subscriptions_Vendor1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription (Vendor)</label>
    <nameField>
        <displayFormat>SV-{0000000000}</displayFormat>
        <label>Subscription (Vendor) Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions (Vendor)</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/OrderLineItemVendorTriggerHandlerTest.cls
/**
  * Class Name: OrderLineItemVendorTriggerHandlerTest
  * @author: Recuerdo Bregente
  * Date: 08/06/2015
  * Requirement/Project Name: SPH Project
  * @description Test Class for OrderLineItemVendorTriggerHandler
  */
@isTest(seeAllData=false)
private class OrderLineItemVendorTriggerHandlerTest{

    // Test Data
    static Account acc;
    static Account accVendor;
    static Order__c order;
    static Publication__c pub;
    static Order_Line_Item_Vendor__c orderLineItem;
    static List<Subscription_Vendor__c> svs;
    
    
     /**
    * @name : prepareTestData
    * @author : Recuerdo Bregente
    * @description : Prepares the test data objects.
    * @date: 08/06/2015
    */ 
    static void prepareTestData(String pubDays){
        defaultCustomSetting();
        
        acc = TestDataFactory.createAccount(1, 'Direct Corporate')[0];
        insert acc;
        System.assertNotEquals(null, acc);
        
        accVendor = TestDataFactory.createAccount(1, 'Vendor')[0];
        insert accVendor;
        System.assertNotEquals(null, accVendor);
        
        order = TestDataFactory.createOrder(1)[0];
        order.Account__c = acc.id;
        insert order;
        System.assertNotEquals(null, order);
        
        pub = TestDataFactory.createPublication(1)[0];
        pub.Published_Days__c = pubDays;
        pub.Vendor_Sub_Delivery_Method__c = 'Mailing Agent';
        pub.Publication_Type__c = 'N';
        pub.Platform_Type__c = 'Print';
        insert pub;
        System.assertNotEquals(null, pub);
        
        orderLineItem = TestDataFactory.createOrderLineItemVendor(1)[0];
        orderLineItem.Order__c = order.id;
        orderLineItem.Publication__c = pub.id;
        orderLineItem.Earliest_Start_Date__c = Date.today().addDays(1);
        orderLineItem.Start_Date__c = Date.today().addDays(3); //EGC 4/9/2016 Added
        orderLineItem.Vendor__c = acc.id;
        orderLineItem.Sun__c = 1;
        insert orderLineItem;
        
        svs = TestDataFactory.createSubscriptionVendor(1);
        for(Subscription_Vendor__c sv:svs) {
            sv.Account__c = acc.Id;
            sv.Status__c = 'Active';
            sv.Order_Number__c = order.id;
        }
        
        insert svs;
        
        Case cas = new Case();
        cas.Order__c = order.Id;
        insert cas;
    }
    
    /**
    * @name: testUpdatePassed
    * @author : Recuerdo Bregente
    * @description : Handles the testing for the update logic with error.
    * @date: 08/06/2015
    */
    static testmethod void testUpdatePassed(){
        prepareTestData('YYYYYYY');
        Test.startTest();
        System.assertNotEquals(null, orderLineItem);
        Boolean errorExist = false;
        try{
            orderLineItem.Vendor__c = accVendor.Id;
            update orderLineItem;
        } catch(System.DmlException e) {
            errorExist = true;
        }
        System.assertEquals(false, errorExist);
        Test.stopTest();
    }
    
    /**
    * @name: testUpdatePassedWithAnotherOLIVendor
    * @author : Recuerdo Bregente
    * @description : Handles the testing for the update logic with error.
    * @date: 08/06/2015
    */
    static testmethod void testUpdatePassedWithAnotherOLIVendor(){
        prepareTestData('YYYYYYY');
        Test.startTest();
        System.assertNotEquals(null, orderLineItem);
        Boolean errorExist = false;
        
        Order_Line_Item_Vendor__c newOrderLineItem = TestDataFactory.createOrderLineItemVendor(1)[0];
        newOrderLineItem.Order__c = order.id;
        newOrderLineItem.Publication__c = pub.id;
        newOrderLineItem.Earliest_Start_Date__c = Date.today().addDays(1);
        newOrderLineItem.Start_Date__c = Date.today().addDays(3); //EGC 4/9/2016 Added
        newOrderLineItem.Vendor__c = acc.id;
        newOrderLineItem.Sun__c = 1;
        insert newOrderLineItem;
        
        try{
            orderLineItem.Vendor__c = accVendor.Id;
            update orderLineItem;
        } catch(System.DmlException e) {
            errorExist = true;
        }
        System.assertEquals(false, errorExist);
        Test.stopTest();
    }
    
    /**
    * @name: testUpdatePassedWithNoVendor
    * @author : Recuerdo Bregente
    * @description : Handles the testing for the update logic with error.
    * @date: 08/06/2015
    */
    static testmethod void testUpdatePassedWithNoVendor(){
        prepareTestData('YYYYYYY');
        Test.startTest();
        System.assertNotEquals(null, orderLineItem);
        Boolean errorExist = false;
        try{
            orderLineItem.Vendor__c = null;
            update orderLineItem;
        } catch(System.DmlException e) {
            errorExist = true;
        }
        System.assertEquals(false, errorExist);
        Test.stopTest();
    }
    
    /**
    * @name: testUpdateFailed
    * @author : Recuerdo Bregente
    * @description : Handles the testing for the update logic with error.
    * @date: 08/06/2015
    */
    static testmethod void testUpdateFailed(){
        prepareTestData('NNNNNNY');
        Test.startTest();
        System.assertNotEquals(null, orderLineItem);
        Boolean errorExist = false;
        try{
            orderLineItem.Vendor__c = accVendor.Id;
            update orderLineItem;
        } catch(System.DmlException e) {
            errorExist = true;
        }
        System.assertEquals(true, errorExist);
        Test.stopTest();
    }
    
    /**
    * @name: testUpdateFailedWithTwoEditable
    * @author : Recuerdo Bregente
    * @description : Handles the testing for the update logic with error.
    * @date: 08/06/2015
    */
    static testmethod void testUpdateFailedWithTwoEditable(){
        prepareTestData('NNNNYYN');
        Test.startTest();
        System.assertNotEquals(null, orderLineItem);
        Boolean errorExist = false;
        Order_Line_Item_Vendor__c oliv = [SELECT Sun__c FROM Order_Line_Item_Vendor__c WHERE Id =: orderLineItem.Id];
        try{
            orderLineItem.Vendor__c = accVendor.Id;
            if(oliv.Sun__c == 1){
                orderLineItem.Sun__c = 0;
            } else {
                orderLineItem.Sun__c = 1;
            }
            update orderLineItem;
        } catch(System.DmlException e) {
            errorExist = true;
        }
        System.assertEquals(true, errorExist);
        Test.stopTest();
    }
    
    static testmethod void testDelete(){
        prepareTestData('NNNNNNY');
        Test.startTest();
        System.assertNotEquals(null, orderLineItem);
        
        delete orderLineItem;
        
        Test.stopTest();
    }
    
    /**
    * @name: defaultCustomSetting
    * @author : Recuerdo Bregente
    * @description : Prepares custom settings.
    * @date: 08/06/2015
    */
    static void defaultCustomSetting()
    {
        String invoiceId = '0x00x0x00x00x000000x0x000xx00x00';
        Key_Id__c keyId;
        Other__c otherC;
        
        String[] keyIdNameArray = new String[]{'Account_Direct Individual','Account_Vendor Subscriber','Address_Local','Contact_Customer Contact','Package Item_Base Product','Package Item_Bundle Product','Package Item_Discount','Package Item_Extension Discount','UpdateARMSInfoResultId','NEXT_RECIPIENT_NUMBER','Account_Direct Corporate','Account_Direct SPH Inter-Division','Case_Change of Subscription','Case_Start Sub','Case_Stop','Case_Temp Stop','CSO Asst. Manager/ Manager Queue','CSO TL Queue','Head of Customer Service Queue','Case Renewal of Subscription','Case_Change in Address','Complaint_Newspaper','Case_Complaint Magazine','SubTypeDel','SubTypePostage','SubTypePub'};
        String[] keyIdIdcArray = new String[]{'012N00000008ic1IAA','012N00000008ibwIAA','012N00000008idiIAA','012N00000008r43IAA','012N00000008jCOIAY','012N00000008jCdIAI','012N00000008jCTIAY','012N00000008jCsIAI','123vd','123457177','012N00000008ic6IAA','012N00000008icBIAQ','012N00000008lpwIAA','012N00000008jvYIAQ','012N00000008k09IAA','012N00000008k0EIAQ','00GN0000000mMcJ','00GN0000000lUNp','00GN0000000mUXw','012N00000008lqG','012N00000008lAoIAI','012N00000008kI8IAI','012N00000008kIDIAY','Delivery','Postage','Publication'};
        String[] keyIdTypeArray = new String[]{'Record Type','Record Type','Record Type','Record Type','Record Type','Record Type','Record Type','Record Type','Id','Number','Record Type','Record Type','Record Type','Record Type','Record Type','Record Type','Id','Id','Id','Record Type','Record Type','Record Type','Record Type','Name','Name','Name'};
        
        List<Key_Id__c> keyList = [SELECT Name FROM Key_Id__c];
        Set<String> keyNames = new Set<String>();
        for(Key_Id__c keyRec : keyList) {
            keyNames.add(keyRec.Name);
        }
        
        for(Integer i = 0 ; i < keyIdNameArray.size(); i++ )
        {
            if(!keyNames.contains(keyIdNameArray[i])) {
                keyId = new Key_Id__c();
                keyId.Name = keyIdNameArray[i];
                keyId.Id__c = keyIdIdcArray[i];
                keyId.Type__c = keyIdTypeArray[i];
                insert keyId;
            }
        }
        
        String[] orderCNameArray = new String[]{'Order_Type COS_Package','Order_Type COS_Quantity','Order_Type Renewal','Order_Type Start','Order_Type Stop','Product_Category AIO','Product_Category Digital','Product_Category Magazine','Product_Category Print','DTL','ARMS_AccTyp','ARMS_SysId','ARMS_userID','ARMS_password'};
        String[] orderCValueArray = new String[]{'Change of Subscription Package','Change of Subscription Quantity','Renewal','Start','Stop','All in One (AIO)','Digital','Magazine','Print', '23:59','SS','SS','Username','Password'};
        
        List<Other__c> otherList = [SELECT Name FROM Other__c];
        Set<String> otherNames = new Set<String>();
        for(Other__c otherRec : otherList) {
            otherNames.add(otherRec.Name);
        }
        
        for(Integer i = 0 ; i < orderCNameArray.size(); i++ )
        {
            if(!otherNames.contains(orderCNameArray[i])) {
                otherC = new Other__c();
                otherC.Name = orderCNameArray[i];
                otherC.Value__c = orderCValueArray[i];
                insert otherC;
            }
        }
        
        List<Cir_Planner_Schedule__c> cpcList = [SELECT Name FROM Cir_Planner_Schedule__c WHERE Name = 'CIR Plan Schedule'];
        if(cpcList.isEmpty()) {
            Cir_Planner_Schedule__c cirPlannerSchedule = new Cir_Planner_Schedule__c();
            cirPlannerSchedule.Sat_PH_Start_Time__c = System.Now();
            cirPlannerSchedule.Sat_PH_End_Time__c = System.Now()+1;
            cirPlannerSchedule.Mon_Fri_Start_Time__c = System.Now();
            cirPlannerSchedule.Mon_Fri_End_Time__c = System.Now()+1;
            cirPlannerSchedule.Sun_Start_Time__c = System.Now();
            cirPlannerSchedule.Sun_End_Time__c = System.Now()+1;
            cirPlannerSchedule.Name = 'CIR Plan Schedule';
            insert cirPlannerSchedule;
        }
        
        List<BatchInterface_Settings__c> bitList = [SELECT Name FROM BatchInterface_Settings__c WHERE Name = 'Endpoint Delegator'];
        if(bitList.isEmpty()) {
            BatchInterface_Settings__c batchInterfaceSetting = new BatchInterface_Settings__c();
            batchInterfaceSetting.Name = 'Endpoint Delegator';
            batchInterfaceSetting.value__C = 'http://devcrsm.sph.com.sg/sqebatch/Batch/BatchAuth2/BatchDelegator';
            insert batchInterfaceSetting;
        }
        
        Delivery_Charge_Type__c testDeliveryChargeType = new Delivery_Charge_Type__c();
            testDeliveryChargeType.Name = 'T';
            testDeliveryChargeType.Default_Delivery_Charge_Type__c = 'T';
        insert testDeliveryChargeType; 
        
        Postage_Charge__c testPostageCharge = new Postage_Charge__c();
            testPostageCharge.Name = 'null';
            testPostageCharge.Amount__c = 10;
        insert testPostageCharge;
       
    }

}