src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Vendor_Code__c</fullName>
        <label>Vendor Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/BatchInterface_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Batch Interface Settings</label>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account field that is not read-only to be used in Adjustment Case. Field Value will be copied into Account Standard field and will not be exposed in detail page layout.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Account) (Do Not Use)</relationshipLabel>
        <relationshipName>Cases_Do_Not_Use</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Billing_Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Billing Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>Zuora__CustomerAccount__c.Zuora__Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Zuora__CustomerAccount__c.Zuora__Account__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_To_Update__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact To Update</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases (Contact To Update)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Main_Package__c</fullName>
        <description>Custom field for Main Package.</description>
        <label>Main Package</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stop_Request_Date__c</fullName>
        <label>Stop Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Cir_Planner_Schedule__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used as reference if requests are within circulation planning schedule.</description>
    <fields>
        <fullName>Mon_Fri_End_Time__c</fullName>
        <label>Mon-Fri End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Mon_Fri_Start_Time__c</fullName>
        <label>Mon-Fri Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sat_PH_End_Time__c</fullName>
        <label>Sat/PH End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sat_PH_Start_Time__c</fullName>
        <label>Sat/PH Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sun_End_Time__c</fullName>
        <label>Sun End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sun_Start_Time__c</fullName>
        <label>Sun Start Time</label>
        <type>DateTime</type>
    </fields>
    <label>Cir Planner Schedule</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Billing Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HomePhone__c</fullName>
        <description>User specified</description>
        <label>Home Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Recipient_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recipient Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vendor_Code__c</fullName>
        <formula>Account.Vendor_Code__c</formula>
        <label>Vendor Code</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Base_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Subscription to be renewed.</description>
        <label>Base Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Orders (Subscription for Renewal)</relationshipLabel>
        <relationshipName>Orders_Renewal</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_Account_Creation_Mode__c</fullName>
        <label>Billing Account Creation Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Create New Billing Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Use existing Billing Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.Billing_Indicator__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Billing Contact)</relationshipLabel>
        <relationshipName>Orders2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Type__c</fullName>
        <label>Order Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stop_Request_Date__c</fullName>
        <label>Stop Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND NOT 5) OR (1 AND 2 AND 3 AND 4 AND 5)</booleanFilter>
            <filterItems>
                <field>Zuora__Subscription__c.Subscription_Type_1__c</field>
                <operation>equals</operation>
                <value>Publication</value>
            </filterItems>
            <filterItems>
                <field>Zuora__Subscription__c.Zuora__Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Zuora__Subscription__c.Zuora__Status__c</field>
                <operation>notEqual</operation>
                <value>Cancelled</value>
            </filterItems>
            <filterItems>
                <field>$Source.Order_Type1__c</field>
                <operation>contains</operation>
                <value>Change of Subscription</value>
            </filterItems>
            <filterItems>
                <field>$Source.isChangeOfSubEntry__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Case__r.Account.Name</formula>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Order Line Items (Direct)</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Main_Package_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Main Package ID</label>
        <referenceTo>Package__c</referenceTo>
        <relationshipLabel>Order Line Items (Main Package ID)</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Line_Item__c</fullName>
        <displayFormat>A-{000000}</displayFormat>
        <label>Order Line Item #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items_Direct</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Stop_Request_Date__c</fullName>
        <label>Stop Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Term_Length__c</fullName>
        <label>Term Length (Mth)</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI{0000000000}</displayFormat>
        <label>Order Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Other__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Other</label>
</CustomObject>

src/objects/Product_Code__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Product Codes to bypass creation of Delivery Subscription</description>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>8</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Product Code</label>
</CustomObject>

src orig/classes/SP_CancelSubscriptionInZuoraTest.cls
@isTest
public class SP_CancelSubscriptionInZuoraTest {
    
    static testMethod void testSP_CancelSubscriptionInZuoraTest(){
        
        Cir_Planner_Schedule__c cir = new Cir_Planner_Schedule__c();
        cir.Name = 'CIR Plan Schedule';
        cir.Mon_Fri_End_Time__c = DateTime.newInstance(2014, 08, 19, 22, 0, 0);
        cir.Mon_Fri_Start_Time__c = DateTime.newInstance(2014, 08, 19, 8, 0, 0);
        cir.Sat_PH_End_Time__c = DateTime.newInstance(2014, 08, 18, 17, 0, 0);
        cir.Sat_PH_Start_Time__c = DateTime.newInstance(2014, 08, 18, 8, 0, 0);
        cir.Sun_End_Time__c = DateTime.newInstance(2014, 08, 18, 17, 0, 0);
        cir.Sun_Start_Time__c = DateTime.newInstance(2014, 08, 18, 17, 0, 0);
        database.insert(cir);
        
        List<Other__c> otherList = new List<Other__c>{
            new Other__c(Name='DTL', Value__c='23:59')
        };
        database.insert(otherList);
        
        BatchInterface_Settings__c bs = new BatchInterface_Settings__c();
        bs.Name = 'Endpoint Delegator';
        bs.Value__c = 'http://devcrsm.sph.com.sg/sqebatch/Batch/BatchAuth2/BatchDelegator';
        database.insert(bs);
        
        Account acc = TestDataFactory.createAccount(1, 'Direct Corporate')[0];
        acc.Vendor_Code__c = '01';
        database.insert(acc);
        
        Address__c address = TestDataFactory.createAddress(1)[0];
        database.insert(address);
        
        Contact con = TestDataFactory.createContact(1)[0];
        con.AccountId = acc.id;
        con.HomePhone__c = '321324321434';
        con.Billing_Indicator__c = True;
        //contact1.Recipient_Indicator__c = true;
        con.Address__c = address.Id;
        database.insert(con);  
        
        Zuora__CustomerAccount__c billAcc = TestDataFactory.createBillingAccount(1)[0];
        billAcc.Zuora__Account__c = acc.Id;
        database.insert(billAcc);
        
        Package__c pack = TestDataFactory.createPackage(1)[0];
        database.insert(pack);
        
        List<Zuora__Subscription__c> sub = TestDataFactory.createSubscription(1);
        sub[0].Zuora__CustomerAccount__c = billAcc.Id;
        sub[0].Main_Package__c = pack.Id;
        sub[0].Product_Code__c = '01';
        sub[0].Zuora__TermSettingType__c = 'Termed';
        sub[0].Term_Length__c = 1;
        sub[0].Term_Length1__c = '1'; 
        sub[0].Main_Package_1__c = pack.Id;
        sub[0].Zuora__SubscriptionStartDate__c = date.today();
        sub[0].Zuora__SubscriptionEndDate__c = date.today().addDays(1);
        database.insert(sub);
        
        List<Order__c> orders = TestDataFactory.createOrder(1);
        for(Order__c ord : orders){
        ord.Account__c = acc.id;
        ord.Order_Type__c = 'Renewal'; 
        ord.Base_Subscription__c = sub[0].id;
        ord.Billing_Contact__c = con.id;
        ord.Billing_Account_Creation_Mode__c = 'Create New Billing Account';
        }      
        database.insert(orders);
        
        List<Order_Line_Item__c> olis = TestDataFactory.createOrderLineItem(1);
        for(Order_Line_Item__c oli : olis ){
        oli.Order__c = orders[0].id; 
        oli.Main_Package_ID__c = pack.id; 
        oli.Subscription__c = sub[0].id;  
        oli.Start_Date__c = Date.Today().addDays(2);          
        }
        database.insert(olis);
        
        Test.startTest();
            
            SP_CancelSubscriptionInZuora batch = new SP_CancelSubscriptionInZuora();
            database.executeBatch(batch, 200);
               
            Database.BatchableContext BC;
            //batch.execute(BC, sub);
            
        Test.stopTest();
        
    }
    
    static testMethod void testSP_CancelSubscriptionInZuoraTest2(){
        
        Cir_Planner_Schedule__c cir = new Cir_Planner_Schedule__c();
        cir.Name = 'CIR Plan Schedule';
        cir.Mon_Fri_End_Time__c = DateTime.newInstance(2014, 08, 19, 22, 0, 0);
        cir.Mon_Fri_Start_Time__c = DateTime.newInstance(2014, 08, 19, 8, 0, 0);
        cir.Sat_PH_End_Time__c = DateTime.newInstance(2014, 08, 18, 17, 0, 0);
        cir.Sat_PH_Start_Time__c = DateTime.newInstance(2014, 08, 18, 8, 0, 0);
        cir.Sun_End_Time__c = DateTime.newInstance(2014, 08, 18, 17, 0, 0);
        cir.Sun_Start_Time__c = DateTime.newInstance(2014, 08, 18, 17, 0, 0);
        database.insert(cir);
        
        List<Other__c> otherList = new List<Other__c>{
            new Other__c(Name='DTL', Value__c='23:59')
        };
        database.insert(otherList);
        
        BatchInterface_Settings__c bs = new BatchInterface_Settings__c();
        bs.Name = 'Endpoint Delegator';
        bs.Value__c = 'http://devcrsm.sph.com.sg/sqebatch/Batch/BatchAuth2/BatchDelegator';
        database.insert(bs);
        
        Account acc = TestDataFactory.createAccount(1, 'Direct Corporate')[0];
        acc.Vendor_Code__c = '01';
        database.insert(acc);
        
        Address__c address = TestDataFactory.createAddress(1)[0];
        database.insert(address);
        
        Contact con = TestDataFactory.createContact(1)[0];
        con.AccountId = acc.id;
        con.HomePhone__c = '321324321434';
        con.Billing_Indicator__c = True;
        //contact1.Recipient_Indicator__c = true;
        con.Address__c = address.Id;
        database.insert(con);  
        
        Zuora__CustomerAccount__c billAcc = TestDataFactory.createBillingAccount(1)[0];
        billAcc.Zuora__Account__c = acc.Id;
        database.insert(billAcc);
        
        Package__c pack = TestDataFactory.createPackage(1)[0];
        database.insert(pack);
        
        List<Zuora__Subscription__c> sub = TestDataFactory.createSubscription(1);
        sub[0].Zuora__CustomerAccount__c = billAcc.Id;
        sub[0].Main_Package__c = pack.Id;
        sub[0].Product_Code__c = '01';
        sub[0].Zuora__TermSettingType__c = 'Termed';
        sub[0].Term_Length__c = 1;
        sub[0].Term_Length1__c = '1'; 
        sub[0].Main_Package_1__c = pack.Id;
        sub[0].Zuora__SubscriptionStartDate__c = date.today();
        sub[0].Zuora__SubscriptionEndDate__c = date.today().addDays(1);
        database.insert(sub);
        
        List<Order__c> orders = TestDataFactory.createOrder(1);
        for(Order__c ord : orders){
        ord.Account__c = acc.id;
        ord.Order_Type__c = 'Renewal'; 
        ord.Base_Subscription__c = sub[0].id;
        ord.Billing_Contact__c = con.id;
        ord.Billing_Account_Creation_Mode__c = 'Create New Billing Account';
        }      
        database.insert(orders);
        
        List<Order_Line_Item__c> olis = TestDataFactory.createOrderLineItem(1);
        for(Order_Line_Item__c oli : olis ){
        oli.Order__c = orders[0].id; 
        oli.Main_Package_ID__c = pack.id; 
        oli.Subscription__c = sub[0].id;  
        oli.Start_Date__c = Date.Today().addDays(2);          
        }
        database.insert(olis);
        
        Date newDate = sub[0].Zuora__SubscriptionEndDate__c;
        Boolean newBoolean = true;
        
        Test.startTest();
            
            SP_CancelSubscriptionInZuora batch1 = new SP_CancelSubscriptionInZuora(newDate, newBoolean);
            database.executeBatch(batch1, 200);
               
            Database.BatchableContext BC;
            //batch.execute(BC, sub);
            
        Test.stopTest();
        
    }
    
     static testMethod void testSP_CancelSubscriptionInZuoraTest3(){
        
        Cir_Planner_Schedule__c cir = new Cir_Planner_Schedule__c();
        cir.Name = 'CIR Plan Schedule';
        cir.Mon_Fri_End_Time__c = DateTime.newInstance(2014, 08, 19, 22, 0, 0);
        cir.Mon_Fri_Start_Time__c = DateTime.newInstance(2014, 08, 19, 8, 0, 0);
        cir.Sat_PH_End_Time__c = DateTime.newInstance(2014, 08, 18, 17, 0, 0);
        cir.Sat_PH_Start_Time__c = DateTime.newInstance(2014, 08, 18, 8, 0, 0);
        cir.Sun_End_Time__c = DateTime.newInstance(2014, 08, 18, 17, 0, 0);
        cir.Sun_Start_Time__c = DateTime.newInstance(2014, 08, 18, 17, 0, 0);
        database.insert(cir);
        
        List<Other__c> otherList = new List<Other__c>{
            new Other__c(Name='DTL', Value__c='23:59')
        };
        database.insert(otherList);
        
        BatchInterface_Settings__c bs = new BatchInterface_Settings__c();
        bs.Name = 'Endpoint Delegator';
        bs.Value__c = 'http://devcrsm.sph.com.sg/sqebatch/Batch/BatchAuth2/BatchDelegator';
        database.insert(bs);
        
        Account acc = TestDataFactory.createAccount(1, 'Direct Corporate')[0];
        acc.Vendor_Code__c = '01';
        database.insert(acc);
        
        Address__c address = TestDataFactory.createAddress(1)[0];
        database.insert(address);
        
        Contact con = TestDataFactory.createContact(1)[0];
        con.AccountId = acc.id;
        con.HomePhone__c = '321324321434';
        con.Billing_Indicator__c = True;
        //contact1.Recipient_Indicator__c = true;
        con.Address__c = address.Id;
        database.insert(con);  
        
        Zuora__CustomerAccount__c billAcc = TestDataFactory.createBillingAccount(1)[0];
        billAcc.Zuora__Account__c = acc.Id;
        database.insert(billAcc);
        
        Package__c pack = TestDataFactory.createPackage(1)[0];
        database.insert(pack);
        
        List<Zuora__Subscription__c> sub = TestDataFactory.createSubscription(1);
        sub[0].Zuora__CustomerAccount__c = billAcc.Id;
        sub[0].Main_Package__c = pack.Id;
        sub[0].Product_Code__c = '01';
        sub[0].Zuora__TermSettingType__c = 'Termed';
        sub[0].Term_Length__c = 1;
        sub[0].Term_Length1__c = '1'; 
        sub[0].Main_Package_1__c = pack.Id;
        sub[0].Zuora__SubscriptionStartDate__c = date.today();
        sub[0].Zuora__SubscriptionEndDate__c = date.today().addDays(1);
        database.insert(sub);
        
        List<Order__c> orders = TestDataFactory.createOrder(1);
        for(Order__c ord : orders){
        ord.Account__c = acc.id;
        ord.Order_Type__c = 'Renewal'; 
        ord.Base_Subscription__c = sub[0].id;
        ord.Billing_Contact__c = con.id;
        ord.Billing_Account_Creation_Mode__c = 'Create New Billing Account';
        }      
        database.insert(orders);
        
        List<Order_Line_Item__c> olis = TestDataFactory.createOrderLineItem(1);
        for(Order_Line_Item__c oli : olis ){
        oli.Order__c = orders[0].id; 
        oli.Main_Package_ID__c = pack.id; 
        oli.Subscription__c = sub[0].id;  
        oli.Start_Date__c = Date.Today().addDays(2);          
        }
        database.insert(olis);
        
        Date newDate = sub[0].Zuora__SubscriptionEndDate__c;
        List<String> newList = new List<String>();
        newList.add(sub[0].Zuora__TermSettingType__c);
        newList.add(sub[0].Product_Code__c);
        Integer newInt = 1;
        
        Test.startTest();
            
            SP_CancelSubscriptionInZuora batch2 = new SP_CancelSubscriptionInZuora(newList, newInt, newDate);
            database.executeBatch(batch2, 200);
               
            Database.BatchableContext BC;
            //batch.execute(BC, sub);
            
        Test.stopTest();
        
    }
    
     
     static testMethod void testSP_CancelSubscriptionInZuoraTest4(){
        
        Cir_Planner_Schedule__c cir = new Cir_Planner_Schedule__c();
        cir.Name = 'CIR Plan Schedule';
        cir.Mon_Fri_End_Time__c = DateTime.newInstance(2014, 08, 19, 22, 0, 0);
        cir.Mon_Fri_Start_Time__c = DateTime.newInstance(2014, 08, 19, 8, 0, 0);
        cir.Sat_PH_End_Time__c = DateTime.newInstance(2014, 08, 18, 17, 0, 0);
        cir.Sat_PH_Start_Time__c = DateTime.newInstance(2014, 08, 18, 8, 0, 0);
        cir.Sun_End_Time__c = DateTime.newInstance(2014, 08, 18, 17, 0, 0);
        cir.Sun_Start_Time__c = DateTime.newInstance(2014, 08, 18, 17, 0, 0);
        database.insert(cir);
        
        List<Other__c> otherList = new List<Other__c>{
            new Other__c(Name='DTL', Value__c='23:59')
        };
        database.insert(otherList);
        
        BatchInterface_Settings__c bs = new BatchInterface_Settings__c();
        bs.Name = 'Endpoint Delegator';
        bs.Value__c = 'http://devcrsm.sph.com.sg/sqebatch/Batch/BatchAuth2/BatchDelegator';
        database.insert(bs);
        
        Account acc = TestDataFactory.createAccount(1, 'Direct Corporate')[0];
        acc.Vendor_Code__c = '01';
        database.insert(acc);
        
        Address__c address = TestDataFactory.createAddress(1)[0];
        database.insert(address);
        
        Contact con = TestDataFactory.createContact(1)[0];
        con.AccountId = acc.id;
        con.HomePhone__c = '321324321434';
        con.Billing_Indicator__c = True;
        //contact1.Recipient_Indicator__c = true;
        con.Address__c = address.Id;
        database.insert(con);  
        
        Zuora__CustomerAccount__c billAcc = TestDataFactory.createBillingAccount(1)[0];
        billAcc.Zuora__Account__c = acc.Id;
        database.insert(billAcc);
        
        Package__c pack = TestDataFactory.createPackage(1)[0];
        database.insert(pack);
        
        date subStartDate = date.today().addDays(2);
        
        List<Zuora__Subscription__c> sub = TestDataFactory.createSubscription(1);
        sub[0].Zuora__CustomerAccount__c = billAcc.Id;
        sub[0].Zuora__Account__c = acc.Id;
        sub[0].Main_Package__c = pack.Id;
        sub[0].Product_Code__c = '01';
        sub[0].Zuora__TermSettingType__c = 'Termed';
        sub[0].Term_Length__c = 1;
        sub[0].Term_Length1__c = '1'; 
        sub[0].Main_Package_1__c = pack.Id;
        sub[0].Zuora__SubscriptionStartDate__c = subStartDate;
        sub[0].Zuora__SubscriptionEndDate__c = subStartDate.addMonths(Integer.valueOf(1)).addDays(-1);
        sub[0].Zuora__Zuora_Id__c = 'test123';
        database.insert(sub);
        
        List<Order__c> orders = TestDataFactory.createOrder(1);
        for(Order__c ord : orders){
        ord.Account__c = acc.id;
        ord.Order_Type__c = 'Renewal'; 
        ord.Base_Subscription__c = sub[0].id;
        ord.Billing_Contact__c = con.id;
        ord.Billing_Account_Creation_Mode__c = 'Create New Billing Account';
        }      
        database.insert(orders);
        
        Case cas = TestDataFactory.createcase(1, 'Complaint - Magazine')[0];
        cas.RecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType='Case' AND Name = 'Stop Subscription'].Id;
        cas.Account__c = acc.Id;
        cas.Billing_Account_Name__c = billAcc.Id;
        //cas.Contact_To_Update__c = con.Id;
        database.insert(cas);
        
        List<Order_Line_Item__c> olis = TestDataFactory.createOrderLineItem(1);
        for(Order_Line_Item__c oli : olis ){
        oli.Order__c = orders[0].id; 
        oli.Main_Package_ID__c = pack.id; 
        oli.Subscription__c = sub[0].id;  
        oli.Start_Date__c = Date.Today().addDays(2);
        oli.Case__c = cas.Id;
        oli.Stop_Request_Date__c = date.today().addDays(10);          
        }
        database.insert(olis);    

        String newString = sub[0].Zuora__TermSettingType__c;
        Test.startTest();
            
            SP_CancelSubscriptionInZuora batch3 = new SP_CancelSubscriptionInZuora(newString);
            Database.BatchableContext BC;
            batch3.start(BC);
            //batch3.execute(BC, sub);
            
        Test.stopTest();
        
    }
    
    static testMethod void testSP_CancelSubscriptionInZuoraTest5(){
        
        Cir_Planner_Schedule__c cir = new Cir_Planner_Schedule__c();
        cir.Name = 'CIR Plan Schedule';
        cir.Mon_Fri_End_Time__c = DateTime.newInstance(2014, 08, 19, 22, 0, 0);
        cir.Mon_Fri_Start_Time__c = DateTime.newInstance(2014, 08, 19, 8, 0, 0);
        cir.Sat_PH_End_Time__c = DateTime.newInstance(2014, 08, 18, 17, 0, 0);
        cir.Sat_PH_Start_Time__c = DateTime.newInstance(2014, 08, 18, 8, 0, 0);
        cir.Sun_End_Time__c = DateTime.newInstance(2014, 08, 18, 17, 0, 0);
        cir.Sun_Start_Time__c = DateTime.newInstance(2014, 08, 18, 17, 0, 0);
        database.insert(cir);
        
        List<Other__c> otherList = new List<Other__c>{
            new Other__c(Name='DTL', Value__c='23:59')
        };
        database.insert(otherList);
        
        BatchInterface_Settings__c bs = new BatchInterface_Settings__c();
        bs.Name = 'Endpoint Delegator';
        bs.Value__c = 'http://devcrsm.sph.com.sg/sqebatch/Batch/BatchAuth2/BatchDelegator';
        database.insert(bs);
        
        Account acc = TestDataFactory.createAccount(1, 'Direct Corporate')[0];
        acc.Vendor_Code__c = '01';
        database.insert(acc);
        
        Address__c address = TestDataFactory.createAddress(1)[0];
        database.insert(address);
        
        Contact con = TestDataFactory.createContact(1)[0];
        con.AccountId = acc.id;
        con.HomePhone__c = '321324321434';
        con.Billing_Indicator__c = True;
        //contact1.Recipient_Indicator__c = true;
        con.Address__c = address.Id;
        database.insert(con);  
        
        Zuora__CustomerAccount__c billAcc = TestDataFactory.createBillingAccount(1)[0];
        billAcc.Zuora__Account__c = acc.Id;
        database.insert(billAcc);
        
        Package__c pack = TestDataFactory.createPackage(1)[0];
        database.insert(pack);
        
        date subStartDate = date.today().addDays(2);
        
        List<Zuora__Subscription__c> sub = TestDataFactory.createSubscription(1);
        sub[0].Zuora__CustomerAccount__c = billAcc.Id;
        sub[0].Zuora__Account__c = acc.Id;
        sub[0].Main_Package__c = pack.Id;
        sub[0].Product_Code__c = '01';
        sub[0].Zuora__TermSettingType__c = 'Termed';
        sub[0].Term_Length__c = 1;
        sub[0].Term_Length1__c = '1'; 
        sub[0].Main_Package_1__c = pack.Id;
        sub[0].Zuora__SubscriptionStartDate__c = subStartDate;
        //sub[0].Zuora__SubscriptionEndDate__c = subStartDate.addMonths(Integer.valueOf(1)).addDays(-1);
        sub[0].Zuora__Zuora_Id__c = 'test123';
        database.insert(sub);
        
        List<Order__c> orders = TestDataFactory.createOrder(1);
        for(Order__c ord : orders){
        ord.Account__c = acc.id;
        ord.Order_Type__c = 'Renewal'; 
        ord.Base_Subscription__c = sub[0].id;
        ord.Billing_Contact__c = con.id;
        ord.Billing_Account_Creation_Mode__c = 'Create New Billing Account';
        }      
        database.insert(orders);
        
        Case cas = TestDataFactory.createcase(1, 'Complaint - Magazine')[0];
        cas.RecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType='Case' AND Name = 'Stop Subscription'].Id;
        cas.Account__c = acc.Id;
        cas.Billing_Account_Name__c = billAcc.Id;
        cas.Case_Sub_Status__c = 'Case Created';
        //cas.Contact_To_Update__c = con.Id;
        database.insert(cas);
        
        List<Order_Line_Item__c> olis = TestDataFactory.createOrderLineItem(1);
        for(Order_Line_Item__c oli : olis ){
        oli.Order__c = orders[0].id; 
        oli.Main_Package_ID__c = pack.id; 
        oli.Subscription__c = sub[0].id;  
        oli.Start_Date__c = Date.Today().addDays(2);
        oli.Case__c = cas.Id;
        oli.Stop_Request_Date__c = date.today().addDays(10);          
        }
        database.insert(olis);    

        String newString = sub[0].Zuora__TermSettingType__c;
        Test.startTest();
            
            SP_CancelSubscriptionInZuora batch3 = new SP_CancelSubscriptionInZuora(newString);
            Database.BatchableContext BC;
            batch3.start(BC);
            //batch3.execute(BC, sub);
            
        Test.stopTest();
        
    }
    
}