src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Auto_Number__c</fullName>
        <description>Generates auto number to be copied on the Standard AccountNumber field if &quot;Generate Account Number?&quot; checkbox field is ticked.</description>
        <displayFormat>3{0000000}</displayFormat>
        <label>Account Auto Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Recipient_Number__c</fullName>
        <displayFormat>{00000000}</displayFormat>
        <label>Recipient Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Singpost_Address__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Postal Code</label>
        <referenceTo>Singpost_Address__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_Code__c</fullName>
        <label>Vendor Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Block_House_Number__c</fullName>
        <description>This field will be displayed if record type field is Local.
Read-only. Auto-populated by the system based on Postal Code</description>
        <label>House/Block Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be displayed if record type field is Local.
User specified</description>
        <label>Postal Code</label>
        <referenceTo>Singpost_Address__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/BatchInterface_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Batch Interface Settings</label>
</CustomObject>

src/objects/BT_CO_Batch_Run_Request__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Run_Date__c</fullName>
        <label>Batch Run Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Interface_ID__c</fullName>
        <label>Interface ID</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>BT_CO_Batch_Run_Request</label>
    <nameField>
        <displayFormat>BRR-{0000000000}</displayFormat>
        <label>Batch Run Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT_CO_Batch_Run_Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recipient_Contact__c</fullName>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Recipient Contact</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recipient_Number__c</fullName>
        <description>Recipient Number will be auto set by the system.</description>
        <label>Recipient Number</label>
        <precision>17</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vendor_Code__c</fullName>
        <formula>Account.Vendor_Code__c</formula>
        <label>Vendor Code</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Other__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Other</label>
</CustomObject>

src/objects/Product_Code__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Product Codes to bypass creation of Delivery Subscription</description>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>8</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Product Code</label>
</CustomObject>

src/objects/Product_Publication__c.object
<CustomObject>
    <fields>
        <fullName>Product_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Code</label>
        <referenceTo>Zuora__Product__c</referenceTo>
        <relationshipLabel>Product Publications</relationshipLabel>
        <relationshipName>Product_Publications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Product Publications</relationshipLabel>
        <relationshipName>Product_Publications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ZProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ZProduct</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>zqu__ZProduct__c.zqu__Deleted__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>Product Publications</relationshipLabel>
        <relationshipName>Product_Publications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Publication</label>
    <nameField>
        <displayFormat>PPUB-{00000000}</displayFormat>
        <label>Product Publication Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Publication__c.object
<CustomObject>
    <fields>
        <fullName>Platform_Type__c</fullName>
        <label>Platform Type</label>
        <picklist>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tablet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Smartphone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All in One (AIO)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Publication_Code__c</fullName>
        <externalId>true</externalId>
        <label>Publication Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Published_Days__c</fullName>
        <label>Published Days</label>
        <length>7</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <label>Publication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Singpost_Address__c.object
<CustomObject>
    <label>Singpost Address</label>
    <nameField>
        <label>Postal Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Singpost Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/BT_AB_HDS037DX_DailyVendorSubsP2Test.cls
//test class for BT_AB_HDS037DX_DailyVendorSubscriptionP2
@isTest
private class BT_AB_HDS037DX_DailyVendorSubsP2Test{
    static testMethod void testBT_AB_HDS037DX_DailyVendorSubscriptionP2(){
        //start custom settings
        Other__c other = new Other__c();
        other.Name = 'DTL';
        other.Value__c = '23:59';
        database.insert(other);
        
        BatchInterface_Settings__c integ = new BatchInterface_Settings__c();
        integ.Name = 'Endpoint Delegator';
        integ.Value__c = 'http://devcrsm.sph.com.sg/sqebatch/Batch/BatchAuth2/BatchDelegator';
        database.insert(integ);
        //end custom settings
    
        //start test data
        Account acc = TestDataFactory.createAccount(1, 'Direct Corporate')[0];
        acc.Vendor_Code__c = '01';
        database.insert(acc);
        
        Singpost_Address__c postal = TestDataFactory.createSingpostAddress(1)[0];
        postal.Name = '6000';
        database.insert(postal);
        
        Address__c add = TestDataFactory.createAddress(1)[0];
        add.Block_House_Number__c = '12';
        add.Postal_Code__c = postal.Id;
        database.insert(add);
        
        Contact con = TestDataFactory.createContact(1)[0];
        con.Recipient_Number__c = 123456;
        con.Address__c = add.Id;
        database.insert(con);
        
        Zuora__CustomerAccount__c billAcc = TestDataFactory.createBillingAccount(1)[0];
        billAcc.Zuora__Account__c = acc.Id;
        database.insert(billAcc);
        
        Account accQ = [SELECT Id, Account_Auto_Number__c FROM Account WHERE Id=:acc.Id];
        
        Zuora__Subscription__c sub = TestDataFactory.createSubscription(1)[0];
        sub.Zuora__CustomerAccount__c = billAcc.Id;
        sub.Zuora__SubscriptionStartDate__c = date.today();
        sub.Term_Length1__c = '0.1';
        sub.Product_Code__c = '01';
        sub.Recipient_Contact__c = con.Id;
        sub.Frequency_1__c = 'Default';
        sub.Qty1__c = '3';
        sub.Vendor_1__c = acc.Id;
        sub.Zuora__Account__c = accQ.Id;
        database.insert(sub);
        
        Zuora__Subscription__c subQ = [SELECT Zuora__SubscriptionEndDate__c FROM Zuora__Subscription__c WHERE id=:sub.Id];
        
        BT_CO_Batch_Run_Request__c batchRun = new BT_CO_Batch_Run_Request__c();
        batchRun.Interface_ID__c = 'HDS037DX';
        batchRun.End_Time__c = null;
        batchRun.Batch_Run_Date__c = (subQ.Zuora__SubscriptionEndDate__c).addDays(-1);
        database.insert(batchRun);
        
        zqu__ZProduct__c zp = TestDataFactory.createZProduct(1)[0];
        zp.ProductCode__c = '01';
        database.insert(zp);
        
        List<Publication__c> pub = TestDataFactory.createPublication(2);
        for(Publication__c p: pub){
            p.Platform_Type__c = 'Print';   
            p.Published_Days__c = 'YYYYYYY';
        }
        database.insert(pub);
        
        Product_Publication__c prodPub = TestDataFactory.createProductPublication(1)[0];
        prodPub.ZProduct__c = zp.Id;
        prodPub.Publication_Code__c = pub[0].Id;
        database.insert(prodPub);
        
        Product_Publication__c pp = new Product_Publication__c();
        pp.ZProduct__c = zp.Id;
        pp.Publication_Code__c = pub[1].Id;
        database.insert(pp);
        //end test data
    
        test.startTest();
            BT_AB_HDS037DX_DailyVendorSubscriptionP2 batch = new BT_AB_HDS037DX_DailyVendorSubscriptionP2();
            ID batchID = database.executeBatch(batch, 200);
            system.assertNotEquals(batchID, null);
        test.stopTest();
    }
}