src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mailing_Agent_Code__c</fullName>
        <label>Mailing Agent Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Code__c</fullName>
        <label>Vendor Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Group__c</fullName>
        <label>Vendor Group</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Mailing_Agent</fullName>
        <active>true</active>
        <label>Mailing Agent</label>
    </recordTypes>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Vendor Profile</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>House_Type__c</fullName>
        <formula>Postal_Code__r.House_Type_Description__c</formula>
        <label>House Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Sector__c</fullName>
        <formula>Postal_Code__r.Postal_Sector__c</formula>
        <label>Postal Sector</label>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <recordTypes>
        <fullName>Internal</fullName>
        <active>true</active>
        <description>For Internal Subscribers</description>
        <label>Internal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/BA_INT_DATA_POOL__c.object
<CustomObject>
    <description>custom object for batch integration purposes.
the object act as a single repository for the entire batch data set across all interfaces.
{Job_ID, Record_Type, Group_ID, Sort_Order, Data_in_CSV_format}</description>
    <fields>
        <fullName>export_data__c</fullName>
        <description>the comma separated values fetched fro SFDC per batch job</description>
        <label>export data</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>group_id__c</fullName>
        <description>the unique identifier for the record (eg account_id or invoice_id)</description>
        <label>group id</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>insert_time__c</fullName>
        <description>the start time for the batch job</description>
        <label>insertion time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>job_id__c</fullName>
        <description>job name for the scheduled batch job</description>
        <label>job_id</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>run_for_date__c</fullName>
        <description>EOD date for which the batch job was run</description>
        <label>run for date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>BA_INT_DATA_POOL</label>
    <nameField>
        <label>BA_INT_DATA_POOL Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA_INT_DATA_POOL</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BatchInterface_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Batch Interface Settings</label>
</CustomObject>

src/objects/BT_CO_MIRO_SubscriptionIssueFile__c.object
<CustomObject>
    <description>BT_CO_MIRO_SubscriptionIssueFile
to be purged daily... expected volume 30000</description>
    <fields>
        <fullName>Publication_Code__c</fullName>
        <label>Publication_Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication_Issue_Date__c</fullName>
        <label>Publication_Issue_Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>house_type__c</fullName>
        <label>house_type</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>office_house_mail_indicator__c</fullName>
        <label>office_house_mail_indicator</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>postal_sector__c</fullName>
        <label>postal_sector</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sub_channel_code__c</fullName>
        <label>sub_channel_code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subscriber_count__c</fullName>
        <label>subscriber_count</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>subscription_copies__c</fullName>
        <label>subscription_copies</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>vendor_number__c</fullName>
        <label>vendor_number</label>
        <length>26</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>BT_CO_MIRO_SubscriptionIssueFile</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>BT_CO_MIRO_ Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT_CO_MIRO_SubscriptionIssueFile</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Cir_Planner_Schedule__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used as reference if requests are within circulation planning schedule.</description>
    <fields>
        <fullName>Mon_Fri_End_Time__c</fullName>
        <label>Mon-Fri End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Mon_Fri_Start_Time__c</fullName>
        <label>Mon-Fri Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sat_PH_End_Time__c</fullName>
        <label>Sat/PH End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sat_PH_Start_Time__c</fullName>
        <label>Sat/PH Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sun_End_Time__c</fullName>
        <label>Sun End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sun_Start_Time__c</fullName>
        <label>Sun Start Time</label>
        <type>DateTime</type>
    </fields>
    <label>Cir Planner Schedule</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_Code__c</fullName>
        <formula>Account.Vendor_Code__c</formula>
        <label>Vendor Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Group__c</fullName>
        <formula>Account.Vendor_Group__c</formula>
        <label>Vendor Group</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Other__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Other</label>
</CustomObject>

src/classes/BT_AB_MIRO055DX_VendorCreditingFileTest.cls
@isTest 
public class BT_AB_MIRO055DX_VendorCreditingFileTest {
        static testMethod void testBT_AB_MIRO055DX_VendorCreditingFile() {
        
        Cir_Planner_Schedule__c cir = new Cir_Planner_Schedule__c();
        cir.Name = 'CIR Plan Schedule';
        cir.Mon_Fri_End_Time__c = DateTime.newInstance(2014, 08, 19, 22, 0, 0);
        cir.Mon_Fri_Start_Time__c = DateTime.newInstance(2014, 08, 19, 8, 0, 0);
        cir.Sat_PH_End_Time__c = DateTime.newInstance(2014, 08, 18, 17, 0, 0);
        cir.Sat_PH_Start_Time__c = DateTime.newInstance(2014, 08, 18, 8, 0, 0);
        cir.Sun_End_Time__c = DateTime.newInstance(2014, 08, 18, 17, 0, 0);
        cir.Sun_Start_Time__c = DateTime.newInstance(2014, 08, 18, 17, 0, 0);
        database.insert(cir);
        
        List<Other__c> otherList = new List<Other__c>{
            new Other__c(Name='DTL', Value__c='23:59')
        };    
        database.insert(otherList);
        
        BatchInterface_Settings__c bs = new BatchInterface_Settings__c();
        bs.Name = 'Endpoint Delegator';
        bs.Value__c = 'http://devcrsm.sph.com.sg/sqebatch/Batch/BatchAuth2/BatchDelegator';
        database.insert(bs);
        
        
        
        List<Account> accList = TestDataFactory.createAccount(1, 'Vendor');
        accList[0].recordTypeId = [SELECT Id, Name FROM RecordType WHERE sObjectType = 'Account' AND DeveloperName = 'Vendor'].id;
        accList[0].Name = 'Vendor';
        accList[0].Vendor_Code__c = '01';
        accList[0].Active__c = true;
        accLIst[0].Vendor_group__c = '1';
        database.insert(accList);
        
        
        BT_CO_MIRO_SubscriptionIssueFile__c sif1 = new BT_CO_MIRO_SubscriptionIssueFile__c();
        sif1.Publication_Code__c = 'code';
        sif1.Publication_Issue_Date__c = System.Today();
        sif1.postal_sector__c = 'MN';
        sif1.vendor_number__c = '01';
        sif1.office_house_mail_indicator__c = 'Y';
        sif1.house_type__c = 'A';
        sif1.sub_channel_code__c = 'ABC';
        sif1.subscription_copies__c = 200;
        sif1.subscriber_count__c = 100;
        
        insert sif1;
        
        //AggregateResult ar = [SELECT Publication_Code__c,Publication_Issue_Date__c,postal_sector__c,vendor_number__c,office_house_mail_indicator__c,house_type__c,
        //            sub_channel_code__c,sum(subscription_copies__c),count(subscriber_count__c) FROM BT_CO_MIRO_SubscriptionIssueFile__c where CreatedDate = :dateTime.now() AND Vendor_Number__c =:accList[0].Vendor_Code__c and Vendor_Number__c != 'MLAGN' and subscription_copies__c > 0 group by Publication_Code__c,Publication_Issue_Date__c,postal_sector__c,vendor_number__c, office_house_mail_indicator__c,house_type__c,sub_channel_code__c];
        //system.assertEquals(ar, null);
        
        
        
        test.startTest();
         
            BT_AB_MIRO055DX_VendorCreditingFile batch = new BT_AB_MIRO055DX_VendorCreditingFile();
            database.executeBatch(batch, 200);
            //Database.BatchableContext BC;
            //batch.execute(BC, accList);
        test.stopTest();    
        }

    static testMethod void testBT_AB_MIRO055DX_VendorCreditingFile2() {
        
        Cir_Planner_Schedule__c cir = new Cir_Planner_Schedule__c();
        cir.Name = 'CIR Plan Schedule';
        cir.Mon_Fri_End_Time__c = DateTime.newInstance(2014, 08, 19, 22, 0, 0);
        cir.Mon_Fri_Start_Time__c = DateTime.newInstance(2014, 08, 19, 8, 0, 0);
        cir.Sat_PH_End_Time__c = DateTime.newInstance(2014, 08, 18, 17, 0, 0);
        cir.Sat_PH_Start_Time__c = DateTime.newInstance(2014, 08, 18, 8, 0, 0);
        cir.Sun_End_Time__c = DateTime.newInstance(2014, 08, 18, 17, 0, 0);
        cir.Sun_Start_Time__c = DateTime.newInstance(2014, 08, 18, 17, 0, 0);
        database.insert(cir);
        
        List<Other__c> otherList = new List<Other__c>{
            new Other__c(Name='DTL', Value__c='23:59')
        };
        database.insert(otherList);
        
        BatchInterface_Settings__c bs = new BatchInterface_Settings__c();
        bs.Name = 'Endpoint Delegator';
        bs.Value__c = 'http://devcrsm.sph.com.sg/sqebatch/Batch/BatchAuth2/BatchDelegator';
        database.insert(bs);
        
        RecordType accRec = [SELECT Id, DeveloperName FROM RecordType WHERE sObjectType = 'Account' AND DeveloperName = 'Mailing_Agent'];
        
        List<Account> accList = TestDataFactory.createAccount(2, 'Mailing_Agent');
        accList[0].RecordTypeId = accRec.id;
        accList[0].Name = 'Mailing_Agent';
        accList[0].Mailing_Agent_Code__c = 'MLAGN';
       // accList[0].Vendor_group__c = 'H';
        accList[0].Active__c = true;

        database.insert(accList);
        
        system.assertNotEquals(accList.size(), 0);
        
        RecordType rt = [SELECT Id FROM RecordType WHERE sObjectType = 'Address__c' AND Name = 'Internal'];
        
        Address__c ad = TestDataFactory.createAddress(1)[0];
        ad.recordType = rt;
        database.insert(ad);
        
        List<Contact> conList = TestDataFactory.createContactRecType(1, 'Vendor Contact');
        for(Contact con: conList){
        con.AccountId = accList[0].id;
        con.Address__c =ad.id;
        }
        database.insert(conList);
        
        
        
        BT_CO_MIRO_SubscriptionIssueFile__c sif1 = new BT_CO_MIRO_SubscriptionIssueFile__c();
        sif1.Publication_Code__c = '03';
        sif1.Publication_Issue_Date__c = date.Today();
        sif1.postal_sector__c = 'AB';
        sif1.office_house_mail_indicator__c = 'A';
        sif1.house_type__c = 'A';
        sif1.sub_channel_code__c = 'ABC';
        sif1.vendor_number__c = '03';
        sif1.subscription_copies__c = 2;
        
        insert sif1;
        
        BA_INT_DATA_POOL__c datapoolHRecord = new BA_INT_DATA_POOL__c();
        
        datapoolHRecord.name = 'MIRO055DX';
        datapoolHRecord.job_id__c = 'MIRO055DX';
        datapoolHRecord.group_id__c = 'Master';
        datapoolHRecord.run_for_date__c = Date.today();      
        datapoolHRecord.insert_time__c = DateTime.now(); 
        datapoolHRecord.export_data__c = 'H,' + DateTime.now();       
        
        insert datapoolHRecord;   
        test.startTest();
        
        Set<Id> accID = new Set<Id>();
        accID.add(accList[0].id);
        
        List<Account> accountList = [SELECT Id, Name FROM Account WHERE Id IN:accID AND Name = 'Mailing_Agent'];
        system.assertNotEquals(accountList, null); 
        
            BT_AB_MIRO055DX_VendorCreditingFile batch = new BT_AB_MIRO055DX_VendorCreditingFile();
            Id batchID = database.executeBatch(batch, 200);

        test.stopTest();    
        }
    
    static testMethod void testBT_AB_MIRO055DX_VendorCreditingFile3() {
        
        Cir_Planner_Schedule__c cir = new Cir_Planner_Schedule__c();
        cir.Name = 'CIR Plan Schedule';
        cir.Mon_Fri_End_Time__c = DateTime.newInstance(2014, 08, 19, 22, 0, 0);
        cir.Mon_Fri_Start_Time__c = DateTime.newInstance(2014, 08, 19, 8, 0, 0);
        cir.Sat_PH_End_Time__c = DateTime.newInstance(2014, 08, 18, 17, 0, 0);
        cir.Sat_PH_Start_Time__c = DateTime.newInstance(2014, 08, 18, 8, 0, 0);
        cir.Sun_End_Time__c = DateTime.newInstance(2014, 08, 18, 17, 0, 0);
        cir.Sun_Start_Time__c = DateTime.newInstance(2014, 08, 18, 17, 0, 0);
        database.insert(cir);
        
        List<Other__c> otherList = new List<Other__c>{
            new Other__c(Name='DTL', Value__c='23:59')
        };
        database.insert(otherList);
        
        BatchInterface_Settings__c bs = new BatchInterface_Settings__c();
        bs.Name = 'Endpoint Delegator';
        bs.Value__c = 'http://devcrsm.sph.com.sg/sqebatch/Batch/BatchAuth2/BatchDelegator';
        database.insert(bs);
        
        RecordType accRec = [SELECT Id, DeveloperName FROM RecordType WHERE sObjectType = 'Account' AND DeveloperName = 'Vendor'];
        
        List<Account> accList = TestDataFactory.createAccount(2, 'Vendor');
        accList[0].RecordTypeId = accRec.id;
        accList[0].Name = 'Vendor';
        accList[0].Vendor_group__c = 'A';
        accList[0].Active__c = true;
        accList[0].Vendor_Code__c = '01';

        database.insert(accList);
        
        system.assertNotEquals(accList.size(), 0);
        
        RecordType rt = [SELECT Id FROM RecordType WHERE sObjectType = 'Address__c' AND Name = 'Internal'];
        
        Address__c ad = TestDataFactory.createAddress(1)[0];
        ad.recordType = rt;
        database.insert(ad);
        
        List<Contact> conList = TestDataFactory.createContactRecType(1, 'Vendor Contact');
        for(Contact con: conList){
        con.AccountId = accList[0].id;
        con.Address__c =ad.id;
        }
        database.insert(conList);
        
        
        
        BT_CO_MIRO_SubscriptionIssueFile__c sif1 = new BT_CO_MIRO_SubscriptionIssueFile__c();
        sif1.Publication_Code__c = '03';
        sif1.Publication_Issue_Date__c = date.Today();
        sif1.postal_sector__c = 'AB';
        sif1.office_house_mail_indicator__c = 'A';
        sif1.house_type__c = 'A';
        sif1.sub_channel_code__c = 'ABC';
        sif1.vendor_number__c = '03';
        sif1.subscription_copies__c = 2;
        
        insert sif1;
        
        BA_INT_DATA_POOL__c datapoolHRecord = new BA_INT_DATA_POOL__c();
        
        datapoolHRecord.name = 'MIRO055DX';
        datapoolHRecord.job_id__c = 'MIRO055DX';
        datapoolHRecord.group_id__c = 'Master';
        datapoolHRecord.run_for_date__c = Date.today();      
        datapoolHRecord.insert_time__c = DateTime.now(); 
        datapoolHRecord.export_data__c = 'H,' + DateTime.now();       
        
        insert datapoolHRecord;   
        test.startTest();
        
        Set<Id> accID = new Set<Id>();
        accID.add(accList[0].id);
        
        String interfaceId = 'MIRO055DX';
        String batchRunDate = BT_AU_BATCHRUNREQUEST_UpdateInfo.getBatchRunDate(interfaceId); 
        
        List<BT_CO_MIRO_SubscriptionIssueFile__c> btcoSub = [SELECT CreatedDate FROM BT_CO_MIRO_SubscriptionIssueFile__c WHERE CreatedDate = : Datetime.valueOfGmt(batchRunDate+' 00:00:00') ];
        List<Account> accountList = [SELECT Id, Name FROM Account WHERE Id IN:accID AND Name = 'Vendor'];
        system.assertNotEquals(accountList, null); 
        
            BT_AB_MIRO055DX_VendorCreditingFile batch = new BT_AB_MIRO055DX_VendorCreditingFile();
            Id batchID = database.executeBatch(batch, 200);

        test.stopTest();    
        }
}