src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is auto-populated via trigger. See Section 1.2.8.4. Apex Trigger).</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Activation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Vendor Profile</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <label>Sub Status</label>
        <picklist>
            <controllingField>Category__c</controllingField>
            <picklistValues>
                <fullName>Assess for Goodwill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complaint Resolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>For Retention Offer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goodwill Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goodwill Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newspaper Redelivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provisioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reclassification Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reclassification Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Reclassification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to CSO Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to CSO to Initiate Courier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Mailing Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Ops Rep/Cir-Planner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Technical CSO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Vendor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subscription Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subscription Stop Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temp Stop Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temp Stop Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urgent Start Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urgent Start Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urgent Stop Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urgent Stop Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Goodwill Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Reclassification Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Urgent Start Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Urgent Stop Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order_Line_Item_Vendor__c.object
<CustomObject>
    <description>The Order Line Item Object will represent the item selected during Order Entry. 
The record looks up to Order record.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Order Line Items (Vendor)</relationshipLabel>
        <relationshipName>Order_Line_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription (Vendor)</label>
        <referenceTo>Subscription_Vendor__c</referenceTo>
        <relationshipLabel>Publications</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Line Item (Vendor)</label>
    <nameField>
        <displayFormat>OLIV{0000000000}</displayFormat>
        <label>Order Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items (Vendor)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subscription_Vendor__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Subscription (Vendor)</label>
    <nameField>
        <displayFormat>SV-{0000000000}</displayFormat>
        <label>Subscription (Vendor) Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions (Vendor)</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/VendorStopSubscriptionButton.cls
global class VendorStopSubscriptionButton{
    
    webservice static String stopVendorSub(String subStopCaseId){
        String result;
        Case caseRec = new Case();
        Set<id> subVendorSet = new Set<id>();       
        List<Order_Line_Item_Vendor__c> oLIVendor = new List<Order_Line_Item_Vendor__c>();
        List<Subscription_Vendor__c> subVenList = new List<Subscription_Vendor__c>();
        List<Subscription_Vendor__c> newSubVenList = new List<Subscription_Vendor__c>();
        
        try{        
            caseRec = [SELECT id, Status, Sub_Status__c, account.recordType.name FROM Case WHERE id =: subStopCaseId];          
            if(String.valueOf(caseRec.account.recordType.name) == GlobalVariableClass.VENDORSUB){
                caseRec.Status = GlobalVariableClass.STATUS_CLOSED;
                caseRec.Sub_Status__c = GlobalVariableClass.SUB_STATUS_STOP_COMPLETED;
                
                oLIVendor = [SELECT id, name, Subscription_Vendor__c FROM Order_Line_Item_Vendor__c WHERE Case__c =: subStopCaseId];
                
                for(Order_Line_Item_Vendor__c oliv : oLIVendor){
                    subVendorSet.add(oliv.Subscription_Vendor__c);
                }
                
                subVenList = [SELECT id, name, status__c FROM Subscription_Vendor__c WHERE id IN: subVendorSet];
                
                for(Subscription_Vendor__c subVen : subVenList){
                    subVen.status__c = GlobalVariableClass.STATUS_CANCELLED;
                    newSubVenList.add(subVen);
                }
                
                update newSubVenList;
                update caseRec;
                result = 'Success';
            } else {
                result = 'Account should be Vendor Stop Subscription.';  // Start/End UD-3816 VPernicia 1/29/16
            }
        } catch(Exception e){
            result = 'Error in cancelling subscription.';
            system.debug('ERROR : ' + e.getStackTraceString());
        }
        
        return result;
    }
}