src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Billing_Type__c</fullName>
        <description>For populating New Billing Account in Zuora via SendToZBilling. Add to Field Set zqu__CustomAccountFields</description>
        <label>Billing Type (System Use)</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Recipient_Contact__c</fullName>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Recipient Contact</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recipient_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recipient Indicator</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Delivery_Charge__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Mapping of Subscriber Charge and Vendor Credit based on Delivery Charge Type.

Please note that the Name is a combination of Address Type and Delivery Charge Type in that order.</description>
    <label>Delivery Charge</label>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_Account_Creation_Mode__c</fullName>
        <label>Billing Account Creation Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Create New Billing Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Use existing Billing Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Billing Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (3 OR 4) AND (2 OR 4 OR 5)</booleanFilter>
            <errorMessage>Please select a Billing Account with correct Billing Type</errorMessage>
            <filterItems>
                <field>Zuora__CustomerAccount__c.Zuora__Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.Billing_Type__c</field>
                <operation>equals</operation>
                <valueField>Zuora__CustomerAccount__c.Billing_Type__c</valueField>
            </filterItems>
            <filterItems>
                <field>Zuora__CustomerAccount__c.Billing_Type__c</field>
                <operation>equals</operation>
                <valueField>$Source.Billing_Type__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.isOrderLegacy__c</field>
                <operation>notEqual</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>Zuora__CustomerAccount__c.Legacy_Billing_Account_Id__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_Type__c</fullName>
        <label>Billing Type</label>
        <picklist>
            <picklistValues>
                <fullName>Full Prepaid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recurring Prepaid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recurring Postpaid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Credit_Balance__c</fullName>
        <label>Credit Balance</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Delivery_Charge__c</fullName>
        <label>Delivery Charge</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Order_Legacy_Id__c</fullName>
        <externalId>true</externalId>
        <label>Order Legacy Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Recipient_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recipient Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.Recipient_Indicator__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Recipient Contact)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isChangeOfSubEntry__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used as lookup filter for Subscription field</description>
        <label>isChangeOfSubEntry?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isWaive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isWaive?</label>
        <type>Checkbox</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src orig/classes/MigrationOrderTriggerHandlerTest.cls
@IsTest (seeAllData = True)
private class MigrationOrderTriggerHandlerTest {

            static Account testAccount;
            static Order__c testOrder;  
            static Contact testContact;
            static Zuora__CustomerAccount__c testBillingAccount;  
            
    static testmethod void testOrder()
    {
            testAccount = TestDataFactory.createAccount(1, 'Direct Corporate')[0];
            Database.insert (testAccount);
            
            testContact = TestDataFactory.createContact(1)[0];
            testContact.AccountId = testAccount.Id;
            testContact.Recipient_Indicator__c = true;
            Database.insert (testContact);
            
            testOrder = TestDataFactory.createOrder(1)[0];
            testOrder.Account__c = testAccount.Id; 
            testOrder.Order_Legacy_Id__c = 'IDNGNEIRGA';
            testOrder.Recipient_Contact__c = testContact.Id;
            testOrder.Credit_Balance__c = 100.00;
            testOrder.Delivery_Charge__c = 100.00;
            testOrder.Billing_Account_Creation_Mode__c = 'Use created Billing Account';
            testOrder.isChangeOfSubEntry__c = False;
            testOrder.isWaive__c = False;
            Database.insert (testOrder);
            
            testOrder = [SELECT Id, Order_Legacy_Id__c FROM Order__c WHERE Id = :testOrder.Id];
            
            Test.startTest();
            MigrationOrderTriggerHandler moth = new MigrationOrderTriggerHandler();
            moth.doBeforeInsert(new List<Order__c> { testOrder });
            
            Test.stopTest();
            
            System.assertEquals(testOrder.Order_Legacy_Id__c, 'IDNGNEIRGA');
    }
    
    static testmethod void testOrder2()
    {
            testAccount = TestDataFactory.createAccount(1, 'Direct Corporate')[0];
            Database.insert (testAccount);
            
            testContact = TestDataFactory.createContact(1)[0];
            testContact.AccountId = testAccount.Id;
            testContact.Recipient_Indicator__c = true;
            Database.insert (testContact);

            testBillingAccount = TestDataFactory.createBillingAccount(1)[0];
            testBillingAccount.Zuora__Account__c = testAccount.Id;
            testBillingAccount.Billing_Type__c = 'Full Prepaid';
            Database.insert (testBillingAccount);
            
            testOrder = TestDataFactory.createOrder(1)[0];
            testOrder.Billing_Account__c = testBillingAccount.Id;
            testOrder.Account__c = testAccount.Id; 
            testOrder.Order_Legacy_Id__c = 'IDNGNEIRGA';
            testOrder.Recipient_Contact__c = testContact.Id;
            testOrder.Credit_Balance__c = 100.00;
            testOrder.Delivery_Charge__c = 100.00;
            testOrder.Billing_Account_Creation_Mode__c = 'Use created Billing Account';
            testOrder.isChangeOfSubEntry__c = False;
            testOrder.isWaive__c = False;
            testOrder.Billing_Type__c = 'Full Prepaid';
            Database.insert (testOrder);

            testOrder = [SELECT Id, Order_Legacy_Id__c, Account__c FROM Order__c WHERE Id = :testOrder.Id];
            
            Map<Id, Order__c> orderMap = new Map<Id, Order__c>();
            orderMap.put(testOrder.id, testOrder);
            
            Map<Id, Order__c> orderMap2 = new Map<Id, Order__c>();
            orderMap2.put(testOrder.id, testOrder);
            
            Test.startTest();
            MigrationOrderTriggerHandler moth = new MigrationOrderTriggerHandler();
            moth.doBeforeUpdate(new List<Order__c> { testOrder }, orderMap , new List<Order__c> { testOrder }, orderMap2);
            Test.stopTest();
            
            System.assertEquals(testOrder.Order_Legacy_Id__c, 'IDNGNEIRGA');
    }
}