src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Airline_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Airline Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Recipient_Number__c</fullName>
        <displayFormat>{00000000}</displayFormat>
        <label>Recipient Number</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>City Code</label>
        <referenceTo>City__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_Name__c</fullName>
        <formula>Country__r.Country_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flight_Number_1__c</fullName>
        <formula>City__r.Flight_Number_1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Flight Number 1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Number_2__c</fullName>
        <formula>City__r.Flight_Number_2__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Flight Number 2</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Packing_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Packing Code</label>
        <referenceTo>Packing_Grp__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Packing_Group_Description__c</fullName>
        <formula>Packing_Code__r.Packing_Group_Description__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Packing Group Description</label>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <recordTypes>
        <fullName>Airline</fullName>
        <active>true</active>
        <description>For Airline Subscriber</description>
        <label>Airline</label>
    </recordTypes>
    <recordTypes>
        <fullName>Internal</fullName>
        <active>true</active>
        <description>For Internal Subscribers</description>
        <label>Internal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Local</fullName>
        <active>true</active>
        <description>For Local Subscribers</description>
        <label>Local</label>
    </recordTypes>
    <recordTypes>
        <fullName>Overseas</fullName>
        <active>true</active>
        <description>For Overseas Subscribers</description>
        <label>Overseas</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/City__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Cities</relationshipLabel>
        <relationshipName>Cities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flight_Number_1__c</fullName>
        <description>Formula Display on Airlines Address</description>
        <label>Flight Number (1)</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Number_2__c</fullName>
        <label>Flight Number (2)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>City</label>
    <nameField>
        <label>City Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recipient_Contact__c</fullName>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Recipient Contact</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recipient_Number__c</fullName>
        <description>Recipient Number will be auto set by the system.</description>
        <label>Recipient Number</label>
        <precision>17</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <externalId>true</externalId>
        <label>Code</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Country_Name__c</fullName>
        <label>Country Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Package__c.object
<CustomObject>
    <fields>
        <fullName>Subscription_Type__c</fullName>
        <label>Subscription Type</label>
        <picklist>
            <picklistValues>
                <fullName>Termed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evergreen</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Package_Item__c.object
<CustomObject>
    <fields>
        <fullName>Package__c</fullName>
        <description>The package name for which the package item is being created will be displayed.</description>
        <label>Package</label>
        <referenceTo>Package__c</referenceTo>
        <relationshipLabel>Package Items</relationshipLabel>
        <relationshipName>Package_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Rate Plan</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>zqu__ProductRatePlan__c.zqu__Deleted__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>Package Items</relationshipLabel>
        <relationshipName>Package_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Package Item</label>
    <nameField>
        <label>Package Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Package Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Packing_Grp__c.object
<CustomObject>
    <fields>
        <fullName>Packing_Code__c</fullName>
        <label>Packing Code</label>
        <picklist>
            <picklistValues>
                <fullName>MFA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MOD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MOD1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MOD2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SATS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SILK</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Packing_Group_Description__c</fullName>
        <label>Packing Group Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Packing Grp</label>
    <nameField>
        <label>Packing Grp Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packing Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Packing_Label_Batch__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Number_1__c</fullName>
        <label>Flight Number 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Number_2__c</fullName>
        <label>Flight Number 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Issue_Date__c</fullName>
        <label>Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mailing_Agent_Account_Number__c</fullName>
        <label>Mailing Agent Account Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication_Code__c</fullName>
        <label>Publication Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient_Number__c</fullName>
        <label>Recipient Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient_Type__c</fullName>
        <label>Recipient Type</label>
        <picklist>
            <picklistValues>
                <fullName>Overseas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Airline</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subscriber_Account_Number__c</fullName>
        <label>Subscriber Account Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Type__c</fullName>
        <label>Subscription Type</label>
        <picklist>
            <picklistValues>
                <fullName>Newspaper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Magazine</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Packing Label Batches</relationshipLabel>
        <relationshipName>Packing_Label_Batches1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Packing Label Batch</label>
    <nameField>
        <displayFormat>PLB{0000000}</displayFormat>
        <label>Packing Label Batch 2 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing Label Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Publication__c.object
<CustomObject>
    <fields>
        <fullName>Platform_Type__c</fullName>
        <label>Platform Type</label>
        <picklist>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tablet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Smartphone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All in One (AIO)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Publication_Code__c</fullName>
        <externalId>true</externalId>
        <label>Publication Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <label>Publication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/PackingLabelsControllerTest.cls
@isTest(seeAllData=true)
private class PackingLabelsControllerTest{
    static testMethod void testPackingLabelsControllerOverseas(){
        Integer counter;
    
        //start test data
        Account acc = TestDataFactory.createAccount(1, 'Direct Corporate')[0];
        acc.AccountNumber = 'unique123456';
        insert acc;
        
        Address__c add = TestDataFactory.createAddress(1)[0];
        add.RecordTypeId = ConstantsSLB.getKeyId('Address_Overseas');
        insert add;
        
        Contact con = TestDataFactory.createContact(1)[0];
        con.Address__c = add.Id;
        con.Recipient_Number__c = 123456;
        insert con;
        
        Zuora__CustomerAccount__c billAcc = TestDataFactory.createBillingAccount(1)[0];
        billAcc.Zuora__Account__c = acc.Id;
        insert billAcc;
        
        counter=0;
        List<Zuora__Subscription__c> subRecs = TestDataFactory.createSubscription(6);
        for(Zuora__Subscription__c sub:subRecs){
            sub.Zuora__CustomerAccount__c = billAcc.Id;
            sub.subscription_type__c = 'Publication';
            sub.Recipient_Contact__c = con.Id;
            sub.Zuora__SubscriptionEndDate__c = date.today();
            sub.Qty1__c = '3';
            sub.Frequency__c = GlobalVariableClass.FREQUENCY_MONFRI;
            if(counter==1){
                sub.Frequency__c = GlobalVariableClass.FREQUENCY_FRISUN;
            }
            else if(counter==2){
                sub.Frequency__c = GlobalVariableClass.FREQUENCY_SATSUN;
            }
            else if(counter==3){
                sub.Frequency__c = 'Mon-Sat';
            }
            else if(counter==4){
                sub.Frequency__c = GlobalVariableClass.FREQUENCY_DEFAULT;
            }
            counter++;
        }
        insert subRecs;
        
        counter=0;
        List<Zuora__SubscriptionProductCharge__c> spc = TestDataFactory.createSubscriptionProductCharge(6);
        for(Zuora__SubscriptionProductCharge__c sp:spc){
            sp.Zuora__Subscription__c = subRecs[counter].Id;
            sp.Zuora__UOM__c = 'UOM001';
            sp.PublicationCode__c = 'BH';
            if(counter==0){
                sp.PublicationCode__c = 'ZB';  
            }
            else if(counter==1){
                sp.PublicationCode__c = 'TM';   
            }
            else if(counter==2){
                sp.PublicationCode__c = 'BT';   
            }
            else if(counter==3){
                sp.PublicationCode__c = 'ST';   
            }
            else if(counter==4){
                sp.PublicationCode__c = 'NP';   
            }
            else if(counter==5){
                sp.Zuora__Subscription__c = subRecs[0].Id; 
                sp.PublicationCode__c = 'WB';   
            }
            counter++;
        }
        insert spc;
        
        Publication__c pub = TestDataFactory.createPublication(1)[0];
        pub.Publication_Code__c = 'BH';
        pub.Platform_Type__c = 'Print';
        insert pub;
        
        Account accQ = [SELECT AccountNumber FROM Account WHERE Id=:acc.Id];
        
        List<Packing_Label_Batch__c> plb = new List<Packing_Label_Batch__c>();
        for(counter=0;counter<6;counter++){
            Packing_Label_Batch__c p = new Packing_Label_Batch__c();
            p.Subscription__c = subRecs[counter].Id; 
            p.Subscriber_Account_Number__c = accQ.AccountNumber;
            plb.add(p);  
        }
        insert plb;
        
        Set<String> subIdSet = new Set<String>();
        for(Zuora__Subscription__c sub:subRecs){
            subIdSet.add(sub.Id);
        }
        //end test data
    
        test.startTest();
            PageReference pageRef = Page.AirlineSubscriptions;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('issueDate', string.valueOf(system.now()));
            ApexPages.currentPage().getParameters().put('id', plb[0].Id);
        
            PackingLabelsController cont = new PackingLabelsController();
            cont.overseasReportHardCopy(subIdSet);
            cont.initializeOSW();
            cont.initializeAirline();
        test.stopTest();
    }
    
    static testMethod void testPackingLabelsControllerAirline(){
        Integer counter;
    
        //start test data
        Account acc = TestDataFactory.createAccount(1, 'Direct Corporate')[0];
        acc.AccountNumber = 'unique123456';
        acc.Airline_Indicator__c = true;
        insert acc;
        
        Packing_Grp__c pGRP = new Packing_Grp__c();
        pGRP.Packing_Code__c = '001';
        pGRP.Packing_Group_Description__c = 'Description';
        insert pGRP;
        
        Country__c country = TestDataFactory.createCountry(1)[0];
        country.Code__c = '6000';
        country.Country_Name__c = 'Country';
        insert country;
        
        Country__c cq = [SELECT Country_Name__c FROM Country__c Where id=:country.Id];
        system.assertNotEquals(cq.Country_Name__c, null);
        
        City__c city = TestDataFactory.createCity(1)[0];
        city.Flight_Number_1__c = 'F123';
        city.Flight_Number_2__c = 'F456';
        city.Name = 'City';
        city.Country__c = country.Id;
        insert city;
        
        Address__c add = TestDataFactory.createAddress(1)[0];
        add.RecordTypeId = ConstantsSLB.getKeyId('Address_Airline');
        add.Packing_Code__c = pGRP.ID;
        add.Country__c = country.Id;
        add.City__c = city.Id;
        insert add;
        
        Contact con = TestDataFactory.createContact(1)[0];
        con.Address__c = add.Id;
        con.Recipient_Number__c = 123456;
        insert con;
        
        Zuora__CustomerAccount__c billAcc = TestDataFactory.createBillingAccount(1)[0];
        billAcc.Zuora__Account__c = acc.Id;
        insert billAcc;
        
        Package__c pack = TestDataFactory.createPackage(1)[0];
        database.insert(pack);
        
        zqu__ZProduct__c zProduct = TestDataFactory.createZProduct(1)[0];
        database.insert(zProduct);
         
        zqu__ProductRatePlan__c prdRatePlan = TestDataFactory.createProductRatePlan(1)[0];
        prdRatePlan.zqu__ZProduct__c = zProduct.Id;
        prdRatePlan.RatePlanType__c= 'Bill Plan';
        database.insert(prdRatePlan);
         
        Package_Item__c pItem = TestDataFactory.createPackageItem(1,'Base Product')[0];
        pItem.Package__c = pack.id;
        pItem.Product_Rate_Plan__c = prdRatePlan.Id;
        database.insert(pItem);
        
        counter=0;
        List<Zuora__Subscription__c> subRecs = TestDataFactory.createSubscription(6);
        for(Zuora__Subscription__c sub:subRecs){
            sub.Zuora__CustomerAccount__c = billAcc.Id;
            sub.subscription_type__c = 'Publication';
            sub.Recipient_Contact__c = con.Id;
            sub.Zuora__SubscriptionEndDate__c = date.today();
            sub.Qty1__c = '3';
            sub.Zuora__Account__c = acc.Id;
            sub.Main_Package__c = pack.Id;
            sub.Frequency__c = GlobalVariableClass.FREQUENCY_MONFRI;
            if(counter==1){
                sub.Frequency__c = GlobalVariableClass.FREQUENCY_FRISUN;
            }
            else if(counter==2){
                sub.Frequency__c = GlobalVariableClass.FREQUENCY_SATSUN;
            }
            else if(counter==3){
                sub.Frequency__c = 'Mon-Sat';
            }
            else if(counter==4){
                sub.Frequency__c = GlobalVariableClass.FREQUENCY_DEFAULT;
            }
            counter++;
        }
        insert subRecs;
        
        counter=0;
        List<Zuora__SubscriptionProductCharge__c> spc = TestDataFactory.createSubscriptionProductCharge(6);
        for(Zuora__SubscriptionProductCharge__c sp:spc){
            sp.Zuora__Subscription__c = subRecs[counter].Id;
            sp.Zuora__UOM__c = 'UOM001';
            sp.PublicationCode__c = 'BH';
            if(counter==0){
                sp.PublicationCode__c = 'ZB';  
            }
            else if(counter==1){
                sp.PublicationCode__c = 'TM';   
            }
            else if(counter==2){
                sp.PublicationCode__c = 'BT';   
            }
            else if(counter==3){
                sp.PublicationCode__c = 'ST';   
            }
            else if(counter==4){
                sp.PublicationCode__c = 'NP';   
            }
            else if(counter==5){
                sp.Zuora__Subscription__c = subRecs[0].Id; 
                sp.PublicationCode__c = 'WB';   
            }
            counter++;
        }
        insert spc;
        
        Publication__c pub = TestDataFactory.createPublication(1)[0];
        pub.Publication_Code__c = 'BH';
        pub.Platform_Type__c = 'Print';
        insert pub;
        
        Account accQ = [SELECT AccountNumber FROM Account WHERE Id=:acc.Id];
        
        List<Packing_Label_Batch__c> plb = new List<Packing_Label_Batch__c>();
        for(counter=0;counter<6;counter++){
            Packing_Label_Batch__c p = new Packing_Label_Batch__c();
            p.Subscription__c = subRecs[counter].Id; 
            p.Subscriber_Account_Number__c = accQ.AccountNumber;
            p.Recipient_Type__c = 'Airline';
            p.Mailing_Agent_Account_Number__c = accQ.AccountNumber;
            p.Issue_Date__c = date.today();
            plb.add(p);  
        }
        insert plb;
        
        Set<String> subIdSet = new Set<String>();
        for(Zuora__Subscription__c sub:subRecs){
            subIdSet.add(sub.Id);
        }
        //end test data
    
        test.startTest();
            PageReference pageRef = Page.AirlineSubscriptions;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('issueDate', string.valueOf(system.now()));
            ApexPages.currentPage().getParameters().put('id', plb[0].Id);
        
            PackingLabelsController cont = new PackingLabelsController();
            cont.overseasReportHardCopy(subIdSet);
            cont.initializeOSW();
            cont.airlineReportHardCopy();
            cont.initializeAirline();
            cont.initializeMagazineWrap();
            cont.querySub('local', '');
            cont.querySub('internal', '');
            cont.querySub('airline', '');
            cont.querySub('overseas', '');
            cont.pubCode = '';
            cont.address1 = '';
            cont.address2 = '';
            cont.address3 = '';
            cont.address4 = '';
            cont.address5 = '';
            
            ApexPages.currentPage().getParameters().put('id', acc.Id);
            PackingLabelsController cont2 = new PackingLabelsController();
            cont2.airlineReportHardCopy();
        test.stopTest();
    }
}