src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Building_Name__c</fullName>
        <label>Building Name</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level_Number__c</fullName>
        <label>Level Number</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Singpost_Address__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Postal Code</label>
        <referenceTo>Singpost_Address__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is auto-populated via trigger. See Section 1.2.8.4. Apex Trigger).</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Activation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <label>Unit Number</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Block_House_Number__c</fullName>
        <description>This field will be displayed if record type field is Local.
Read-only. Auto-populated by the system based on Postal Code</description>
        <label>House/Block Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Building_Name__c</fullName>
        <description>This field will be displayed if record type field is Local. 
Read-only. Auto-populated by the system based on Postal Code</description>
        <formula>Postal_Code__r.Building_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Building Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Name__c</fullName>
        <formula>Country__r.Country_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level_Number__c</fullName>
        <description>This field will be displayed if record type field is Local.
User specified</description>
        <label>Level Number</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be displayed if record type field is Local.
User specified</description>
        <label>Postal Code</label>
        <referenceTo>Singpost_Address__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <description>This field will be displayed if record type field is Local.
User specified</description>
        <label>Unit Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/BATCH_JOB_SCHEDULER__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>STARTED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ABORTED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUCCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAILED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BATCH_JOB_SCHEDULER</label>
    <nameField>
        <displayFormat>SBRR-{0000000000}</displayFormat>
        <label>SP Batch Run Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BATCH_JOB_SCHEDULER</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BatchInterface_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Batch Interface Settings</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recipient_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recipient Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <formula>Address__r.Unit_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unit Number</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Country_Name__c</fullName>
        <label>Country Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/External_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>External Payments</relationshipLabel>
        <relationshipName>External_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>External Payments</relationshipLabel>
        <relationshipName>External_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_PDF_Generated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is PDF Generated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Credit Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PayPal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transaction_Amount__c</fullName>
        <label>Transaction Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>K</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>External Payment</label>
    <nameField>
        <label>External Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Key_Id__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To contain the list of Id&apos;s.</description>
    <fields>
        <fullName>Id__c</fullName>
        <label>Id</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Key Id</label>
</CustomObject>

src/objects/Letter_Print_Request__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Letter Print Requests</relationshipLabel>
        <relationshipName>Letter_Print_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Successful</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Letter Print Request</label>
    <nameField>
        <label>Letter Print Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Letter Print Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Other__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Other</label>
</CustomObject>

src/objects/Singpost_Address__c.object
<CustomObject>
    <fields>
        <fullName>Building_Name__c</fullName>
        <description>User Specified</description>
        <label>Building Name</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <label>Singpost Address</label>
    <nameField>
        <label>Postal Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Singpost Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SP_PaypalFailureRequestBatchTest.cls
/* April Veloso
   10/16/2015
   Test class for SP_PaypalFailureRequestBatch
*/


@isTest(seeAllData = false)
public class SP_PaypalFailureRequestBatchTest{
        static testmethod void testSP_PaypalFailureRequestBatchtest(){

                    /*Key_Id__c key = new Key_Id__c();
                    key.Name = 'NEXT_RECIPIENT_NUMBER';
                    key.Id__c = '30012551';
                    database.insert(key);*/
                    
                    Other__c other = new Other__c();
                    other.Name = 'SP18_InitializedBatch';
                    other.Value__c = '0';
                    database.insert(other);
                    
                    
                    //String letterType = 'April';
                    Integer batchCount = 200;
                    String sessionId = 'SE123';
                    String strBatch = ConstantsSLB.getOther('SP18_InitializedBatch');
                    
                    Account acc = TestDataFactory.createAccount(1, 'Direct Corporate')[0];
                    insert acc;
                    
                    Singpost_Address__c postal = TestDataFactory.createSingpostAddress(1)[0];
                    postal.Building_Name__c = 'Ebloc2';
                    insert postal;
                    
                    Country__c country = TestDataFactory.createCountry(1)[0]; 
                    country.Country_Name__c = 'SINGAPORE'; 
                    insert country;
                    
                    Address__c address = TestDataFactory.createAddress(1)[0];
                    address.Block_House_Number__c =  'TEST';
                    address.Postal_Code__c = postal.id;
                    address.Level_Number__c = '17';
                    address.Unit_Number__c = 'Unit 5';
                    address.Country__c = country.id;
                    insert address;
                    
                    Contact con = TestDataFactory.createContact(1)[0];
                    con.AccountId = acc.Id;
                    con.Address__c = address.id;
                    con.Recipient_Indicator__c = true;
                    insert con;
                    
                    Zuora__CustomerAccount__c billAcc = TestDataFactory.createBillingAccount(1)[0];
                    billAcc.Zuora__Account__c = acc.Id;
                    insert billAcc;
                    
                    Zuora__PaymentMethod__c paymentMethod = TestdataFactory.createPaymentMethod(1)[0];
                    paymentMethod.Zuora__Type__c = 'Paypal';
                    paymentMethod.Zuora__BillingAccount__c = billAcc.Id;
                    database.insert(paymentMethod);
                    
                    
                    List<Zuora__CustomerAccount__c> billAccountList = TestDataFactory.createBillingAccount(1);
                    billAccountList[0].name = 'April Summer';
                    //billAccountList [0].id = zInv.id;
                    billAccountList[0].Zuora__Account__c = acc.id; 
                    billAccountList[0].Billing_Contact__c = con.id;
                    billAccountList[0].Zuora__Default_Payment_Method__c = paymentMethod.id;
                    insert billAccountList;
                    
                    Zuora__Payment__c paymentRecord = new Zuora__Payment__c();
                    paymentRecord.Zuora__BillingAccount__c = billAccountList[0].id;
                    paymentRecord.Name='TestPayment';
                    paymentRecord.Zuora__Amount__c=100.00;
                    paymentRecord.Zuora__PaymentMethod__c='Payment Method';
                    paymentRecord.Zuora__EffectiveDate__c=date.today();
                    paymentRecord.Zuora__Type__c = 'Electronic';
                    paymentRecord.Zuora__Status__c = 'Error';
                    paymentRecord.Is_PDF_Generated__c = false;
                    database.insert(paymentRecord);
                    
                    External_Payment__c externalPayment = TestDataFactory.createExternalPayment(1)[0];
                    externalPayment.Name = 'External';
                    externalPayment.Transaction_Amount__c = 15.00;
                    externalPayment.Transaction_Date__c = date.today();
                    externalPayment.Account_Name__c = acc.id;
                    externalPayment.Transaction_Type__c = 'F';
                    externalPayment.Billing_Account__c = billAccountList[0].id ;
                    externalPayment.Payment_Type__c = 'Paypal';
                    database.insert(externalPayment);    
                    
                    //List<Zuora__Payment__c> scope = [SELECT Zuora__BillingAccount__c,Zuora__Type__c,Zuora__Status__c,Is_PDF_Generated__c FROM Zuora__Payment__c];
                    BatchInterface_Settings__c batchSettings = new BatchInterface_Settings__c();
                    batchSettings.Name = 'Endpoint Delegator';
                    batchSettings.value__c = 'Endpoint Delegator';
                    database.insert(batchSettings);
                    
                    BATCH_JOB_SCHEDULER__c batchJob = new BATCH_JOB_SCHEDULER__c();
                    batchJob.Batch_Code__c = 'SP045';
                    batchJob.Status__c = 'SUCCESS';
                    batchJob.Batch_Run_Date__c = date.today();
                    database.insert(batchJob);
                    Test.setCreatedDate(batchJob.Id, date.today() - 1);
                    
                    Letter_Print_Request__c letterPrint = new Letter_Print_Request__c ();
                    letterPrint.Letter_Type__c = SP_GenerateLetterPrintBatch.FAILED_PAYPAL_NOTIFICATION;
                    letterPrint.Status__c = SP_GenerateLetterPrintBatch.newValue;
                    letterPrint.Batch_Run_Sequence__c = 3;
                    database.insert(letterPrint);
                    
                    List<External_Payment__c> scope = [SELECT Id, Name, Transaction_Amount__c,Transaction_Date__c,Account_Name__c,
                    Transaction_Type__c,Billing_Account__c, Payment_Type__c from External_Payment__c where id =: externalPayment.id];
                    
                    Set<Id> paymentIds = new Set<Id>();
                    paymentIds.add(paymentRecord.Id);
                    
                    Test.startTest();
                    Database.BatchableContext BC;
                    
                    SP_PaypalFailureRequestBatch batch = new SP_PaypalFailureRequestBatch('letter_type',batchCount,sessionId);
                    ID batchprocessid = Database.executeBatch(batch,200);
                    System.assertNotEquals(null, batchprocessid);
                    batch.execute(BC,scope);
                    SP_PaypalFailureRequestBatch batch2 = new SP_PaypalFailureRequestBatch('letter_type',batchCount,sessionId, paymentIds);
                    ID batchprocessid2 = Database.executeBatch(batch2,200);
                    System.assertNotEquals(null, batchprocessid2);
                    batch2.execute(BC,scope);
                    Test.stopTest();
                    
        }
        static testmethod void testbatchJobSchedulerListsizeisZero(){

                    /*Key_Id__c key = new Key_Id__c();
                    key.Name = 'NEXT_RECIPIENT_NUMBER';
                    key.Id__c = '30012551';
                    database.insert(key);*/
                    
                    Other__c other = new Other__c();
                    other.Name = 'SP18_InitializedBatch';
                    other.Value__c = '0';
                    database.insert(other);
                    
                    Integer batchCount = 200;
                    String sessionId = 'SE123';
                    String strBatch = ConstantsSLB.getOther('SP18_InitializedBatch');
                    
                    Account acc = TestDataFactory.createAccount(1, 'Direct Corporate')[0];
                    insert acc;
                    
                    Singpost_Address__c postal = TestDataFactory.createSingpostAddress(1)[0];
                    postal.Building_Name__c = 'Ebloc2';
                    insert postal;
                    
                    Country__c country = TestDataFactory.createCountry(1)[0]; 
                    country.Country_Name__c = 'SINGAPORE'; 
                    insert country;
                    
                    Address__c address = TestDataFactory.createAddress(1)[0];
                    address.Block_House_Number__c =  'TEST';
                    address.Postal_Code__c = postal.id;
                    address.Level_Number__c = '17';
                    address.Unit_Number__c = 'Unit 5';
                    address.Country__c = country.id;
                    insert address;
                    
                    Contact con = TestDataFactory.createContact(1)[0];
                    con.AccountId = acc.Id;
                    con.Address__c = address.id;
                    con.Recipient_Indicator__c = true;
                    insert con;
                    
                    Zuora__CustomerAccount__c billAcc = TestDataFactory.createBillingAccount(1)[0];
                    billAcc.Zuora__Account__c = acc.Id;
                    insert billAcc;
                    
                    Zuora__PaymentMethod__c paymentMethod = TestdataFactory.createPaymentMethod(1)[0];
                    paymentMethod.Zuora__Type__c = 'Paypal';
                    paymentMethod.Zuora__BillingAccount__c = billAcc.Id;
                    database.insert(paymentMethod);
                    
                    
                    List<Zuora__CustomerAccount__c> billAccountList = TestDataFactory.createBillingAccount(1);
                    billAccountList[0].name = 'April Summer';
                    billAccountList[0].Zuora__Account__c = acc.id; 
                    billAccountList[0].Billing_Contact__c = con.id;
                    billAccountList[0].Zuora__Default_Payment_Method__c = paymentMethod.id;
                    insert billAccountList;
                    
                    Zuora__Payment__c paymentRecord = new Zuora__Payment__c();
                    paymentRecord.Zuora__BillingAccount__c = billAccountList[0].id;
                    paymentRecord.Name='TestPayment';
                    paymentRecord.Zuora__Amount__c=100.00;
                    paymentRecord.Zuora__PaymentMethod__c='Payment Method';
                    paymentRecord.Zuora__EffectiveDate__c=date.today();
                    paymentRecord.Zuora__Type__c = 'Electronic';
                    paymentRecord.Zuora__Status__c = 'Error';
                    paymentRecord.Is_PDF_Generated__c = false;
                    database.insert(paymentRecord);
                    
                    External_Payment__c externalPayment = TestDataFactory.createExternalPayment(1)[0];
                    externalPayment.Name = 'External';
                    externalPayment.Transaction_Amount__c = 15.00;
                    externalPayment.Transaction_Date__c = date.today();
                    externalPayment.Account_Name__c = acc.id;
                    externalPayment.Transaction_Type__c = 'F';
                    externalPayment.Billing_Account__c = billAccountList[0].id ;
                    externalPayment.Payment_Type__c = 'Paypal';
                    database.insert(externalPayment);    
                    
                    //List<Zuora__Payment__c> scope = [SELECT Zuora__BillingAccount__c,Zuora__Type__c,Zuora__Status__c,Is_PDF_Generated__c FROM Zuora__Payment__c];
                    BatchInterface_Settings__c batchSettings = new BatchInterface_Settings__c();
                    batchSettings.Name = 'Endpoint Delegator';
                    batchSettings.value__c = 'Endpoint Delegator';
                    database.insert(batchSettings);
                                        
                    Letter_Print_Request__c letterPrint = new Letter_Print_Request__c ();
                    letterPrint.Letter_Type__c = SP_GenerateLetterPrintBatch.FAILED_PAYPAL_NOTIFICATION;
                    letterPrint.Status__c = SP_GenerateLetterPrintBatch.newValue;
                    letterPrint.Batch_Run_Sequence__c = 3;
                    database.insert(letterPrint);
                    
                    List<External_Payment__c> scope = [SELECT Id, Name, Transaction_Amount__c,Transaction_Date__c,Account_Name__c,
                    Transaction_Type__c,Billing_Account__c, Payment_Type__c from External_Payment__c where id =: externalPayment.id];
                    
                    Set<Id> paymentIds = new Set<Id>();
                    paymentIds.add(paymentRecord.Id);
                    
                    Test.startTest();
                    Database.BatchableContext BC;
                    SP_PaypalFailureRequestBatch batch = new SP_PaypalFailureRequestBatch('letter_type',batchCount,sessionId);
                    ID batchprocessid = Database.executeBatch(batch,200);
                    System.assertNotEquals(null, batchprocessid);
                    batch.execute(BC,scope);
                    SP_PaypalFailureRequestBatch batch2 = new SP_PaypalFailureRequestBatch('letter_type',batchCount,sessionId, paymentIds);
                    ID batchprocessid2 = Database.executeBatch(batch2,200);
                    System.assertNotEquals(null, batchprocessid2);
                    batch2.execute(BC,scope);
                    Test.stopTest();
         }
                   
}