src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is auto-populated via trigger. See Section 1.2.8.4. Apex Trigger).</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Activation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Vendor Profile</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Order_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Cases (Order Number)</relationshipLabel>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Mode__c</fullName>
        <label>Payment Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cheque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CreditCard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eNets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paypal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Parties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Charge</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <label>Sub Status</label>
        <picklist>
            <controllingField>Category__c</controllingField>
            <picklistValues>
                <fullName>Assess for Goodwill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complaint Resolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>For Retention Offer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goodwill Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goodwill Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newspaper Redelivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provisioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reclassification Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reclassification Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Reclassification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to CSO Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to CSO to Initiate Courier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Mailing Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Ops Rep/Cir-Planner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Technical CSO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Vendor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subscription Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subscription Stop Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temp Stop Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temp Stop Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urgent Start Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urgent Start Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urgent Stop Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urgent Stop Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Goodwill Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Reclassification Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Urgent Start Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Urgent Stop Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Vendor Assignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Paid__c</fullName>
        <label>Amount Paid</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Check_Amount__c</fullName>
        <label>Check Amount</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Check_Dated__c</fullName>
        <label>Check Dated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Check_Issuing_Bank__c</fullName>
        <label>Check Issuing Bank</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Check_No__c</fullName>
        <label>Check No</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Mode__c</fullName>
        <label>Payment Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provisioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Vendor Assignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Void</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Order_Line_Item__c</fullName>
        <displayFormat>A-{000000}</displayFormat>
        <label>Order Line Item #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items_Direct</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vendor_Mailing_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor/Mailing Agent</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Mailing Agent</value>
            </filterItems>
            <infoMessage>Select Vendor or Mailing Agent Account.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items_Direct</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI{0000000000}</displayFormat>
        <label>Order Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SendQuotesToZuora.cls
global  class SendQuotesToZuora {

    public void SendQuotesToZuora(){}
    
    public void RecievedData(list<Id> lQuoteId, Id AccountId, Id BillingAccountId, boolean bNewBilling){
        SendQuoteToZBilling(lQuoteId, AccountId, BillingAccountId, bNewBilling);
    }
    

    @future (callout=true)
    static void SendQuoteToZBilling(list<Id> lQuoteId, Id AccountId, Id BillingAccountId, boolean bNewBilling){
        
        list<zqu.zQuoteUtil.ZBillingQuoteCollection> quotes = new List<zqu.zQuoteUtil.ZBillingQuoteCollection>();
        
        zqu.zQuoteUtil.ZBillingQuoteCollection quote = new zqu.zQuoteUtil.ZBillingQuoteCollection();
        quote.sfdcAccountId  = AccountId;   
        
        if (bNewBilling){ 
            quote.zAccountId     = 'new';       
        }else{
            quote.zAccountId     = BillingAccountId;
        }
        
        list<zqu.zQuoteUtil.ZBillingQuoteRequest> lQReq = new list<zqu.zQuoteUtil.ZBillingQuoteRequest>();
        for(Id i: lQuoteId){
            zqu.zQuoteUtil.ZBillingQuoteRequest req = new zqu.zQuoteUtil.ZBillingQuoteRequest();
            req.sfdcQuoteId = i;
            lQReq.add(req);
        }
        
        quote.quoteRequests = lQReq;
        quotes.add(quote);
        
        List<zqu.zQuoteUtil.zBillingResult> results = zqu.zQuoteUtil.sendToZBilling(quotes);
        
        list<string> lResult = new list<string>();
        set<string> zAccountId = new set<string>();
        for (zqu.zQuoteUtil.zBillingResult result : results ) {
            //Returns are: Status:zAccountId:zSubscriptionId
            
            System.debug('RESULTS > '+ result);
            System.debug('SEND RESULT > '+ result.success + ':'+ result.zAccountId + ':'+result.zSubscriptionId);           
            lResult.add(result.success + ':'+ result.zAccountId + ':'+result.zSubscriptionId);
            zAccountId.add(result.zAccountId);
            
        }   
        
        RealTimeOnDemandSync(zAccountId);
        assessCaseOrderStatus(lQuoteId);
        
    }
    
    @future (callout=true)
    static void RealTimeOnDemandSync(set<String> lZuoraAccountId ) {
        Set<String> zuoraAccountIdSet = new Set<String>();
        zuoraAccountIdSet = lZuoraAccountId;
        
        try
        {
          Zuora.OnDemandSyncManager syncManager = new Zuora.OnDemandSyncManager();
          syncManager.syncObjectType = Zuora.OnDemandSyncManager.ObjectType.BILLING_ACCOUNT;
          syncManager.syncZuoraObjectIdSet = zuoraAccountIdSet;	
          List<Zuora.SyncResult> syncResult = syncManager.sendRequest();
        }
        catch( Zuora.OnDemandSyncManager.OnDemandSyncException e )
        {
          // Process On-demand Sync exception.
        }

    }
    
	public static void assessCaseOrderStatus(List<Id> quoteIds) {
    	Set<Id> orderIds = new Set<Id>();
    	Map<Id, Boolean> orderIdToIsASsignedMap = new Map<Id, Boolean>();
    	List<Case> cases;
    	List<Order__c> ordersToUpdate = new List<Order__c>();
    	
    	for(zqu__Quote__c quote : [SELECT Order_Number__c FROM zqu__Quote__c WHERE Id IN :quoteIds]) {
    		if(quote.Order_Number__c != null) {
    			orderIds.add((Id) quote.Order_Number__c);
    		}
    	}
    	
    	for(Order__c orderRec : [SELECT Id, (SELECT Vendor_Mailing_Agent__c FROM Order_Line_Items_Direct__r) FROM Order__c WHERE Id IN :orderIds]) {
    		Boolean isAssigned = true;
    		for(Order_Line_Item__c oli : orderRec.Order_Line_Items_Direct__r) {
    			if(oli.Vendor_Mailing_Agent__c == null) {
    				isAssigned = false;
    			}
    		}
    		orderIdToIsASsignedMap.put(orderRec.Id, isAssigned);
    	}
    	
    	cases = [SELECT Id, Status, Order__c FROM Case WHERE Order__c IN :orderIds];
    	for(Case cas : cases) {
    		if(orderIdToIsASsignedMap.containsKey(cas.Order__c)) {
    			if(orderIdToIsASsignedMap.get(cas.Order__c)) {
	    			cas.Status = 'Closed';
	    			cas.Sub_Status__C = 'Subscription Created';
	    			ordersToUpdate.add(new Order__c(Id=cas.Order__c, Status__c = 'Close'));
    			}
    			else {
    				cas.Status = 'Pending';
    				cas.Sub_Status__c = 'Waiting for Vendor Assignment';
    				ordersToUpdate.add(new Order__c(Id=cas.Order__c, Status__c = 'Pending Vendor Assignment'));
    			}
    		}
    		
    	}
    	update cases;
    	update ordersToUpdate;
    }
    
    /*
     * Method to Generate Invoice after the Usage records has been loaded for Delivery Subscriptions
     *
    static void generateInvoice(ZouraCallout zcallout, String zBillingACctId) {
    	List<Zuora.zObject> invoiceList = new List<Zuora.zObject>();
		Zuora.zObject invoice = new Zuora.zObject('Invoice');
		invoice.setValue('AccountId', zBillingACctId);
		invoice.setValue('InvoiceDate', String.valueOf(DateTime.now().addDays(-1)));
		invoice.setValue('TargetDate', String.valueOf(DateTime.now().addDays(1)));
		invoiceList.add(invoice);
		List<Zuora.zApi.SaveResult> generateResult = zcallout.zApiInstance.zgenerate(invoiceList);

    }*/
    
    static String sendPaymentToZuora(String BillingAccountId, Id quoteId) {
    	
    	zqu__Quote__c quote = [SELECT Order_Number__c FROM zqu__Quote__c WHERE Id = :quoteId];
    	Order__c order = [Select Id, Payment_Mode__c, Check_Amount__c, Check_Dated__c, Check_Issuing_Bank__c, Check_No__c FROM Order__c WHERE Id = : quote.Order_Number__c];
    	
    	ZuoraCallOut zCallout = new ZuoraCallOut();
		Map<String, String> paymentMap = new Map<String, String>();
		paymentMap.put('AccountId', BillingAccountId); //billing account Id
		//paymentMap.put('Amount', String.valueOf(amount));	
		//paymentMap.put('AppliedCreditBalanceAmount', '100');
		//paymentMap.put('AppliedInvoiceAmount', '0');
		paymentMap.put('EffectiveDate', String.valueOf(DateTime.now())); //The date when the payment takes effect.
		paymentMap.put('Type', 'External');
		paymentMap.put('Status', 'Processed');
		paymentMap.put('PaymentMethodId', ConstantsSLB.getKeyId('PaymentMethodId_Check'));
		if(order.Payment_Mode__c == 'Check') {
			paymentMap.put('Amount', String.valueOf(order.Check_Amount__c));
			paymentMap.put('AppliedCreditBalanceAmount', String.valueOf(order.Check_Amount__c));
			String comments = 'Check Dated: ' + (order.Check_Dated__c != null ? String.valueOf(order.Check_Dated__c) : '--') + '; ' +
								'Check Issuing Bank: ' + (order.Check_Issuing_Bank__c != null ? order.Check_Issuing_Bank__c : '--') + ': ' +
								'Check No.: ' + (order.Check_No__c != null ? order.Check_No__c : '--');
			paymentMap.put('Comment', comments);
		}
		else {
			paymentMap.put('Amount', String.valueOf(order.Amount_Paid__c));
			paymentMap.put('AppliedCreditBalanceAmount', String.valueOf(order.Amount_Paid__c));
		}
		zCallout.createZObject(paymentMap, 'Payment');
		return null;
    }
  
}