src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>NRIC__c</fullName>
        <label>NRIC</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_Balance__c</fullName>
        <label>Credit Balance</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Delivery_Charge__c</fullName>
        <label>Delivery Charge</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Legacy_Create_By__c</fullName>
        <label>Legacy Create By</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_Create_Date__c</fullName>
        <label>Legacy Create Date</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_Update_By__c</fullName>
        <label>Legacy Update By</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_Update_Date__c</fullName>
        <label>Legacy Update Date</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Monthly_Delivery_Charge_for_Full_Payment__c</fullName>
        <label>Monthly Delivery Charge for Full Payment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Order_Legacy_Id__c</fullName>
        <externalId>true</externalId>
        <label>Order Legacy Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Case__r.Account.Name</formula>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Delivered_By__c</fullName>
        <label>Delivered By</label>
        <picklist>
            <picklistValues>
                <fullName>Vendor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mailing Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Earliest_Start_Date__c</fullName>
        <label>Earliest Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Main_Package_Billing_Type__c</fullName>
        <label>Main Package Billing Type</label>
        <picklist>
            <picklistValues>
                <fullName>Full Prepaid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recurring Prepaid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recurring Postpaid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Main_Package_Frequency__c</fullName>
        <label>Main Package Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Default</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mon - Fri</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mon - Sat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sat - Sun</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fri - Sun</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Main_Package_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Main Package ID</label>
        <referenceTo>Package__c</referenceTo>
        <relationshipLabel>Order Line Items (Main Package ID)</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Main_Package_Period__c</fullName>
        <label>Main Package Period</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Main_Package_Type__c</fullName>
        <label>Main Package Type</label>
        <picklist>
            <picklistValues>
                <fullName>Base</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bundle</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order_Line_Item__c</fullName>
        <displayFormat>A-{000000}</displayFormat>
        <label>Order Line Item #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items_Direct</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Updated Length  from 16,2 (FDS)  to 5,0 (Sample Tool tip from Eugene)</description>
        <label>Qty</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Term_Length__c</fullName>
        <label>Term Length (Mth)</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI{0000000000}</displayFormat>
        <label>Order Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order_Line_Item_Gift__c.object
<CustomObject>
    <fields>
        <fullName>Order_Line_Item__c</fullName>
        <label>Order Line Item</label>
        <referenceTo>Order_Line_Item__c</referenceTo>
        <relationshipLabel>Order Line Item Gifts</relationshipLabel>
        <relationshipName>Order_Line_Item_Gifts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Promotion_Gift__c</fullName>
        <label>Promotion Gift</label>
        <referenceTo>Promotion_Gift__c</referenceTo>
        <relationshipLabel>Order Line Item Gifts</relationshipLabel>
        <relationshipName>Order_Line_Item_Gifts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <formula>Order_Line_Item__r.Qty__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order Line Item Gift</label>
    <nameField>
        <displayFormat>OLIG{000000}</displayFormat>
        <label>Order Line Item Gift Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Item Gifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Package__c.object
<CustomObject>
    <fields>
        <fullName>Effective_End_Date__c</fullName>
        <label>Effective End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Start_Date__c</fullName>
        <label>Effective Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Package_Code__c</fullName>
        <externalId>true</externalId>
        <label>Package Code</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Package_Type__c</fullName>
        <label>Package Type</label>
        <picklist>
            <picklistValues>
                <fullName>Add On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Base</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bundle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grace Period</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subscription_Period__c</fullName>
        <label>Subscription Period</label>
        <picklist>
            <controllingField>Subscription_Type__c</controllingField>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subscription_Type__c</fullName>
        <label>Subscription Type</label>
        <picklist>
            <picklistValues>
                <fullName>Termed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evergreen</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Promotion_Gift__c.object
<CustomObject>
    <fields>
        <fullName>Gift_Inventory__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Inventory level of the gift for the promotion.</description>
        <label>Promotion Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Promotion Gift</label>
    <nameField>
        <displayFormat>PG-{00000000}</displayFormat>
        <label>Promotion Gift Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Gifts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OrderLineItemGiftTriggerHandlerTest.cls
/**
   @Author <Marjorie Gaelo>
   @name <OrderLineItemGiftTriggerHandlerTest >
   @CreateDate <2/3/2015>
   @Description <Test Class for OrderLineItemGiftTriggerHandler>
   @Version <1.0>
   @reference <Referenced program names>
  */
@isTest
private class OrderLineItemGiftTriggerHandlerTest {
    
    @testSetup 
    static void setupData() {
        insert CustomSettingsDataFactory.createOther();
    }
    
     /**
    *  @description This method executes during class instantiation.  
    *  @name <testOrderLineItemGiftTrigger>
    */
    static  testmethod void  testOrderLineItemGiftTrigger(){
    
    Account acc = TestDataFactory.createAccount(1, 'Direct Individual')[0];
    acc.Name = 'TEST';
    acc.NRIC__c = 'T1234567R';
    insert acc;
    
    Order__c order = TestDataFactory.createOrder(1)[0];
    order.Account__c = acc.id;
    order.Delivery_Charge__c = 4;
    order.Order_Legacy_Id__c = '3421';
    order.Legacy_Create_By__c = '1';
    order.Legacy_Create_Date__c = '1';
    order.Legacy_Update_By__c = '1';
    order.Legacy_Update_Date__c = '1';
    order.Monthly_Delivery_Charge_for_Full_Payment__c = 4;
    order.Credit_Balance__c =1;
    insert order;
    
    
    Package__c pack = TestDataFactory.createPackage(1)[0];
    pack.Package_Type__c = 'Base';
    pack.Name = 'testpackaA';
    pack.Package_Code__c = 'pcode2';
    pack.Subscription_Type__c = 'Termed';
    pack.Subscription_Period__c= '1';
    pack.Effective_End_Date__c = date.today().addDays(20);
    pack.Effective_Start_Date__c = date.today();
    insert pack;
    
    Order_Line_Item__c oli = TestDataFactory.createOrderLineItem(1)[0];
    oli.Earliest_Start_Date__c = date.today();
    oli.Start_Date__c =  date.today().addDays(2);
    oli.order__c = order.id;
    oli.Main_Package_ID__c = pack.id;
    oli.Main_Package_Period__c = 1;
    oli.Qty__c = 1;
    oli.Term_Length__c = 1;
    oli.Main_Package_Billing_Type__c = 'Full Prepaid';
    oli.Main_Package_Type__c = 'Base';
    oli.Main_Package_Frequency__c = 'Default';
    oli.Delivered_By__c = 'None';
    insert oli;
    
    Promotion_Gift__c promgift = TestDataFactory.createPromotionGift(1)[0];
    promgift.Gift_Inventory__c = 1;
    promgift.Gift_Issued__c = 1;
    promgift.Gift_Redeemed__c = 1;
    insert promgift;
    
    Order_Line_Item_Gift__c oligift = TestDataFactory.createItemGift(1)[0];
    oligift.Order_Line_Item__c = oli.id;
    oligift.Promotion_Gift__c = promgift.id;
    oligift.Redemption_Date__c = date.today();
    oligift.Redemption_Quantity__c = 5;
    
    Test.startTest();
    insert oligift;
    update oligift;
    delete oligift;
    Test.stopTest();
    
    OrderLineItemGiftTriggerHandler oligtHandler = new OrderLineItemGiftTriggerHandler();
    oligtHandler.runBeforeInsertTrigger();
    oligtHandler.runBeforeUpdateTrigger();
    oligtHandler.runBeforeDeleteTrigger();
    oligtHandler.runAfterInsertTrigger();
    oligtHandler.runAfterUpdateTrigger();
    oligtHandler.runAfterDeleteTrigger();
    
    }
    
    
}