src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Building_Name__c</fullName>
        <label>Building Name</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Batch-interfaced</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>House_Block_Number__c</fullName>
        <label>House/Block Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level_Number__c</fullName>
        <label>Level Number</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Singpost_Address__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Postal Code</label>
        <referenceTo>Singpost_Address__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Street_Name__c</fullName>
        <label>Street Name</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <label>Unit Number</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address_Type__c</fullName>
        <description>This field will be displayed if record type field is Local.
Read-only. Auto-populated by the system based on Postal Code</description>
        <label>Singpost Address Type</label>
        <picklist>
            <picklistValues>
                <fullName>P</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>W</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>H</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>K</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>U</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Building_Name__c</fullName>
        <description>This field will be displayed if record type field is Local. 
Read-only. Auto-populated by the system based on Postal Code</description>
        <formula>Postal_Code__r.Building_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Building Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>City Code</label>
        <referenceTo>City__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company Code</label>
        <referenceTo>SPH_Company__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_Name__c</fullName>
        <formula>Country__r.Country_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>SPH_Department__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Division Code</label>
        <referenceTo>SPH_Division__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flight_Number_1__c</fullName>
        <formula>City__r.Flight_Number_1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Flight Number 1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level_Number__c</fullName>
        <description>This field will be displayed if record type field is Local.
User specified</description>
        <label>Level Number</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Units__c</fullName>
        <formula>Postal_Code__r.Number_of_Units__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Number of Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be displayed if record type field is Local.
User specified</description>
        <label>Postal Code</label>
        <referenceTo>Singpost_Address__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Section Code</label>
        <referenceTo>SPH_Section__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Street_Name__c</fullName>
        <description>This field will be displayed if record type field is Local. 
Read-only. Auto-populated by the system based on Postal Code</description>
        <formula>Postal_Code__r.Street_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Street Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <description>This field will be displayed if record type field is Local.
User specified</description>
        <label>Unit Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <recordTypes>
        <fullName>Internal</fullName>
        <active>true</active>
        <description>For Internal Subscribers</description>
        <label>Internal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Local</fullName>
        <active>true</active>
        <description>For Local Subscribers</description>
        <label>Local</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/City__c.object
<CustomObject>
    <fields>
        <fullName>City_Name__c</fullName>
        <label>City Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Cities</relationshipLabel>
        <relationshipName>Cities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flight_Number_1__c</fullName>
        <description>Formula Display on Airlines Address</description>
        <label>Flight Number (1)</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>City</label>
    <nameField>
        <label>City Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>User specified</description>
        <label>Email Address 1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>HomePhone__c</fullName>
        <description>User specified</description>
        <label>Home Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Street_Name__c</fullName>
        <formula>Address__r.Street_Name__c</formula>
        <label>Street Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <formula>Address__r.Unit_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unit Number</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Country_Name__c</fullName>
        <label>Country Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Email__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <label>Email</label>
</CustomObject>

src/objects/Singpost_Address__c.object
<CustomObject>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Building_Name__c</fullName>
        <description>User Specified</description>
        <label>Building Name</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>House_Block_Number__c</fullName>
        <label>House/Block Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Units__c</fullName>
        <label>Number of Units</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Street_Name__c</fullName>
        <label>Street Name</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Singpost Address</label>
    <nameField>
        <label>Postal Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Singpost Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CreateModifyContactAddressControllerTest.cls
@isTest(seeAllData = TRUE)
public class CreateModifyContactAddressControllerTest {
    /**
     * Class Name: CreateModifyContactAddressControllerTest
     * @author: Jeffrey B. Teves
     * Date: 
     * Requirement/Project Name: CRSM Project
     * @description Test Class for CAM_CreateModifyContactAddressController
     * 
     */
    
    static User cso;
    static Account acc;
    static List<Address__c> addressList;
    static SingPost_Address__c singPost;
    static Country__c country;
    static City__c city;
    
    static testMethod void testLocalAddress() {
        prepareTestUsers();
        System.runAs(cso) {
            prepareTestData();
            
            Test.startTest();
            
            //initialize page and controllers
            PageReference pRef = Page.CreateModifyContactAddress;
            Test.setCurrentPage(pRef);
            ApexPages.currentPage().getParameters().put('accountId', acc.Id);
            ApexPages.StandardController stdCtrlr = new ApexPages.StandardController(new Contact());
            CAM_CreateModifyContactAddressController controller = new CAM_CreateModifyContactAddressController(stdCtrlr);
            
            //assert number of available options for address types : 5
            System.assertEquals(controller.getAddressTypeOptions().size(), 5);
            
            //test search functionality
            controller.stagedAddress.Postal_Code__c = singPost.Id;
            controller.search();
            System.assertEquals(10, controller.add.size());
            
            //test city/country code fubnctionality
            controller.stagedAddress.City__c = city.Id;
            controller.fetchCityName();
            System.assertEquals(city.City_Name__c, controller.cityName);
            controller.StagedAddress.City__c = null;
            controller.fetchCityName();
            System.assertEquals('', controller.cityName);
            
            controller.selectedCountry = country.Id;
            controller.fetchCountryCode();
            system.assertEquals(country.Name, controller.countryCode);
            
            //get address record
            controller.addressId = addressList[0].Id;
            controller.selectAddressRecord();
            System.assertEquals(addressList[0].Id, controller.thisContact.Address__c);
            
            //clear address record
            controller.clearAddressDetails();
            System.assertEquals(NULL, controller.thisContact.Address__c);
            
            controller.clearContactAddress();
            System.assertEquals(NULL, controller.thisContact.Address__c);
            
            Test.stopTest();
        } 
    }
    
    static testMethod void testInternalContact() {
        prepareTestUsers();
        
        System.runAs(cso) {
            prepareTestData();
            
            Test.startTest();
            
            //initialize page and controllers
            PageReference pRef = Page.CreateModifyContactAddress;
            Test.setCurrentPage(pRef);
            ApexPages.StandardController stdCtrlr = new ApexPages.StandardController(new Contact());
            CAM_CreateModifyContactAddressController controller = new CAM_CreateModifyContactAddressController(stdCtrlr);
            
            //assert number of available options for address types : 5
            System.assertEquals(controller.getAddressTypeOptions().size(), 5);
            
            //set address details
            controller.AddressType = 'Internal';
            /*controller.stagedAddress.LocationCode__c = 'Test Location';
            controller.stagedAddress.Company_Code__c = 'Test Company Code';
            controller.stagedAddress.Division_Code__c = 'Test Division Code';
            controller.stagedAddress.Department__c = 'Test Department';
            controller.stagedAddress.Section_Code__c = 'Test Section Code';
            */
            //set contact details
            controller.thisContact.AccountId = acc.Id;
            controller.thisContact.LastName = 'test last name';
            controller.thisContact.FirstName = 'test first name';
            controller.thisContact.HomePhone__c = '1234567';
            
            //set indicator flags -- tick both so we will create 2 contact records
            controller.billingIndicator = TRUE;
            controller.recipientIndicator = TRUE;
            
            //invoke save action
            controller.saveRecord();
            
            //assert field values for inserted records
            Boolean isBillingContactCreated = FALSE;
            Boolean isRecipientCOntactCreated = FALSE;
            /*for(Contact con : [SELECT Id, LastName, FirstName, RecordType.Name, Address__r.LocationCode__c, Address__r.Company_Code__c, Address__r.Division_Code__c, Address__r.Department__c, Address__r.Section_Code__c FROM Contact WHERE AccountId = :acc.Id]) {
                System.assertEquals('test last name', con.LastName);
                System.assertEquals('test first name', con.FirstName);
                System.assertEquals('Test Location', con.Address__r.LocationCode__c);
                System.assertEquals('Test Company Code', con.Address__r.Company_Code__c);
                System.assertEquals('Test Division Code', con.Address__r.Division_Code__c);
                System.assertEquals('Test Department', con.Address__r.Department__c);
                System.assertEquals('Test Section Code', con.Address__r.Section_Code__c);
                if(con.RecordType.Name == 'Billing Contact') {
                    isBillingContactCreated = TRUE;
                }
                if(con.RecordType.Name == 'Recipient Contact') {
                    isRecipientCOntactCreated = TRUE;
                }
            }*/
            //assert if billing and recipient contacts are created
            //System.assert(isBillingContactCreated);
            //System.assert(isRecipientContactCreated);
            
            Test.stopTest();
        } 
    }
    
    static testMethod void testErrorHandling() {
        prepareTestUsers();
        
        System.runAs(cso) {
            prepareTestData();
            
            Test.startTest();
            
            //initialize page and controllers
            PageReference pRef = Page.CreateModifyContactAddress;
            Test.setCurrentPage(pRef);
            ApexPages.StandardController stdCtrlr = new ApexPages.StandardController(new Contact());
            CAM_CreateModifyContactAddressController controller = new CAM_CreateModifyContactAddressController(stdCtrlr);
            
            //assert number of available options for address types : 5
            System.assertEquals(controller.getAddressTypeOptions().size(), 5);
            
            //assert error on billing/recipient indicator
            controller.billingIndicator = FALSE;
            controller.recipientIndicator = FALSE;
            controller.saveRecord();
            System.AssertEquals('Please tick Billing Indicator, Recipient Indicator or both.', ApexPages.getMessages().get(ApexPages.getMessages().size()-1).getSummary());
            
            //assert error on null adress type
            controller.billingIndicator = TRUE;
            controller.recipientIndicator = TRUE;
            controller.AddressType = '';
            controller.saveRecord();
            System.AssertEquals('Please select an address type!', ApexPages.getMessages().get(ApexPages.getMessages().size()-1).getSummary());
            
            //assert error on null postal code for Local address type
            controller.checked = TRUE;
            controller.AddressType = 'Local';
            controller.saveRecord();
            System.AssertEquals('Please select a Postal Code.', ApexPages.getMessages().get(ApexPages.getMessages().size()-1).getSummary());
            
            //assert error on invalid unit number
            controller.stagedAddress.Postal_Code__c = singPost.Id;
            controller.stagedAddress.Unit_Number__c = '1';
            controller.saveRecord();
            System.AssertEquals('Unit must be at least two characters.', ApexPages.getMessages().get(ApexPages.getMessages().size()-1).getSummary());
            
            //assert error on invalid level number
            controller.stagedAddress.Postal_Code__c = singPost.Id;
            controller.stagedAddress.Unit_Number__c = '11';
            controller.stagedAddress.Level_Number__c = '1';
            controller.saveRecord();
            System.AssertEquals('Level must be at least two characters.', ApexPages.getMessages().get(ApexPages.getMessages().size()-1).getSummary());
            
            //assert error on null address Id
            controller.checked = FALSE;
            controller.stagedAddress.Level_Number__c = '11';
            controller.saveRecord();
            System.AssertEquals('Please select an existing Address record or create a New one.', ApexPages.getMessages().get(ApexPages.getMessages().size()-1).getSummary());
            
            //assert error on attempt to insert existing address
            controller.checked = TRUE;
            controller.stagedAddress.Postal_Code__c = singPost.Id;
            controller.saveRecord();
            System.assert(ApexPages.getMessages().get(ApexPages.getMessages().size()-1).getSummary().contains('Existing Address record found:'));            
            
            //assert queryexception on save record
            
            
            //assert DML exception on saverecord method
            controller.thisContact.LastName = 'test';
            controller.stagedAddress.Unit_Number__c = '51';
            controller.saveRecord();
            System.assertEquals('At least 1 phone number should be entered (either home phone, mobile, other phone or office number).', ApexPages.getMessages().get(ApexPages.getMessages().size()-1).getSummary());
            
            PageReference pRef_2 = Page.CreateModifyContactAddress;
            Test.setCurrentPage(pRef);
            ApexPages.currentPage().getParameters().put('accountId', '1234567890');
            ApexPages.StandardController stdCtrlr_2 = new ApexPages.StandardController(new Contact());
            CAM_CreateModifyContactAddressController controller_2 = new CAM_CreateModifyContactAddressController(stdCtrlr_2);
            System.assert(ApexPages.getMessages().get(ApexPages.getMessages().size()-1).getSummary().contains('Error trying to fetch Account details'));
        
            Test.stopTest();
        } 
    }
    
    static void prepareTestusers() {
        cso = new User(
            Alias = 'standt',
            Email='standarduser@gmail.com', 
            EmailEncodingKey='UTF-8',
            LastName='Testing',
            LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US',
            ProfileId = ConstantsSLB.getKeyId('Profile_System Administrator'), 
            TimeZoneSidKey='America/Los_Angeles',
            UserName='userstand3541987*@testorg.com'
        );
    }
    
    static void prepareTestdata() {
        
        acc = new Account(
            Name = 'Test Account',
            RecordtypeId = ConstantsSLB.getKeyId('Account_Direct Individual'),
            Email__c = 'Test@testing.com'
        );
        insert acc;
        
        singPost = new SingPost_Address__c(
            Name = '999999',
            Building_Name__c = 'Test Building Name',
            Address_Type__c = 'S',
            Street_Name__c = 'Test Street Name',
            Number_of_Units__c = 1,
            House_Block_Number__c = '1'
        );
        insert singPost;
        
        country = new Country__c(
            Name = 'xx',
            Country_Name__c = 'Country Name'
        );
        insert country;
        
        addressList = new List<Address__c>();
        for(Integer x = 10; x < 20; x++) {
            addressList.add(
                new Address__c(
                    Postal_Code__c = singPost.Id,
                    Unit_Number__c = String.valueOf(x),
                    Name = 'Test Add ' + x,
                    Level_Number__c = String.valueOf(x),
                    country__c = country.id
                )
            );            
        }
        insert addressList;
        
        
        city = new City__c(
            Name = 'yy',
            City_Name__c = 'City Name',
            Flight_Number_1__c = 'SQ279-DAILY'
        );
        insert city;
        
        
    }
}