src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Billing_Type__c</fullName>
        <description>For populating New Billing Account in Zuora via SendToZBilling. Add to Field Set zqu__CustomAccountFields</description>
        <label>Billing Type (System Use)</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Batch-interfaced</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Singpost_Address__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Postal Code</label>
        <referenceTo>Singpost_Address__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be displayed if record type field is Local.
User specified</description>
        <label>Postal Code</label>
        <referenceTo>Singpost_Address__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>User specified</description>
        <label>Email Address 1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Recipient_Contact__c</fullName>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Recipient Contact</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recipient_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recipient Indicator</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Email__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <label>Email</label>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_Type__c</fullName>
        <label>Billing Type</label>
        <picklist>
            <picklistValues>
                <fullName>Full Prepaid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recurring Prepaid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recurring Postpaid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Informed_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Informed Customer?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Legacy_Create_By__c</fullName>
        <label>Legacy Create By</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_Create_Date__c</fullName>
        <label>Legacy Create Date</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_Update_By__c</fullName>
        <label>Legacy Update By</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_Update_Date__c</fullName>
        <label>Legacy Update Date</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Mode__c</fullName>
        <label>Payment Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>ARMS field</description>
        <label>ARMS Postal Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recipient Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.Recipient_Indicator__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Recipient Contact)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Refund_Amount__c</fullName>
        <label>Refund Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subscriber_Charge__c</fullName>
        <label>Subscriber Charge</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Case__r.Account.Name</formula>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Main_Package_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Main Package ID</label>
        <referenceTo>Package__c</referenceTo>
        <relationshipLabel>Order Line Items (Main Package ID)</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Line_Item__c</fullName>
        <displayFormat>A-{000000}</displayFormat>
        <label>Order Line Item #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items_Direct</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI{0000000000}</displayFormat>
        <label>Order Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Package__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Type__c</fullName>
        <label>Billing Type</label>
        <picklist>
            <controllingField>Package_Type__c</controllingField>
            <picklistValues>
                <fullName>Full Prepaid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recurring Prepaid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recurring Postpaid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subscription_Period__c</fullName>
        <label>Subscription Period</label>
        <picklist>
            <controllingField>Subscription_Type__c</controllingField>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Singpost_Address__c.object
<CustomObject>
    <label>Singpost Address</label>
    <nameField>
        <label>Postal Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Singpost Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CancelSubscriptionBatchTest.cls
/**
 * Class Name: CancelSubscriptionBatchTest
 * @author: Recuerdo Bregente
 * Date: 07.13.2015
 * Requirement/Project Name: SPH
 * @description Test Class for CancelSubscriptionBatch
 */
@isTest(seeAllData=true)
private class CancelSubscriptionBatchTest {

    static Integer uname = 0;
    static Account acc;
    static Singpost_Address__c postal;
    static Address__c address;
    static List<Contact> con;
    static List<Package__c> pkg;
    static List<Zuora__CustomerAccount__c> zcaList;
    static List<Zuora__Subscription__c> zSubs;
    static List<Zuora__PaymentMethod__c> zpmList;
    
    static Set<String> orderIdForStopSubscription;
    static Set<String> subscriptionIdSetForCancellation;
    static Date stopDate;
    static Set<String> zAccountId;
    static Id accountId;
    
        
    /**
    * @author : Recuerdo Bregente
    * @description : Prepares the test data objects.
    * @date: 07/08/2015
    */ 
    static void prepareTestData(String methodType){
            acc = TestDataFactory.createAccount(1, 'Direct Corporate')[0];
            acc.Name = 'Test Account';
            acc.Email__c = 'test@email.com';
            acc.Mobile__c = '09324861074';
            insert acc;
            
            postal = new Singpost_Address__c();
            postal = TestDataFactory.createSingpostAddress(1)[0];
            insert postal;
            
            address = new Address__c();
            address = TestDataFactory.createAddress(1)[0];
            address.Postal_Code__c = postal.Id;
            insert address;
            
            con = TestDataFactory.createContact(1);
            con[0].Phone = '1234567';
            con[0].AccountId = acc.Id;
            con[0].Recipient_Indicator__c = true;
            insert con;
                   
            pkg = TestDataFactory.createPackage(1);
            pkg[0].Subscription_Period__c = '15'; 
            insert pkg;
           
            
            zcaList = TestDataFactory.createBillingAccount(1);
            zcaList[0].Name = 'Zuora Customer Account';
            zcaList[0].Zuora__Account__c = acc.Id;
            zcaList[0].Zuora__Credit_Balance__c = 1;
            zcaList[0].Refund_Amount__c = 100;
            zcaList[0].Zuora__AutoPay__c =false;
            zcaList[0].Zuora__Balance__c = 1;
            zcaList[0].Payment_Mode__c = methodType;
            zcaList[0].Other_PaymentMethod__c= methodType;
            //zcaList[0].Zuora__Default_Payment_Method__c = zpmList[0].id;
            zcaList[0].Zuora__PaymentMethodType__c = methodType; 
            zcalist[0].Zuora__External_Id__c = '22544AA';  
            zcalist[0].Zuora__Zuora_Id__c = '0124';         
            insert zcaList;
            
            //START : D-1929 3/2/2015 added to create Default Payment Method
            zpmList = TestDataFactory.createPaymentMethod(1);
            zpmList[0].Name = 'Zuora Customer Account';
            zpmList[0].Zuora__Type__c = methodType;
            zpmList[0].Zuora__BillingAccount__c = zcaList[0].id;
            insert zpmList;  
            //End: D-1929 3/2/2015 added to create Default Payment Method
            
            zcalist[0].Zuora__Default_Payment_Method__c = zpmList[0].id;         
            update zcaList;
            
            Order__c orderRec = TestDataFactory.createOrder(1)[0];
            orderRec.Account__c = acc.Id;
            orderRec.Informed_Customer__c = TRUE;
            orderRec.Recipient_Contact__c = con[0].Id;
            orderRec.Subscriber_Charge__c = 15;
            insert orderRec;
                
            Order_Line_Item__c orderline = TestDataFactory.createOrderLineItem(1)[0];
            orderline.Order__c = orderRec.Id;
            orderline.Start_Date__c = Date.Today().addDays(1);
            orderline.End_Date__c = Date.Today().addDays(100);
            orderline.Main_Package_ID__c = pkg[0].id;
            insert orderline;
            
            //create billing account      
            zSubs =  TestDataFactory.createSubscription(1);
            zSubs[0].Order_Line_Item_Number__c = orderline.Id;
            zSubs[0].Subscriber_Contact__c = con[0].id;
            zSubs[0].Main_Package_1__c = pkg[0].id;
            zSubs[0].Zuora__Account__c = acc.id;
            zSubs[0].Order_Number__c = null;
            zSubs[0].Zuora__CustomerAccount__c = zcaList[0].Id;
            zSubs[0].Billing_Type__c = 'Full Prepaid';
            zSubs[0].Legacy_Create_Date__c = 'a';
            zSubs[0].Legacy_Create_By__c = 'a';
            zSubs[0].Legacy_Update_By__c = 'a';
            zSubs[0].Legacy_Subscription_ID__c = 'a';
            zSubs[0].Legacy_Update_Date__c = 'a';
            zSubs[0].Number_of_Copies__c = 100;
            zSubs[0].Number_of_Copies1__c = '100';
            zSubs[0].Zuora__Zuora_Id__c = 'ZZ0001';
            zSubs[0].Recipient_Contact__c = con[0].id;
            insert zSubs;
            
            subscriptionIdSetForCancellation =  new Set<String>();
            subscriptionIdSetForCancellation.add('ZZ0001');
            
            stopDate = Date.today();
            accountId = acc.Id;
    }

    
    /**
    * @name: testBatch
    * @author : Recuerdo Bregente
    * @description : Tests the batch
    * @date: 07/13/2015
    */
    static testMethod void testBatch(){
        try{
             prepareTestData('Cash');
             Test.startTest();
             CancelSubscriptionBatch batch = new CancelSubscriptionBatch(orderIdForStopSubscription,
                                        subscriptionIdSetForCancellation,
                                        stopDate,
                                        zAccountId,
                                        accountId);
             Database.executeBatch(batch, 200);
             Test.stopTest();
         } catch(Zuora.zAPIException e){
             System.assertNotEquals(null, accountId);
         }
    }
    
    static testMethod void testBatch2(){
        try{
             prepareTestData('Cash');
             Test.startTest();
             Database.BatchableContext BC;
             CancelSubscriptionBatch batch = new CancelSubscriptionBatch(orderIdForStopSubscription,
                                        subscriptionIdSetForCancellation,
                                        stopDate,
                                        zAccountId,
                                        accountId);
             batch.finish(BC);
             Test.stopTest();
         } catch(Zuora.zAPIException e){
             System.assertNotEquals(null, accountId);
         }
    }
}