src/objects/Address__c.object
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/BATCH_JOB_SCHEDULER__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Run_Date__c</fullName>
        <label>Batch Run Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SFDC_Job_id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>SFDC_Job_id</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>BATCH_JOB_SCHEDULER</label>
    <nameField>
        <displayFormat>SBRR-{0000000000}</displayFormat>
        <label>SP Batch Run Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BATCH_JOB_SCHEDULER</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account field that is not read-only to be used in Adjustment Case. Field Value will be copied into Account Standard field and will not be exposed in detail page layout.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Account) (Do Not Use)</relationshipLabel>
        <relationshipName>Cases_Do_Not_Use</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Main_Package__c</fullName>
        <description>Custom field for Main Package.</description>
        <label>Main Package</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Cases (Order Number)</relationshipLabel>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <label>Qty</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Restart_Date__c</fullName>
        <label>Restart Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Temp_Stop_Date__c</fullName>
        <label>Temp Stop Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Temp_Stop__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Temp Stop</label>
        <referenceTo>Temp_Stop__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Billing Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Recipient_Contact__c</fullName>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Recipient Contact</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recipient_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recipient Indicator</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Informed_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Informed Customer?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Recipient_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recipient Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.Recipient_Indicator__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Recipient Contact)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND NOT 5) OR (1 AND 2 AND 3 AND 4 AND 5)</booleanFilter>
            <filterItems>
                <field>Zuora__Subscription__c.Subscription_Type_1__c</field>
                <operation>equals</operation>
                <value>Publication</value>
            </filterItems>
            <filterItems>
                <field>Zuora__Subscription__c.Zuora__Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Zuora__Subscription__c.Zuora__Status__c</field>
                <operation>notEqual</operation>
                <value>Cancelled</value>
            </filterItems>
            <filterItems>
                <field>$Source.Order_Type1__c</field>
                <operation>contains</operation>
                <value>Change of Subscription</value>
            </filterItems>
            <filterItems>
                <field>$Source.isChangeOfSubEntry__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Package__c.object
<CustomObject>
    <fields>
        <fullName>Subscription_Type__c</fullName>
        <label>Subscription Type</label>
        <picklist>
            <picklistValues>
                <fullName>Termed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evergreen</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Package_Item__c.object
<CustomObject>
    <fields>
        <fullName>Package__c</fullName>
        <description>The package name for which the package item is being created will be displayed.</description>
        <label>Package</label>
        <referenceTo>Package__c</referenceTo>
        <relationshipLabel>Package Items</relationshipLabel>
        <relationshipName>Package_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Rate Plan</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>zqu__ProductRatePlan__c.zqu__Deleted__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>Package Items</relationshipLabel>
        <relationshipName>Package_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Package Item</label>
    <nameField>
        <label>Package Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Package Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subscription_Temp_Stop__c.object
<CustomObject>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Subscription Temp Stops</relationshipLabel>
        <relationshipName>Subscription_Temp_Stops</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Temp_Stop__c</fullName>
        <label>Temp Stop</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Temp_Stop__c</referenceTo>
        <relationshipLabel>Subscription Temp Stops</relationshipLabel>
        <relationshipName>Subscription_Temp_Stops</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subscription Temp Stop</label>
    <nameField>
        <displayFormat>STS-{0000000000}</displayFormat>
        <label>Subscription Temp Stop Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Temp Stops</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Temp_Stop__c.object
<CustomObject>
    <fields>
        <fullName>Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelled?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Temp Stops</relationshipLabel>
        <relationshipName>Temp_Stops</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <label>Qty</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Restart_Date__c</fullName>
        <label>Restart Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Temp_Stop_Date__c</fullName>
        <label>Temp Stop Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Temp_Stop_Status__c</fullName>
        <formula>IF(Cancelled__c , &apos;Cancelled&apos;, IF(Temp_Stop_Date__c &gt;  TODAY(), &apos;Not Started&apos;,  IF(Temp_Stop_Date__c&lt;= TODAY() &amp;&amp;  Restart_Date__c &gt; TODAY(), &apos;On-going&apos;,  IF(Restart_Date__c &lt;= TODAY(), &apos;Completed&apos;, null) ) )  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Temp Stop Status</label>
        <type>Text</type>
    </fields>
    <label>Temp Stop</label>
    <nameField>
        <displayFormat>TS-{0000000000}</displayFormat>
        <label>Temp Stop</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Temp Stops</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SP_DeliveryChargesBatch_SelectAccsTest.cls
/**
 * Class Name: SP_DeliveryChargesBatch_SelectAccsTest
 * @author: Christian Coquilla
 * Date: 4/13/2016
 * Requirement/Project Name: Singapore Press Holdings
 * @description Test Class for SP_DeliveryChargesBatch_SelectAccs
 */
 
 @isTest(seeAllData = True)
public class SP_DeliveryChargesBatch_SelectAccsTest {
    private final static Date referenceDate = UsageHelper.getUsageReferenceDate(); 
    static testmethod void test01(){
    
     Account acc = TestDataFactory.createAccount(1, 'Direct Corporate')[0];
     insert acc;
     
     set<String> AccntSet = new set<string>();
     AccntSet.add('acc.Id');
     
     Zuora__CustomerAccount__c billAcc = TestDataFactory.createBillingAccount(1)[0];
     billAcc.Zuora__DefaultPaymentMethod__c = 'Other'; 
     billAcc.Zuora__Account__c = acc.Id;
     billAcc.Zuora__AccountNumber__c = '123';
     database.insert(billAcc);
    
     Address__c address = TestDataFactory.createAddress(1)[0];
     database.insert(address);
    
     Contact con = TestDataFactory.createContact(1)[0];
     con.AccountId = acc.id;
     con.Address__c = address.Id;
     //con.Billing_Indicator__c = True;
     con.Recipient_Indicator__c = true;
     database.insert(con);
 
     Package__c pack = TestDataFactory.createPackage(1)[0];
     database.insert(pack);
    
     Order__c orderRec = TestDataFactory.createOrder(1)[0];
     orderRec.Account__c = acc.Id;
     orderRec.Informed_Customer__c = TRUE;
     orderRec.Recipient_Contact__c = con.Id;
     database.insert(orderRec);
    
    /*Case cas = TestDataFactory.createCase(1, 'Temp Stop Subscription')[0];
    cas.Order__c = orderRec.Id;
    database.insert(cas);*/
    
     List<Temp_Stop__c> temp = TestDataFactory.createTempStop(1);
     temp[0].Restart_Date__c = referenceDate.addMonths(1).toStartofMonth().addDays(-1);
     temp[0].Temp_Stop_Date__c = referenceDate.toStartOfMonth();
     temp[0].Qty__c = 3;
     temp[0].Cancelled__c  = false;
    
     /*temp[1].Restart_Date__c = date.newInstance(referenceDate.year(), 12, 31);
     temp[1].Temp_Stop_Date__c = date.newInstance(referenceDate.year()-1, 1, 1);
     temp[1].Qty__c = 3;
     temp[1].Cancelled__c  = false;*/
     database.insert(temp);
    
     system.assertEquals(null, temp[0].Temp_Stop_Status__c);

     zqu__ZProduct__c zProduct = TestDataFactory.createZProduct(1)[0];
     zProduct.ProductSubType__c = 'Newspaper';
     zProduct.ProductPlatform__c = 'Print';
     database.insert(zProduct);
        
     zqu__ProductRatePlan__c prdRatePlan = TestDataFactory.createProductRatePlan(1)[0];
     prdRatePlan.zqu__ZProduct__c = zProduct.Id;
     database.insert(prdRatePlan);
        
     zqu__ProductRatePlanCharge__c prpc = TestDataFactory.createProductRatePlanCharge(1)[0];
     prpc.zqu__ProductRatePlan__c = prdRatePlan.Id;
     database.insert(prpc);
        
     List<Package_Item__c> pItems = TestDataFactory.createPackageItem(2, 'Base Product');
     for (Package_Item__c pItem : pItems) {
     pItem.Package__c = pack.Id;
     pItem.Product_Rate_Plan__c = prdRatePlan.Id;
     }
     database.insert(pItems);     
     
     List<Zuora__Subscription__c> subRecs = TestDataFactory.createSubscription(2);
     subRecs[0].Zuora__Account__c = acc.Id;
     subRecs[0].Name = 'TestName';
     subRecs[0].Zuora__CustomerAccount__c = billAcc.id;
     subRecs[0].Order_Number_1__c = orderRec.Id;
     subRecs[0].Order_Number__c = orderRec.Id;
     subRecs[0].Term_Length__c = 0;
     subRecs[0].Term_Length1__c = '0';
     subRecs[0].Main_Package_1__c = pack.id;
     subRecs[0].Main_Package__c = pack.Id;
     subRecs[0].Zuora__SubscriptionStartDate__c = Date.Today();
     subRecs[0].Zuora__SubscriptionEndDate__c = date.Today()+1;
     subRecs[0].Recipient_Contact__c = con.Id;
     subRecs[0].Recipient_Contact_1__c = con.Id;
     subRecs[0].Zuora__Status__c = 'Active';
     subRecs[0].Frequency_1__c = 'Default';
     subRecs[0].Frequency__c = 'Default';
     subRecs[0].Subscription_Type_1__c = 'Publication';
     subRecs[0].Subscription_Type__c = 'Publication';
     
     subRecs[1].Zuora__Account__c = acc.Id;
     subRecs[1].Name = 'TestName';
     subRecs[1].Zuora__CustomerAccount__c = billAcc.id;
     subRecs[1].Order_Number_1__c = orderRec.Id;
     subRecs[1].Order_Number__c = orderRec.Id;
     subRecs[1].Term_Length__c = 0;
     subRecs[1].Term_Length1__c = '0';
     subRecs[1].Main_Package_1__c = pack.id;
     subRecs[1].Main_Package__c = pack.Id;
     subRecs[1].Zuora__SubscriptionStartDate__c = Date.Today();
     subRecs[1].Zuora__SubscriptionEndDate__c = date.Today()+1;
     subRecs[1].Recipient_Contact__c = con.Id;
     subRecs[1].Recipient_Contact_1__c = con.Id;
     subRecs[1].Zuora__Status__c = 'Active';
     subRecs[1].Frequency_1__c = 'Default';
     subRecs[1].Frequency__c = 'Default';
     subRecs[1].Subscription_Type_1__c = 'Delivery';
     subRecs[1].Subscription_Type__c = 'Delivery';
     database.insert(subRecs);
     
     List<Subscription_Temp_Stop__c> subtempstopList = new List<Subscription_Temp_Stop__c>(); 
     Subscription_Temp_Stop__c subTemp = new Subscription_Temp_Stop__c();
     subTemp.Temp_Stop__c = temp[0].Id;
     subTemp.Subscription__c = subRecs[0].Id;
     database.insert(subTemp);
     
    Subscription_Temp_Stop__c subTemp2 = new Subscription_Temp_Stop__c();
    subTemp2.Temp_Stop__c = temp[0].Id;
    subTemp2.Subscription__c = subRecs[1].Id;
    database.insert(subTemp2);
    
    subtempstopList.add(subTemp);
    subtempstopList.add(subTemp2);    
     
      list<Subscription_Temp_Stop__c> listtemp = [SELECT Id, Subscription__c, Subscription__r.Recipient_Contact__r.Address__c,
      Subscription__r.Zuora__CustomerAccount__c, Subscription__r.Subscription_Type_1__c, Temp_Stop__c, Temp_Stop__r.Restart_Date__c,
      Subscription__r.Recipient_Contact_1__c, Subscription__r.Recipient_Contact__c, Temp_Stop__r.Temp_Stop_Date__c, Temp_Stop__r.Temp_Stop_Status__c 
      FROM Subscription_Temp_Stop__c WHERE Id =: subTemp.Id]; 
      
      list<Subscription_Temp_Stop__c> listtemp2 = [SELECT Id, Subscription__c, Subscription__r.Recipient_Contact__r.Address__c,
      Subscription__r.Zuora__CustomerAccount__c, Subscription__r.Subscription_Type_1__c, Temp_Stop__c, Temp_Stop__r.Restart_Date__c,
      Subscription__r.Recipient_Contact_1__c, Subscription__r.Recipient_Contact__c, Temp_Stop__r.Temp_Stop_Date__c, Temp_Stop__r.Temp_Stop_Status__c 
      FROM Subscription_Temp_Stop__c WHERE Id =: subTemp2.Id];  
    
    Test.startTest();
            Database.BatchableContext bc;            
            SP_DeliveryChargesBatch_SelectAccs batch = new SP_DeliveryChargesBatch_SelectAccs(AccntSet);
            //String batchId = Database.executeBatch(batch);
            id batchID = database.executeBatch(batch, 200);
            batch.execute(bc, listtemp);
            batch.execute(bc, listtemp2);
            batch.createUsage(1, subRecs[0]);
            //String schedBatchId = System.scheduleBatch(delCharge, 'testJob', 1);
            //Database.BatchableContext BC;
            //delCharge.finish(BC);
            
            /*BATCH_JOB_SCHEDULER__c batchJobSched = new BATCH_JOB_SCHEDULER__c();
            batchJobSched.SFDC_Job_id__c = batchId;
            batchJobSched.Batch_Run_Date__c = System.today();
            insert batchJobSched;*/
            Test.stopTest();
   
    }
    static testmethod void test02(){
    
     Account acc = TestDataFactory.createAccount(1, 'Direct Corporate')[0];
     insert acc;
     
     set<String> AccntSet = new set<string>();
     AccntSet.add('acc.Id');
     
     Zuora__CustomerAccount__c billAcc = TestDataFactory.createBillingAccount(1)[0];
     billAcc.Zuora__DefaultPaymentMethod__c = 'Other'; 
     billAcc.Zuora__Account__c = acc.Id;
     billAcc.Zuora__AccountNumber__c = '123';
     database.insert(billAcc);
    
     Address__c address = TestDataFactory.createAddress(1)[0];
     database.insert(address);
    
     Contact con = TestDataFactory.createContact(1)[0];
     con.AccountId = acc.id;
     con.Address__c = address.Id;
     //con.Billing_Indicator__c = True;
     con.Recipient_Indicator__c = true;
     database.insert(con);
     
     Contact con1 = TestDataFactory.createContact(1)[0];
     con1.AccountId = acc.id;
     con1.Address__c = address.Id;
     //con.Billing_Indicator__c = True;
     con1.Recipient_Indicator__c = true;
     database.insert(con1);     
     
     
            
    
     Package__c pack = TestDataFactory.createPackage(1)[0];
     database.insert(pack);
    
     Order__c orderRec = TestDataFactory.createOrder(1)[0];
     orderRec.Account__c = acc.Id;
     orderRec.Informed_Customer__c = TRUE;
     orderRec.Recipient_Contact__c = con.Id;
     database.insert(orderRec);
    
    /*Case cas = TestDataFactory.createCase(1, 'Temp Stop Subscription')[0];
    cas.Order__c = orderRec.Id;
    database.insert(cas);*/
    
     List<Temp_Stop__c> temp = TestDataFactory.createTempStop(1);
     temp[0].Restart_Date__c = referenceDate.addMonths(3).toStartofMonth().addDays(-1);
     temp[0].Temp_Stop_Date__c = referenceDate.toStartOfMonth();
     temp[0].Qty__c = 3;
     temp[0].Cancelled__c  = false;
    
     /*temp[1].Restart_Date__c = date.newInstance(referenceDate.year(), 12, 31);
     temp[1].Temp_Stop_Date__c = date.newInstance(referenceDate.year()-1, 1, 1);
     temp[1].Qty__c = 3;
     temp[1].Cancelled__c  = false;*/
     database.insert(temp);
    
     system.assertEquals(null, temp[0].Temp_Stop_Status__c);

     zqu__ZProduct__c zProduct = TestDataFactory.createZProduct(1)[0];
     zProduct.ProductSubType__c = 'Newspaper';
     zProduct.ProductPlatform__c = 'Print';
     database.insert(zProduct);
        
     zqu__ProductRatePlan__c prdRatePlan = TestDataFactory.createProductRatePlan(1)[0];
     prdRatePlan.zqu__ZProduct__c = zProduct.Id;
     database.insert(prdRatePlan);
        
     zqu__ProductRatePlanCharge__c prpc = TestDataFactory.createProductRatePlanCharge(1)[0];
     prpc.zqu__ProductRatePlan__c = prdRatePlan.Id;
     database.insert(prpc);
        
     List<Package_Item__c> pItems = TestDataFactory.createPackageItem(2, 'Base Product');
     for (Package_Item__c pItem : pItems) {
     pItem.Package__c = pack.Id;
     pItem.Product_Rate_Plan__c = prdRatePlan.Id;
     }
     database.insert(pItems);     
     
     List<Zuora__Subscription__c> subRecs = TestDataFactory.createSubscription(2);
     subRecs[0].Zuora__Account__c = acc.Id;
     subRecs[0].Name = 'TestName';
     subRecs[0].Zuora__CustomerAccount__c = billAcc.id;
     subRecs[0].Order_Number_1__c = orderRec.Id;
     subRecs[0].Order_Number__c = orderRec.Id;
     subRecs[0].Term_Length__c = 0;
     subRecs[0].Term_Length1__c = '0';
     subRecs[0].Main_Package_1__c = pack.id;
     subRecs[0].Main_Package__c = pack.Id;
     subRecs[0].Zuora__SubscriptionStartDate__c = Date.Today();
     subRecs[0].Zuora__SubscriptionEndDate__c = date.Today()+1;
     subRecs[0].Recipient_Contact__c = con.Id;
     subRecs[0].Recipient_Contact_1__c = con.Id;
     subRecs[0].Zuora__Status__c = 'Active';
     subRecs[0].Frequency_1__c = 'Default';
     subRecs[0].Frequency__c = 'Default';
     subRecs[0].Subscription_Type_1__c = 'Publication';
     subRecs[0].Subscription_Type__c = 'Publication';
     
     subRecs[1].Zuora__Account__c = acc.Id;
     subRecs[1].Name = 'TestName';
     subRecs[1].Zuora__CustomerAccount__c = billAcc.id;
     subRecs[1].Order_Number_1__c = orderRec.Id;
     subRecs[1].Order_Number__c = orderRec.Id;
     subRecs[1].Term_Length__c = 0;
     subRecs[1].Term_Length1__c = '0';
     subRecs[1].Main_Package_1__c = pack.id;
     subRecs[1].Main_Package__c = pack.Id;
     subRecs[1].Zuora__SubscriptionStartDate__c = Date.Today();
     subRecs[1].Zuora__SubscriptionEndDate__c = date.Today()+1;
     subRecs[1].Recipient_Contact__c = con1.Id;
     subRecs[1].Recipient_Contact_1__c = con1.Id;
     subRecs[1].Zuora__Status__c = 'Active';
     subRecs[1].Frequency_1__c = 'Default';
     subRecs[1].Frequency__c = 'Default';
     subRecs[1].Subscription_Type_1__c = 'Delivery';
     subRecs[1].Subscription_Type__c = 'Delivery';
     database.insert(subRecs);
     
     List<Subscription_Temp_Stop__c> subtempstopList = new List<Subscription_Temp_Stop__c>(); 
     Subscription_Temp_Stop__c subTemp = new Subscription_Temp_Stop__c();
     subTemp.Temp_Stop__c = temp[0].Id;
     subTemp.Subscription__c = subRecs[0].Id;
     database.insert(subTemp);
     
    Subscription_Temp_Stop__c subTemp2 = new Subscription_Temp_Stop__c();
    subTemp2.Temp_Stop__c = temp[0].Id;
    subTemp2.Subscription__c = subRecs[1].Id;
    database.insert(subTemp2);
    
    subtempstopList.add(subTemp);
    subtempstopList.add(subTemp2);    
     
      list<Subscription_Temp_Stop__c> listtemp = [SELECT Id, Subscription__c, Subscription__r.Recipient_Contact__r.Address__c,
      Subscription__r.Zuora__CustomerAccount__c, Subscription__r.Subscription_Type_1__c, Temp_Stop__c, Temp_Stop__r.Restart_Date__c,
      Subscription__r.Recipient_Contact_1__c, Subscription__r.Recipient_Contact__c, Temp_Stop__r.Temp_Stop_Date__c, Temp_Stop__r.Temp_Stop_Status__c 
      FROM Subscription_Temp_Stop__c WHERE Id =: subTemp.Id]; 
      
      list<Subscription_Temp_Stop__c> listtemp2 = [SELECT Id, Subscription__c, Subscription__r.Recipient_Contact__r.Address__c,
      Subscription__r.Zuora__CustomerAccount__c, Subscription__r.Subscription_Type_1__c, Temp_Stop__c, Temp_Stop__r.Restart_Date__c,
      Subscription__r.Recipient_Contact_1__c, Subscription__r.Recipient_Contact__c, Temp_Stop__r.Temp_Stop_Date__c, Temp_Stop__r.Temp_Stop_Status__c 
      FROM Subscription_Temp_Stop__c WHERE Id =: subTemp2.Id];  
    
    Test.startTest();
            Database.BatchableContext bc;            
            SP_DeliveryChargesBatch_SelectAccs batch = new SP_DeliveryChargesBatch_SelectAccs(AccntSet);
            //String batchId = Database.executeBatch(batch);
            id batchID = database.executeBatch(batch, 200);
            batch.execute(bc, listtemp);
            //batch.execute(bc, listtemp2);
            batch.createUsage(1, subRecs[0]);
            //String schedBatchId = System.scheduleBatch(delCharge, 'testJob', 1);
            //Database.BatchableContext BC;
            //delCharge.finish(BC);
            
            /*BATCH_JOB_SCHEDULER__c batchJobSched = new BATCH_JOB_SCHEDULER__c();
            batchJobSched.SFDC_Job_id__c = batchId;
            batchJobSched.Batch_Run_Date__c = System.today();
            insert batchJobSched;*/
            Test.stopTest();
   
    }
    
    static testmethod void test03(){
    
     Account acc = TestDataFactory.createAccount(1, 'Direct Corporate')[0];
     insert acc;
     
     set<String> AccntSet = new set<string>();
     AccntSet.add('acc.Id');
     
     Zuora__CustomerAccount__c billAcc = TestDataFactory.createBillingAccount(1)[0];
     billAcc.Zuora__DefaultPaymentMethod__c = 'Other'; 
     billAcc.Zuora__Account__c = acc.Id;
     billAcc.Zuora__AccountNumber__c = '123';
     database.insert(billAcc);
    
     Address__c address = TestDataFactory.createAddress(1)[0];
     database.insert(address);
    
     Contact con = TestDataFactory.createContact(1)[0];
     con.AccountId = acc.id;
     con.Address__c = address.Id;
     //con.Billing_Indicator__c = True;
     con.Recipient_Indicator__c = true;
     database.insert(con);
     
     Contact con1 = TestDataFactory.createContact(1)[0];
     con1.AccountId = acc.id;
     con1.Address__c = address.Id;
     //con.Billing_Indicator__c = True;
     con1.Recipient_Indicator__c = true;
     database.insert(con1);     
     
     
            
    
     Package__c pack = TestDataFactory.createPackage(1)[0];
     database.insert(pack);
    
     Order__c orderRec = TestDataFactory.createOrder(1)[0];
     orderRec.Account__c = acc.Id;
     orderRec.Informed_Customer__c = TRUE;
     orderRec.Recipient_Contact__c = con.Id;
     database.insert(orderRec);
    
    /*Case cas = TestDataFactory.createCase(1, 'Temp Stop Subscription')[0];
    cas.Order__c = orderRec.Id;
    database.insert(cas);*/
    
     List<Temp_Stop__c> temp = TestDataFactory.createTempStop(1);
     temp[0].Restart_Date__c = referenceDate.addMonths(2).toStartofMonth().addDays(-1);
     temp[0].Temp_Stop_Date__c = referenceDate.toStartOfMonth();
     temp[0].Qty__c = 3;
     temp[0].Cancelled__c  = false;
    
     /*temp[1].Restart_Date__c = date.newInstance(referenceDate.year(), 12, 31);
     temp[1].Temp_Stop_Date__c = date.newInstance(referenceDate.year()-1, 1, 1);
     temp[1].Qty__c = 3;
     temp[1].Cancelled__c  = false;*/
     database.insert(temp);
    
     system.assertEquals(null, temp[0].Temp_Stop_Status__c);

     zqu__ZProduct__c zProduct = TestDataFactory.createZProduct(1)[0];
     zProduct.ProductSubType__c = 'Newspaper';
     zProduct.ProductPlatform__c = 'Print';
     database.insert(zProduct);
        
     zqu__ProductRatePlan__c prdRatePlan = TestDataFactory.createProductRatePlan(1)[0];
     prdRatePlan.zqu__ZProduct__c = zProduct.Id;
     database.insert(prdRatePlan);
        
     zqu__ProductRatePlanCharge__c prpc = TestDataFactory.createProductRatePlanCharge(1)[0];
     prpc.zqu__ProductRatePlan__c = prdRatePlan.Id;
     database.insert(prpc);
        
     List<Package_Item__c> pItems = TestDataFactory.createPackageItem(2, 'Base Product');
     for (Package_Item__c pItem : pItems) {
     pItem.Package__c = pack.Id;
     pItem.Product_Rate_Plan__c = prdRatePlan.Id;
     }
     database.insert(pItems);     
     
     List<Zuora__Subscription__c> subRecs = TestDataFactory.createSubscription(2);
     subRecs[0].Zuora__Account__c = acc.Id;
     subRecs[0].Name = 'TestName';
     subRecs[0].Zuora__CustomerAccount__c = billAcc.id;
     subRecs[0].Order_Number_1__c = orderRec.Id;
     subRecs[0].Order_Number__c = orderRec.Id;
     subRecs[0].Term_Length__c = 0;
     subRecs[0].Term_Length1__c = '0';
     subRecs[0].Main_Package_1__c = pack.id;
     subRecs[0].Main_Package__c = pack.Id;
     subRecs[0].Zuora__SubscriptionStartDate__c = Date.Today();
     subRecs[0].Zuora__SubscriptionEndDate__c = date.Today()+1;
     subRecs[0].Recipient_Contact__c = con.Id;
     subRecs[0].Recipient_Contact_1__c = con.Id;
     subRecs[0].Zuora__Status__c = 'Active';
     subRecs[0].Frequency_1__c = 'Default';
     subRecs[0].Frequency__c = 'Default';
     subRecs[0].Subscription_Type_1__c = 'Publication';
     subRecs[0].Subscription_Type__c = 'Publication';
     
     subRecs[1].Zuora__Account__c = acc.Id;
     subRecs[1].Name = 'TestName';
     subRecs[1].Zuora__CustomerAccount__c = billAcc.id;
     subRecs[1].Order_Number_1__c = orderRec.Id;
     subRecs[1].Order_Number__c = orderRec.Id;
     subRecs[1].Term_Length__c = 0;
     subRecs[1].Term_Length1__c = '0';
     subRecs[1].Main_Package_1__c = pack.id;
     subRecs[1].Main_Package__c = pack.Id;
     subRecs[1].Zuora__SubscriptionStartDate__c = Date.Today();
     subRecs[1].Zuora__SubscriptionEndDate__c = date.Today()+1;
     subRecs[1].Recipient_Contact__c = con1.Id;
     subRecs[1].Recipient_Contact_1__c = con1.Id;
     subRecs[1].Zuora__Status__c = 'Active';
     subRecs[1].Frequency_1__c = 'Default';
     subRecs[1].Frequency__c = 'Default';
     subRecs[1].Subscription_Type_1__c = 'Delivery';
     subRecs[1].Subscription_Type__c = 'Delivery';
     database.insert(subRecs);
     
     List<Subscription_Temp_Stop__c> subtempstopList = new List<Subscription_Temp_Stop__c>(); 
     Subscription_Temp_Stop__c subTemp = new Subscription_Temp_Stop__c();
     subTemp.Temp_Stop__c = temp[0].Id;
     subTemp.Subscription__c = subRecs[0].Id;
     database.insert(subTemp);
     
    Subscription_Temp_Stop__c subTemp2 = new Subscription_Temp_Stop__c();
    subTemp2.Temp_Stop__c = temp[0].Id;
    subTemp2.Subscription__c = subRecs[1].Id;
    database.insert(subTemp2);
    
    subtempstopList.add(subTemp);
    subtempstopList.add(subTemp2);    
     
      list<Subscription_Temp_Stop__c> listtemp = [SELECT Id, Subscription__c, Subscription__r.Recipient_Contact__r.Address__c,
      Subscription__r.Zuora__CustomerAccount__c, Subscription__r.Subscription_Type_1__c, Temp_Stop__c, Temp_Stop__r.Restart_Date__c,
      Subscription__r.Recipient_Contact_1__c, Subscription__r.Recipient_Contact__c, Temp_Stop__r.Temp_Stop_Date__c, Temp_Stop__r.Temp_Stop_Status__c 
      FROM Subscription_Temp_Stop__c WHERE Id =: subTemp.Id]; 
      
      list<Subscription_Temp_Stop__c> listtemp2 = [SELECT Id, Subscription__c, Subscription__r.Recipient_Contact__r.Address__c,
      Subscription__r.Zuora__CustomerAccount__c, Subscription__r.Subscription_Type_1__c, Temp_Stop__c, Temp_Stop__r.Restart_Date__c,
      Subscription__r.Recipient_Contact_1__c, Subscription__r.Recipient_Contact__c, Temp_Stop__r.Temp_Stop_Date__c, Temp_Stop__r.Temp_Stop_Status__c 
      FROM Subscription_Temp_Stop__c WHERE Id =: subTemp2.Id];  
    
    Test.startTest();
            Database.BatchableContext bc;            
            SP_DeliveryChargesBatch_SelectAccs batch = new SP_DeliveryChargesBatch_SelectAccs(AccntSet);
            //String batchId = Database.executeBatch(batch);
            id batchID = database.executeBatch(batch, 200);
            batch.execute(bc, listtemp);
            //batch.execute(bc, listtemp2);
            batch.createUsage(1, subRecs[0]);
            //String schedBatchId = System.scheduleBatch(delCharge, 'testJob', 1);
            //Database.BatchableContext BC;
            //delCharge.finish(BC);
            
            /*BATCH_JOB_SCHEDULER__c batchJobSched = new BATCH_JOB_SCHEDULER__c();
            batchJobSched.SFDC_Job_id__c = batchId;
            batchJobSched.Batch_Run_Date__c = System.today();
            insert batchJobSched;*/
            Test.stopTest();
   
    }
    
    
  }