src/objects/Address_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Void</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Address Assignment</label>
    <nameField>
        <displayFormat>Address_Assign-{0000}</displayFormat>
        <label>Address Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>Account Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <description>ARMS field</description>
        <label>ARMS_Customer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>This field is used to amend existing subscription.</description>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provisioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Vendor Assignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Void</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>isWaive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isWaive?</label>
        <type>Checkbox</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DataPurgeBatchTest.cls
/**
 * Class Name: <DataPurgeBatchTest>
 * @author: <Flores, Emmanuel>
 * Date: <7/2/2015>
 * Requirement/Project Name: <SPH>
 * @description<Test Class for DataPurgeBatch>
 */
@isTest (seeAllData = TRUE)
private class DataPurgeBatchTest {
    
    /*static testmethod void unitTest() {
        
        List<Address_Assignment__c> aa1 = new List<Address_Assignment__c>();
        for(Address_Assignment__c addressAss : aa1){
                addressAss.Effective_Date__c = date.today();
                addressAss.Status__c = 'Active';
                addressAss.End_Date__c =  date.today().addDays(2);
                addressAss.Active__c = False;
        }
        insert aa1;
        
        String query = 'SELECT Account_Name__c, Account_Number__c, Customer_Name__c FROM Order__c WHERE isWaive__c =TRUE';
        DataPurgeBatch batch = new DataPurgeBatch(query);
        //ID batchprocessid = Database.executeBatch(batch,10);
        //System.assertNotEquals(null, batchprocessid);
        Database.BatchableContext bc;
        batch.start(bc);
        try{
        batch.execute(bc, aa1);
        batch.finish(bc);
        }catch(exception e){
            
        }
    }
    */
    
    static testmethod void unitTest2() {

        String query = 'SELECT Account_Name__c, Account_Number__c, Customer_Name__c FROM Order__c WHERE isWaive__c =TRUE';
        DataPurgeBatch batch = new DataPurgeBatch(query);
        ID batchprocessid = Database.executeBatch(batch,10);
        //System.assertNotEquals(null, batchprocessid);
        Database.BatchableContext bc;
        batch.start(bc);
    }
 }