src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address_1__c</fullName>
        <label>Address 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_2__c</fullName>
        <label>Address 2</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_3__c</fullName>
        <label>Address 3</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_4__c</fullName>
        <label>Address 4</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Airline_Number__c</fullName>
        <formula>Packing_Code__r.Airline__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Airline Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Block_House_Number__c</fullName>
        <description>This field will be displayed if record type field is Local.
Read-only. Auto-populated by the system based on Postal Code</description>
        <label>House/Block Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Building_Name__c</fullName>
        <description>This field will be displayed if record type field is Local. 
Read-only. Auto-populated by the system based on Postal Code</description>
        <formula>Postal_Code__r.Building_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Building Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>City Code</label>
        <referenceTo>City__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company Code</label>
        <referenceTo>SPH_Company__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <formula>Company_Code__r.Company_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Company Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Name__c</fullName>
        <formula>Country__r.Country_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>SPH_Department__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Division Code</label>
        <referenceTo>SPH_Division__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flight_Number_1__c</fullName>
        <formula>City__r.Flight_Number_1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Flight Number 1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Number_2__c</fullName>
        <formula>City__r.Flight_Number_2__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Flight Number 2</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level_Number__c</fullName>
        <description>This field will be displayed if record type field is Local.
User specified</description>
        <label>Level Number</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code_Text__c</fullName>
        <formula>Postal_Code__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Postal Code Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be displayed if record type field is Local.
User specified</description>
        <label>Postal Code</label>
        <referenceTo>Singpost_Address__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Section Code</label>
        <referenceTo>SPH_Section__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Street_Name__c</fullName>
        <description>This field will be displayed if record type field is Local. 
Read-only. Auto-populated by the system based on Postal Code</description>
        <formula>Postal_Code__r.Street_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Street Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <description>This field will be displayed if record type field is Local.
User specified</description>
        <label>Unit Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <recordTypes>
        <fullName>Airline</fullName>
        <active>true</active>
        <description>For Airline Subscriber</description>
        <label>Airline</label>
    </recordTypes>
    <recordTypes>
        <fullName>Internal</fullName>
        <active>true</active>
        <description>For Internal Subscribers</description>
        <label>Internal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Local</fullName>
        <active>true</active>
        <description>For Local Subscribers</description>
        <label>Local</label>
    </recordTypes>
    <recordTypes>
        <fullName>Overseas</fullName>
        <active>true</active>
        <description>For Overseas Subscribers</description>
        <label>Overseas</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/BA_INT_DATA_POOL__c.object
<CustomObject>
    <description>custom object for batch integration purposes.
the object act as a single repository for the entire batch data set across all interfaces.
{Job_ID, Record_Type, Group_ID, Sort_Order, Data_in_CSV_format}</description>
    <fields>
        <fullName>export_data__c</fullName>
        <description>the comma separated values fetched fro SFDC per batch job</description>
        <label>export data</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>group_id__c</fullName>
        <description>the unique identifier for the record (eg account_id or invoice_id)</description>
        <label>group id</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>insert_time__c</fullName>
        <description>the start time for the batch job</description>
        <label>insertion time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>job_id__c</fullName>
        <description>job name for the scheduled batch job</description>
        <label>job_id</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>run_for_date__c</fullName>
        <description>EOD date for which the batch job was run</description>
        <label>run for date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>BA_INT_DATA_POOL</label>
    <nameField>
        <label>BA_INT_DATA_POOL Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA_INT_DATA_POOL</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/City__c.object
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Attn. To Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HomePhone__c</fullName>
        <description>User specified</description>
        <label>Home Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Mobile_Number_2__c</fullName>
        <label>Mobile Number 2</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Mobile_Number__c</fullName>
        <label>Mobile Number 1</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Street_Name__c</fullName>
        <formula>Address__r.Street_Name__c</formula>
        <label>Street Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <formula>Address__r.Unit_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unit Number</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Singpost_Address__c.object
<CustomObject>
    <label>Singpost Address</label>
    <nameField>
        <label>Postal Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Singpost Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPH_Company__c.object
<CustomObject>
    <label>SPH Company</label>
    <nameField>
        <label>SPH Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPH Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPH_Department__c.object
<CustomObject>
    <label>SPH Department</label>
    <nameField>
        <label>SPH Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPH Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPH_Division__c.object
<CustomObject>
    <label>SPH Division</label>
    <nameField>
        <label>SPH Division Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPH Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPH_Section__c.object
<CustomObject>
    <label>SPH Section</label>
    <nameField>
        <label>SPH Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPH Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src orig/classes/BT_AB_PPS056DX_EshopRegistrationRefund.cls
/*
 * Class Name: BT_AB_PPS056DX_EshopRegistrationRefund 
 * @author: Kevin H. Evasco
 * Date: 08/26/2014
 * Project/Requirement: SPH Integration - PPS056DX Interface
 * @description This class populates BA_INT_DATA_POOL__c for PPS056DX batch job. Used together with BT_AS_PPS056DX_EshopRegistrationRefund Schedulable
 * 
 * History: 08/26/2014 Kevin Evasco Created Skeletal Apex Batchable
 * History: 09/30/2014 Renino Niefes Added code implementation
 * History: 11/03/2014 Renino Niefes changed criteria in soql (new refunds only)
 */


global class BT_AB_PPS056DX_EshopRegistrationRefund implements Database.Batchable<sObject>,Database.AllowsCallouts
{
    // SOQL Query in getting the interface primary object
    // TO-DO: Update query based on requirements
    //global final String query = 'SELECT Id FROM BA_INT_DATA_POOL__c WHERE Name = \'PPS056DX Sample Source\'';    
    global final String interfaceId = 'PPS056DX';       
  
    /* @description 
     * 
     * @param BatchableContext which is a predefined parameter
     * @return Database.QueryLocator
     */ 
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        List<BA_INT_DATA_POOL__c> resultList = [SELECT Id FROM BA_INT_DATA_POOL__c WHERE Name = :interfaceId];
        delete resultList; 
        //START HotFix 27-July-2015 Added by Nitin - Updated Query
    
        String query = 'SELECT ';
            query += '    Zuora__BillingAccount__r.Billing_Contact__r.name, ';
            query += '    Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Country_Name__c, ';
            query += '    Zuora__BillingAccount__r.Billing_Contact__r.Address__r.RecordType.developername, ';
            //local addresses
            query += '    Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Unit_Number__c, ';
            query += '    Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Level_Number__c, ';
            query += '    Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Street_Name__c, ';
            query += '    Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Building_Name__c, ';
            query += '    Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Block_House_Number__c, ';
            query += '    Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Postal_Code_Text__c, ';
            query += '    Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Postal_Code__r.Service_Number__c, ';
            query += '    Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Postal_Code__r.name, ';
            //overseas
            query += '    Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Address_1__c, ';
            query += '    Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Address_2__c, ';
            query += '    Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Address_3__c, ';
            query += '    Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Address_4__c, ';
            //internal
            query += '    Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Section_Code__r.Section_Name__c, ';
            query += '    Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Department__r.Department_Name__c, ';
            query += '    Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Division_Code__r.Department_Name__c, ';
            query += '    Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Company_Code__r.Company_Name__c, ';
            query += '    Zuora__BillingAccount__r.Billing_Contact__r.Address__r.City__r.City_Name__c, ';
            //airlines
            query += '    Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Airline_Number__c, ';
            query += '    Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Flight_Number_1__c, ';
            query += '    Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Flight_Number_2__c, ';
            query += '    Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Country__r.code__c, ';
            
            query += '    Payee__c, ';
            query += '    Mail_Address_Line_1__c, ';
            query += '    Mail_Address_Line_2__c, ';
            query += '    Mail_Address_Line_3__c, ';
            query += '    Mail_Address_Line_4__c, ';
            query += '    Telephone__c, ';
            query += '    Bank_Code__c, ';
            query += '    Bank_Account_Number__c, ';
            query += '    Payment_Amount__c, ';
            query += '    Clearing_Country_Code__c, ';
            query += '    Payment_Type__c, ';
            query += '    Customer_A_C_Type__c, ';
            query += '    Status__c, ';
            query += '    Zuora__Amount__c, ';
            query += '    Zuora__BillingAccount__r.Id, ';
            query += '    Zuora__Account__r.Account_Auto_Number__c, ';
            query += '    Zuora__Account__r.Name, ';
            
            //contact details
            query += '    Zuora__BillingAccount__r.Billing_Contact__r.Mobile_Number__c, ';
            query += '    Zuora__BillingAccount__r.Billing_Contact__r.Mobile_Number_2__c, ';
            query += '    Zuora__BillingAccount__r.Billing_Contact__r.HomePhone__c ';  
            query += ' FROM ';
            query += '    Zuora__Refund__c';
            query += ' WHERE ';
            query += '    (Status__c = \'new\' OR Status__c = null)';  //replace this with 'new' later on
            query += '    AND Zuora__RefundMethodType__c = \'Check\'';
            //query += '    AND createdDate = TODAY';   
        //End HotFix 27-July-2015 Added by Nitin - Updated Query
        return Database.getQueryLocator(query);
    }
    
    /* @description Executes the business logic and populates BA_INT_DATA_POOL__c with new records based on the interface requirements.
     * 
     * @param BC a BatchableContext which is a predefined parameter
     * @param scope a list of sObjects from the initial database query
     * @return void
     */ 
    global void execute(Database.BatchableContext BC, List<sObject> scope)
    {       
        List<BA_INT_DATA_POOL__c> datapoolList = new List<BA_INT_DATA_POOL__c>();
        List<Zuora__Refund__c> refundList = new List<Zuora__Refund__c>();
        for(sObject record : scope)
        {  
            Zuora__Refund__c refundRecord = (Zuora__Refund__c)record;
            
            String exportData = '';    
            //START HotFix 27-July-2015 Added by Nitin - Updated exportData
            exportData += refundRecord.Zuora__Account__r.name + ',';
            
            if(refundRecord.Zuora__BillingAccount__r.Billing_Contact__r.Address__r.recordType.developerName == 'Local'){
                String poBox = refundRecord.Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Postal_Code__r.Service_Number__c;
                String unitNo = refundRecord.Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Unit_Number__c;
                String levelNo = refundRecord.Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Level_Number__c;
                String houseNo = refundRecord.Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Block_House_Number__c;
                String buildingName = refundRecord.Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Building_Name__c;
                String street = refundRecord.Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Street_Name__c;
                String country = refundRecord.Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Country_Name__c;
                String pCode = refundRecord.Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Postal_Code__r.name;
                 //KRITHIKA D UD-1829 START Address_line_1 has to be mandatory D-3567 
                List<String> AdressLine = new List<String>();  
                String Address_line_1 = (poBox == null ? '' : poBox) + (houseNo == null ? '' : houseNo) + ' ' + (street == null ? '' : street)  ;
                String Address_line_2 = (levelNo == null ? '' : levelNo) + ' ' + (unitNo == null ? '' : unitNo);
                String Address_line_3 = (buildingName == null ? '' : buildingName) ;
                String Address_line_4 = (country == null ? '' : country)  + ' ' + (pCode == null ? '' : pCode) ;
                
                if(!String.isBlank(Address_line_1)){
                    AdressLine.add((Address_line_1.contains(',') ? Address_line_1.replace(',','') : Address_line_1));     
                }
                if(!String.isBlank(Address_line_2)){
                    AdressLine.add((Address_line_2.contains(',') ? Address_line_2.replace(',','') : Address_line_2));     
                }
                if(!String.isBlank(Address_line_3)){
                    AdressLine.add((Address_line_3.contains(',') ? Address_line_3.replace(',','') : Address_line_3));     
                }
                if(!String.isBlank(Address_line_4)){
                    AdressLine.add((Address_line_4.contains(',') ? Address_line_4.replace(',','') : Address_line_4));     
                }
                if(String.isBlank(Address_line_1) && String.isBlank(Address_line_2) && String.isBlank(Address_line_3) && String.isBlank(Address_line_4)){
                    system.debug('Address is blank');
                    refundRecord.Status__c = 'failed';
                    continue;
                }
                system.debug('AddressLinesize=========>'+AdressLine.size());
                if(AdressLine.size() != 4){
                    if(AdressLine.size() == 0){
                        system.debug('AddressLinesizezero=========>'+AdressLine.size());
                        refundRecord.Status__c = 'failed';
                        continue;
                    }
                    if(AdressLine.size() == 1){
                        system.debug('AddressLinesizeone=========>'+AdressLine.size());
                        AdressLine.add('');
                        AdressLine.add('');
                        AdressLine.add('');
                    }
                    if(AdressLine.size() == 2){
                        system.debug('AddressLinesizetwo=========>'+AdressLine.size());
                        AdressLine.add('');
                        AdressLine.add('');
                    }
                    if(AdressLine.size() == 3){
                        system.debug('AddressLinesizethree=========>'+AdressLine.size());
                        AdressLine.add('');
                    }
                }
                system.debug('AddressLinesize=========>'+AdressLine.size());
                for(String tempAdd :AdressLine) {
                    exportData += tempAdd + ',';
                    system.debug('adding comma u stupid ');
                     system.debug('expotdatainsideloop================>'+exportData ); 
                }   
                system.debug('expotdata================>'+exportData ); 
                    //KRITHIKA D UD-1829  Address_line_1 has to be mandatory D-3567  
            }
            
            if(refundRecord.Zuora__BillingAccount__r.Billing_Contact__r.Address__r.recordType.developerName == 'Overseas'){
                String addr1 = refundRecord.Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Address_1__c;
                String addr2 = refundRecord.Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Address_2__c;
                String addr3 = refundRecord.Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Address_3__c;
                String addr4 = refundRecord.Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Address_4__c;        
            
                exportData += (addr1 == null? '' :addr1)  + ',';
                exportData += (addr2 == null? '' :addr2)  + ',';
                exportData += (addr3 == null? '' :addr3)  + ',';
                exportData += (addr4 == null? '' :addr4)  + ',';
            }
            
            if(refundRecord.Zuora__BillingAccount__r.Billing_Contact__r.Address__r.recordType.developerName == 'Internal'){
                String sectionNo = refundRecord.Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Section_Code__r.Section_Name__c;
                String deptNo = refundRecord.Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Department__r.Department_Name__c;
                String div = refundRecord.Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Division_Code__r.Department_Name__c;
                String cCode = refundRecord.Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Company_Code__r.Company_Name__c;
                String countryCode = refundRecord.Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Country__r.code__c;
            
                exportData += (sectionNo == null ? '' : sectionNo)  + ',';
                exportData += (deptNo == null ? '' : deptNo)  + ',';
                exportData += (div == null ? '' : div)  + ',';
                exportData += (cCode == null ? '' : cCode) + ' ' + (countryCode == null ? '' : countryCode)  + ',';
            }
            
            if(refundRecord.Zuora__BillingAccount__r.Billing_Contact__r.Address__r.recordType.developerName == 'Airline'){
                String fltNo1 = refundRecord.Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Flight_Number_1__c;
                String fltNo2 = refundRecord.Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Flight_Number_2__c;
                String airNo = refundRecord.Zuora__BillingAccount__r.Billing_Contact__r.Address__r.Airline_Number__c;
                String city = refundRecord.Zuora__BillingAccount__r.Billing_Contact__r.Address__r.City__r.City_Name__c ;
                
                exportData +=  (fltNo1 == null ? '' : fltNo1) + ',';
                exportData += (fltNo2 == null ? '' : fltNo2)  + ',';
                exportData += (airNo == null ? '' : airNo)  + ',';
                exportData += (city == null ? '' : city)  + ',';
            }
            //KRITHIKA DHARMARAJAN UD-1829 START 26/08/2015 D-3567
            if(refundRecord.Zuora__BillingAccount__r.Billing_Contact__r.Address__r.recordType.developerName == null){ 
              // exportData += ',' + ',' + ',' + ',' ;
              refundRecord.Status__c = 'failed';
              continue;
            }
            //KRITHIKA DHARMARAJAN UD-1829 END 26/08/2015 D-3567
            exportData += refundRecord.Zuora__Account__r.name + ',';
            exportData += refundRecord.Mail_Address_Line_1__c + ',';
            exportData += refundRecord.Mail_Address_Line_2__c + ',';
            exportData += refundRecord.Mail_Address_Line_3__c + ',';
            exportData += refundRecord.Mail_Address_Line_4__c + ',';
            exportData += getTelephoneNumber(refundRecord) + ',';
            exportData += refundRecord.Bank_Code__c + ',';
            exportData += refundRecord.Bank_Account_Number__c + ',';
            exportData += getPaymentAmount(refundRecord) + ',';
            exportData += refundRecord.Clearing_Country_Code__c + ',';
            exportData += refundRecord.Payment_Type__c + ',';
            exportData += refundRecord.Zuora__Account__r.Account_Auto_Number__c;    
            //End HotFix 27-July-2015 Added by Nitin - Updated exportData
            
            refundRecord.Status__c = 'issued';
            refundList.add(refundRecord);
            
           // Prepare Data Pool information here
            BA_INT_DATA_POOL__c datapoolRecord = new BA_INT_DATA_POOL__c();
            datapoolRecord.Name = interfaceId;
            datapoolRecord.job_id__c = '1';
            datapoolRecord.group_id__c = 'Detail';
            datapoolRecord.run_for_date__c = Date.today();      
            datapoolRecord.insert_time__c = DateTime.now(); 
            datapoolRecord.export_data__c = exportData;
            
            datapoolList.add(datapoolRecord);
        }
  
        // Set the database savepoint. In case DML Operation fails, use this savepoint for rollback.  
        Savepoint savepointBeforeDML = Database.setSavepoint();
        try
        {
            insert datapoolList;
            update refundList;
        }
        catch(Exception e)
        {       
            // Execute Database Rollback 
            Database.rollback(savepointBeforeDML);
            System.debug('BT_AB_PPS056DX_EshopRegistrationRefund insert operation failed.');
        }
    }
    
    //Start HotFix 27-July-2015 Added by Nitin - Implemented getTelephoneNumber and getPaymentAmount methods    
    private String getTelephoneNumber(Zuora__Refund__c zrRecord) {
        String zResult = '';
        String zMobile = (String) zrRecord.Zuora__BillingAccount__r.Billing_Contact__r.Mobile_Number__c;
        String zHandphoneNumber = (String) zrRecord.Zuora__BillingAccount__r.Billing_Contact__r.Mobile_Number_2__c;
        String zHomeNumber = (String) zrRecord.Zuora__BillingAccount__r.Billing_Contact__r.HomePhone__c;
        
        
        if (zMobile != null && zMobile.length() > 0) {
            zResult = zMobile;
        } else if (zHandphoneNumber != null && zHandphoneNumber.length() > 0) {
            zResult = zHandphoneNumber;
        } else if (zHomeNumber != null && zHomeNumber.length() > 0) {
            zResult = zHomeNumber;
        }         
        return zResult;
    }
    
    private String getPaymentAmount(Zuora__Refund__c zrRecord) { 
        String zResult = '';
        Decimal pAmount = (Decimal) zrRecord.Payment_Amount__c;
        Decimal zAmount = (Decimal) zrRecord.Zuora__Amount__c;
        
        if (pAmount != null && pAmount >= 0) {
            zResult = String.valueOf(pAmount);
        } else if (zAmount != null && zAmount >= 0) {
            zResult = String.valueOf(zAmount);
        }
        
        return zResult; 
    }
    //End HotFix 27-July-2015 Added by Nitin - Implemented getTelephoneNumber and getPaymentAmount methods
    
    /*
     * @description A method which executes the final actions of the class.
     * 
     * @param BC a BatchableContext which is a predefined parameter
     * @return void
     */ 
    global void finish(Database.BatchableContext BC)
    {
          //Get the batch run date
        String batchRunDate = BT_AU_BATCHRUNREQUEST_UpdateInfo.getBatchRunDate(interfaceId);            
        Date myDate = DateUtility.convertDate(batchRunDate,'-','YMD');
                
        //System.debug('*********************** inside final'+ this.query);
        BatchServiceFacade a1F = new BatchServiceFacade();
        BatchServiceRequestVO serviceRequestVO = new BatchServiceRequestVO();
        serviceRequestVO.setJobStatus(0);
        serviceRequestVO.setJobID(interfaceId);
        serviceRequestVO.setJobDate(myDate);
        System.debug('################ before');
        a1F.delegateBatchCall(serviceRequestVO);
        System.debug('################ after');        

        //Update Batch Run Request's End Time
        BT_AU_BATCHRUNREQUEST_UpdateInfo.updateEndTime(interfaceId);
    }
}