src/objects/BA_INT_DATA_POOL__c.object
<CustomObject>
    <description>custom object for batch integration purposes.
the object act as a single repository for the entire batch data set across all interfaces.
{Job_ID, Record_Type, Group_ID, Sort_Order, Data_in_CSV_format}</description>
    <label>BA_INT_DATA_POOL</label>
    <nameField>
        <label>BA_INT_DATA_POOL Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA_INT_DATA_POOL</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BatchInterface_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Batch Interface Settings</label>
</CustomObject>

src/objects/BT_CO_Batch_Run_Request__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Run_Date__c</fullName>
        <label>Batch Run Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interface_ID__c</fullName>
        <label>Interface ID</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>BT_CO_Batch_Run_Request</label>
    <nameField>
        <displayFormat>BRR-{0000000000}</displayFormat>
        <label>Batch Run Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT_CO_Batch_Run_Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BT_INT_PARAM_CONFIG__c.object
<CustomObject>
    <description>custom object to dynamically generate query for batch interfaces</description>
    <fields>
        <fullName>field_name__c</fullName>
        <description>field to be pulled from the sObject</description>
        <label>field_name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>field_sequence__c</fullName>
        <description>sequence in which the field should appear in the query</description>
        <label>field_sequence</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>from_object__c</fullName>
        <description>the object from which the field data needs to be pulled</description>
        <label>from_object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>interface_name__c</fullName>
        <label>interface_name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>postOpFieldName__c</fullName>
        <label>postOpFieldName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>BT_INT_PARAM_CONFIG</label>
    <nameField>
        <label>name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BT_INT_PARAM_CONFIGS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Package__c.object
<CustomObject>
    <fields>
        <fullName>Channel_Direct__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Channel: Direct</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Channel_E_shop_overseas__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Channel: E-shop (overseas)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Channel_E_shop_private__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Channel: E-shop (private)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Channel_E_shop_public__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Channel: E-shop (public)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Effective_End_Date__c</fullName>
        <label>Effective End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Start_Date__c</fullName>
        <label>Effective Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Package_Code__c</fullName>
        <externalId>true</externalId>
        <label>Package Code</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Package_Type__c</fullName>
        <label>Package Type</label>
        <picklist>
            <picklistValues>
                <fullName>Add On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Base</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bundle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grace Period</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subscription_Period__c</fullName>
        <label>Subscription Period</label>
        <picklist>
            <controllingField>Subscription_Type__c</controllingField>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subscription_Type__c</fullName>
        <label>Subscription Type</label>
        <picklist>
            <picklistValues>
                <fullName>Termed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evergreen</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Package_Item__c.object
<CustomObject>
    <fields>
        <fullName>Package__c</fullName>
        <description>The package name for which the package item is being created will be displayed.</description>
        <label>Package</label>
        <referenceTo>Package__c</referenceTo>
        <relationshipLabel>Package Items</relationshipLabel>
        <relationshipName>Package_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Family</label>
        <referenceTo>Product_Family__c</referenceTo>
        <relationshipLabel>Package Items</relationshipLabel>
        <relationshipName>Package_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Rate Plan</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>zqu__ProductRatePlan__c.zqu__Deleted__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>Package Items</relationshipLabel>
        <relationshipName>Package_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Package Item</label>
    <nameField>
        <label>Package Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Package Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product_Family__c.object
<CustomObject>
    <fields>
        <fullName>Product_Family__c</fullName>
        <inlineHelpText>Product Family Code</inlineHelpText>
        <label>Product Family</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Product Family</label>
    <nameField>
        <displayFormat>PF-{00000000}</displayFormat>
        <label>Product Family Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Families</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product_Publication__c.object
<CustomObject>
    <fields>
        <fullName>Publication_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Product Publications</relationshipLabel>
        <relationshipName>Product_Publications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Publication</label>
    <nameField>
        <displayFormat>PPUB-{00000000}</displayFormat>
        <label>Product Publication Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BT_AB_ESH1003DX_ESHOPPackageTest.cls
@isTest
private class BT_AB_ESH1003DX_ESHOPPackageTest {  

/*
* Class Name: BT_AB_ESH1003DX_ESHOPPackageTest
* @author: Accenture IDC : Rashmi.G.P
* Requirement/Project Name: SPH
* @description: BT_AB_ESH1003DX_ESHOPPackage
*/

 public static List<BA_INT_DATA_POOL__c> blist = new List<BA_INT_DATA_POOL__c>(); 
 
    static testMethod void unitTest1() { 
       
       
        bt_int_param_config__c paramConfig = new bt_int_param_config__c();
        paramConfig.field_name__c = 'Publication_Code__c';
        paramConfig.from_object__c = 'Product_Publication__c';
        paramConfig.interface_name__c = 'Test';
        paramConfig.field_sequence__c = 10;
        paramConfig.postOpFieldName__c = 'Field Name';
        database.insert(paramConfig);
        String interfaceName = 'ESH1003DX';
        List<BT_INT_PARAM_CONFIG__c> bipcList = new List<BT_INT_PARAM_CONFIG__c>();
        List<String> fieldName = new List<String> { 'Package__r.Package_Code__c',
                                                    'Product_Rate_Plan__r.zqu__ZProduct__c',
                                                    'Package__r.name',
                                                    'package__r.Subscription_Period__c',
                                                    'Product_Rate_Plan__r.zqu__Description__c',
                                                    'package__r.Package_Type__c',
                                                    'package__r.Effective_Start_Date__c',
                                                    'package__r.Effective_End_Date__c',
                                                    'createddate',
                                                    'lastmodifiedby.name',
                                                    'createdby.name',
                                                    'lastmodifieddate',
                                                    'Product_Rate_Plan__r.SubscriptionFrequency__c',
                                                    'Package__r.Channel_E_shop_public__c',
                                                    'Package__r.Channel_E_shop_overseas__c',
                                                    'Package__r.Channel_E_shop_private__c',
                                                    'Package__r.Channel_Direct__c' 
                                                     };
                                                    
        List<String> postOpName= new List<String> { 'Package_Code__c',
                                                    'zqu__ZProduct__c',
                                                    'name',
                                                    'Subscription_Period__c',
                                                    'zqu__Description__c',
                                                    'Package_Type__c',
                                                    'Effective_Start_Date__c',
                                                    'Effective_End_Date__c',
                                                    'lastmodifieddate',
                                                    'createddate',
                                                    'name',
                                                    'name',
                                                    'SubscriptionFrequency__c',
                                                    'Channel_E_shop_public__c',
                                                    'Channel_E_shop_overseas__c',
                                                    'Channel_E_shop_private__c',                                                    
                                                    'Channel_Direct__c'
                                                    };
        
        for (Integer i=0; i<fieldName.size(); i++) {
        
            BT_INT_PARAM_CONFIG__c bipc = new BT_INT_PARAM_CONFIG__c();
            bipc.From_Object__c = 'Package_Item__c';
            bipc.field_sequence__c = i+1;
            bipc.interface_Name__c = interfaceName;
            bipc.postopfieldname__c = postOpName[i];
            bipc.name = 'ESHOP000'+i;
            bipc.field_name__c = fieldName[i];
           
            bipcList.add(bipc);
        }
        
        insert bipcList;
        
        BT_CO_Batch_Run_Request__c brr = new BT_CO_Batch_Run_Request__c();
        brr.interface_id__c='ESH1001DX';
        brr.batch_run_date__c = Date.today();
        insert brr;
        
        BatchInterface_Settings__c bis = new BatchInterface_Settings__c();
        bis.name='Endpoint Delegator';
        bis.value__c='http://localhost';
        insert bis;
        
        Package__c p = new Package__c();
        p.Package_Type__c = 'Add On';
        p.Package_Code__c = 'RashPc';
        p.Subscription_Period__c= '1';
        p.Effective_Start_Date__c = Date.Today();
        p.Effective_End_Date__c = Date.Today();
        p.Channel_E_shop_public__c = true;
        p.Channel_E_shop_overseas__c = true;
        p.Channel_E_shop_private__c = true;
        p.Channel_Direct__c = true;
        p.Subscription_Type__c = 'Termed';
        insert p;
        
        zqu__ZProduct__c zpr = new zqu__ZProduct__c();
        zpr.ProductCode__c = 'RashmiPrd';
        zpr.zqu__SKU__c='XYZ';
        zpr.zqu__ZuoraId__c='1234';
        insert zpr;
    
        zqu__ProductRatePlan__c zprp = new zqu__ProductRatePlan__c();
        zprp.zqu__ZProduct__c = zpr.id;
        zprp.zqu__Description__c = 'ABCD';
        zprp.SubscriptionFrequency__c = '0';
        zprp.RatePlanCode__c = 'RPrd';
        zprp.RatePlanType__c = 'Bill Plan';
        zprp.zqu__ZuoraId__c = '1234';
        insert zprp;
     
        Product_Family__c pf = new Product_Family__c();
        pf.Product_Family__c = 'profly';
        insert pf;
        
        list<Package__c> lst = [select id from Package__c limit 1];
        list<zqu__ProductRatePlan__c> lst2 = [select id from zqu__ProductRatePlan__c limit 1];
        list<Product_Family__c> lst3 = [select id from Product_Family__c limit 1];
        Package_Item__c pi = new Package_Item__c();
        pi.Package__c = lst[0].id;
        pi.Product_Rate_Plan__c = lst2[0].id;
        pi.Product_Family__c = lst3[0].id;
        //insert pi;  
        try{
        Test.StartTest(); 
            Test.setMock(HttpCalloutMock.class, new BatchServiceFacadeMockTest()); 
            BT_AB_ESH1003DX_ESHOPPackage a = new BT_AB_ESH1003DX_ESHOPPackage (interfaceName); 
            ID batchprocessid = Database.executeBatch(a, 200); 
                  
            //Database.executeBatch(a);
        Test.stopTest();
        }catch(exception e){}
   
   }//end of unitTest1      
}