src/objects/BA_INT_DATA_POOL__c.object
<CustomObject>
    <description>custom object for batch integration purposes.
the object act as a single repository for the entire batch data set across all interfaces.
{Job_ID, Record_Type, Group_ID, Sort_Order, Data_in_CSV_format}</description>
    <fields>
        <fullName>export_data__c</fullName>
        <description>the comma separated values fetched fro SFDC per batch job</description>
        <label>export data</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>group_id__c</fullName>
        <description>the unique identifier for the record (eg account_id or invoice_id)</description>
        <label>group id</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>insert_time__c</fullName>
        <description>the start time for the batch job</description>
        <label>insertion time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>job_id__c</fullName>
        <description>job name for the scheduled batch job</description>
        <label>job_id</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>run_for_date__c</fullName>
        <description>EOD date for which the batch job was run</description>
        <label>run for date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>BA_INT_DATA_POOL</label>
    <nameField>
        <label>BA_INT_DATA_POOL Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA_INT_DATA_POOL</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src orig/classes/BT_AB_VSS089DX_ExportZoneToPostalTest.cls
@isTest (Seealldata = TRUE)
private class BT_AB_VSS089DX_ExportZoneToPostalTest {
     // prepares the data needed for execution
    static testmethod void unitTest1(){
       
        BA_INT_DATA_POOL__c ezp = new BA_INT_DATA_POOL__c();
        ezp.job_id__c = '1';
        ezp.group_id__c = 'Detail';
        ezp.run_for_date__c = Date.today();      
        ezp.insert_time__c = DateTime.now(); 
        ezp.export_data__c = '0000';   
        
        insert ezp;
        
    Test.StartTest();
    BT_AB_VSS089DX_ExportZoneToPostal batch = new BT_AB_VSS089DX_ExportZoneToPostal();
    ID batchprocessid = Database.executeBatch(batch,200);
    Test.StopTest();
        
        
        
        
        
    }//end of unitTest1
    
}