src/objects/BA_INT_DATA_POOL__c.object
<CustomObject>
    <description>custom object for batch integration purposes.
the object act as a single repository for the entire batch data set across all interfaces.
{Job_ID, Record_Type, Group_ID, Sort_Order, Data_in_CSV_format}</description>
    <fields>
        <fullName>export_data__c</fullName>
        <description>the comma separated values fetched fro SFDC per batch job</description>
        <label>export data</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>group_id__c</fullName>
        <description>the unique identifier for the record (eg account_id or invoice_id)</description>
        <label>group id</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>insert_time__c</fullName>
        <description>the start time for the batch job</description>
        <label>insertion time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>job_id__c</fullName>
        <description>job name for the scheduled batch job</description>
        <label>job_id</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>run_for_date__c</fullName>
        <description>EOD date for which the batch job was run</description>
        <label>run for date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>BA_INT_DATA_POOL</label>
    <nameField>
        <label>BA_INT_DATA_POOL Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA_INT_DATA_POOL</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BT_CO_DIR_VendorPerformanceMaster__c.object
<CustomObject>
    <fields>
        <fullName>Complain_Count_Delivery__c</fullName>
        <label>Complain Count Delivery</label>
        <summaryFilterItems>
            <field>BT_CO_DIR_VendorPerformance__c.Classification__c</field>
            <operation>equals</operation>
            <value>Delivery Related</value>
        </summaryFilterItems>
        <summaryForeignKey>BT_CO_DIR_VendorPerformance__c.BT_CO_DIR_VendorPerformanceMaster__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Complaint_Count_NonDelivery__c</fullName>
        <label>Complaint Count NonDelivery</label>
        <summaryFilterItems>
            <field>BT_CO_DIR_VendorPerformance__c.Classification__c</field>
            <operation>equals</operation>
            <value>Not Delivery Related</value>
        </summaryFilterItems>
        <summaryForeignKey>BT_CO_DIR_VendorPerformance__c.BT_CO_DIR_VendorPerformanceMaster__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Vendor_Code__c</fullName>
        <label>Vendor Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Group__c</fullName>
        <label>Vendor Group</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>BT_CO_DIR_VendorPerformanceMaster</label>
    <nameField>
        <label>BT_CO_VendorPerformanceMaster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BT_CO_DIR_VendorPerformanceMasters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BT_AB_DIR094DX_CallOutOnly.cls
/*
 * Class Name: BT_AB_DIR094DX_CallOutOnly
 * @author: Renino Niefes
 * Date: 11/19/2014
 * Project/Requirement: SPH Integration - DIR094DX Interface
 * @description This class populates BA_INT_DATA_POOL__c for DIR094DX batch job. Used together with BT_AS_DIR094DX_VendorPerformanceInfo Schedulable
 * 
 * History: 11/19/2014 Renino Niefes Created Batchable for call outs only
 */


global class BT_AB_DIR094DX_CallOutOnly implements Database.Batchable<sObject>,Database.AllowsCallouts
{
    global final String interfaceId = 'DIR094DX';

    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        //Select query and save to data pool
        String query = ' SELECT Vendor_Group__c,  ';
        query += '      Vendor_Code__c,  ';
        query += '      Complaint_Count_NonDelivery__c, ';
        query += '      Complain_Count_Delivery__c ';
        query += ' FROM BT_CO_DIR_VendorPerformanceMaster__c ';
        query += ' WHERE Complaint_Count_NonDelivery__c >0 OR Complain_Count_Delivery__c > 0 ';
        query += ' ORDER BY Vendor_Code__c ';
        
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope)
    {   
        List<BA_INT_DATA_POOL__c> datapoolList = new List<BA_INT_DATA_POOL__c>();
        
        for(sObject obj : scope) {  
            BT_CO_DIR_VendorPerformanceMaster__c record = (BT_CO_DIR_VendorPerformanceMaster__c) obj;
        
            String exportData = '';     
            exportData += record.Vendor_Group__c + ',';
            exportData += record.Vendor_Code__c + ',';
            exportData += record.Complain_Count_Delivery__c + ',';
            exportData += record.Complaint_Count_NonDelivery__c + '';
            
            // Prepare Data Pool information here
            BA_INT_DATA_POOL__c datapoolRecord = new BA_INT_DATA_POOL__c();
            datapoolRecord.Name = interfaceId;
            datapoolRecord.job_id__c = '1';
            datapoolRecord.group_id__c = 'Detail';
            datapoolRecord.run_for_date__c = Date.today();      
            datapoolRecord.insert_time__c = DateTime.now(); 
            datapoolRecord.export_data__c = exportData;
            
            datapoolList.add(datapoolRecord);                   
        }

             Savepoint savepointBeforeDML = Database.setSavepoint();
        try
        {
            insert datapoolList;
        }
        catch(Exception e)
        {    
            // Execute Database Rollback 
            Database.rollback(savepointBeforeDML);
            System.debug('BT_AB_' + interfaceId + '_DailyVendorSubscription insert operation failed.');
        }   
    }
    
    global void finish(Database.BatchableContext BC)
    {
        //Send callout
        BT_CO_INT_Utilities.sendCallOutMessage(interfaceId);

        //Update Batch Run Request's End Time
        BT_AU_BATCHRUNREQUEST_UpdateInfo.updateEndTime(interfaceId);
    }
}