src/objects/BA_INT_DATA_POOL__c.object
<CustomObject>
    <description>custom object for batch integration purposes.
the object act as a single repository for the entire batch data set across all interfaces.
{Job_ID, Record_Type, Group_ID, Sort_Order, Data_in_CSV_format}</description>
    <fields>
        <fullName>export_data__c</fullName>
        <description>the comma separated values fetched fro SFDC per batch job</description>
        <label>export data</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>group_id__c</fullName>
        <description>the unique identifier for the record (eg account_id or invoice_id)</description>
        <label>group id</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>insert_time__c</fullName>
        <description>the start time for the batch job</description>
        <label>insertion time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>job_id__c</fullName>
        <description>job name for the scheduled batch job</description>
        <label>job_id</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>run_for_date__c</fullName>
        <description>EOD date for which the batch job was run</description>
        <label>run for date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>BA_INT_DATA_POOL</label>
    <nameField>
        <label>BA_INT_DATA_POOL Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA_INT_DATA_POOL</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BT_DEV_Debugger.cls
/*
 * Class Name: BT_DEV_Debugger
 * @author: Renno Niefes
 * Date: 09/24/2014
 * Project/Requirement: SPH Integration - Interface Tools
 * @description This class sets the end time of Batch Run Request Object
 * 
 * History: 09/24/2014 Renino Niefes  written the this class
 */

public class BT_DEV_Debugger 
{
    List<BA_INT_DATA_POOL__c> debugList = new List<BA_INT_DATA_POOL__c>();
    
   public void addDebugLogs(String interfaceId, String messageLog)
    {
        BA_INT_DATA_POOL__c datapoolRecord = new BA_INT_DATA_POOL__c();
        datapoolRecord.Name = interfaceId+'_DEBUG';
        datapoolRecord.job_id__c = '1';
        datapoolRecord.group_id__c = 'Debug';
        datapoolRecord.run_for_date__c = Date.today();      
        datapoolRecord.insert_time__c = DateTime.now(); 
        datapoolRecord.export_data__c = messageLog;
                
        debugList.add(datapoolRecord);  
        
    }
    
    public void saveDebugLogs()
    {
        Savepoint savepointBeforeDML = Database.setSavepoint();
        try
        {
            //insert datapoolList;
            insert debugList;
        }
        catch(Exception e)
        {    
            // Execute Database Rollback 
            Database.rollback(savepointBeforeDML);
            System.debug('Debugger failed to save the list');
        }
    }
    
    public void clearDebugLogs(String interfaceId)
    {
        interfaceId += '_DEBUG';
        List<BA_INT_DATA_POOL__c> resultList = [SELECT Id FROM BA_INT_DATA_POOL__c WHERE Name = :interfaceId];
        delete resultList;                  

    }
    
}