src/objects/BA_INT_DATA_POOL__c.object
<CustomObject>
    <description>custom object for batch integration purposes.
the object act as a single repository for the entire batch data set across all interfaces.
{Job_ID, Record_Type, Group_ID, Sort_Order, Data_in_CSV_format}</description>
    <fields>
        <fullName>export_data__c</fullName>
        <description>the comma separated values fetched fro SFDC per batch job</description>
        <label>export data</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>group_id__c</fullName>
        <description>the unique identifier for the record (eg account_id or invoice_id)</description>
        <label>group id</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>insert_time__c</fullName>
        <description>the start time for the batch job</description>
        <label>insertion time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>job_id__c</fullName>
        <description>job name for the scheduled batch job</description>
        <label>job_id</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>run_for_date__c</fullName>
        <description>EOD date for which the batch job was run</description>
        <label>run for date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>BA_INT_DATA_POOL</label>
    <nameField>
        <label>BA_INT_DATA_POOL Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA_INT_DATA_POOL</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_BT_AB_ESH1003DX_ESHOPPackage.cls
//*********************************************************************************************
//
// Author: Glen Anthony Abanes Cubinar
// Date: 1/20/2015
// Description: Test Class for BT_AB_ESH1003DX_ESHOPPackage
//
//*********************************************************************************************

@isTest
Private Class Test_BT_AB_ESH1003DX_ESHOPPackage {

    Public Static testMethod void Test_BT_AB_ESH1003DX_ESHOPPackage() {
    
        List<BA_INT_DATA_POOL__c> lDataPool = new List<BA_INT_DATA_POOL__c>();
        
        //GAAC Insert INT_DATA_POOL
        BA_INT_DATA_POOL__c dataPool = new BA_INT_DATA_POOL__c();
        dataPool.Name = 'ESH1003DX';
        dataPool.job_id__c = 'ESH1003DX';
        dataPool.group_id__c = 'Master';
        dataPool.run_for_date__c = System.Today();
        dataPool.export_data__c = 'H,2014-11-14 12:43:01';
        dataPool.insert_time__c = System.Now();
        
        lDataPool.add(dataPool);
        Insert lDataPool ;
    try{
        Test.StartTest();
        
            //GAAC Call the Batch
            BT_AB_ESH1003DX_ESHOPPackage esh1003dx = new BT_AB_ESH1003DX_ESHOPPackage('ESH1003DX');
            //ID batchprocessid = database.executeBatch(esh1003dx ,200);
            Database.executeBatch(esh1003dx );
        
        Test.StopTest();
    }catch(exception e){}
    }
}