src/objects/Batch_Control_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Batch_Size__c</fullName>
        <label>Batch Size</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Parallel_Jobs__c</fullName>
        <label>Number of Parallel Jobs</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Batch Control Settings</label>
</CustomObject>

src/objects/BATCH_JOB_SCHEDULER__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Code__c</fullName>
        <label>Batch Code</label>
        <picklist>
            <picklistValues>
                <fullName>SP001</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP002</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP003</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP004</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP005</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP006</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP007</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP008</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP009</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP011</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP021</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP022</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP023</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP024</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP025</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP026</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Batch_Run_Date__c</fullName>
        <label>Batch Run Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Number_of_Parallel_Jobs__c</fullName>
        <label>Number of Parallel Jobs</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SFDC_Job_id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>SFDC_Job_id</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>STARTED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ABORTED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUCCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAILED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BATCH_JOB_SCHEDULER</label>
    <nameField>
        <displayFormat>SBRR-{0000000000}</displayFormat>
        <label>SP Batch Run Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BATCH_JOB_SCHEDULER</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BatchInterface_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Batch Interface Settings</label>
</CustomObject>

src/objects/BT_CO_Batch_Run_Request__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Run_Date__c</fullName>
        <label>Batch Run Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Interface_ID__c</fullName>
        <label>Interface ID</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>BT_CO_Batch_Run_Request</label>
    <nameField>
        <displayFormat>BRR-{0000000000}</displayFormat>
        <label>Batch Run Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT_CO_Batch_Run_Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Other__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Other</label>
</CustomObject>

src orig/classes/BatchJobHelperTest2.cls
@isTest
private class BatchJobHelperTest2{
    static testMethod void testBatchJobHelper(){
        Set<Id> extPaymentIds = new Set<Id>();
        List<sObject> lstRecords = new List<sObject>();
        Exception error;
        
        //start custom settings
        BatchInterface_Settings__c integ = new BatchInterface_Settings__c();
        integ.Name = 'Endpoint Delegator';
        integ.Value__c = 'http://devcrsm.sph.com.sg/sqebatch/Batch/BatchAuth2/BatchDelegator';
        database.insert(integ);
        
        Other__c other = new Other__c();
        other.Name = 'SP18_InitializedBatch';
        other.Value__c = '0';
        database.insert(other);
        
        Batch_Control_Settings__c batchControlSettings = new Batch_Control_Settings__c();
        batchControlSettings.Name = 'SP028';
        batchControlSettings.Batch_Size__c = 100;
        batchControlSettings.Number_of_Parallel_Jobs__c = 5;
        insert batchControlSettings;
        
        BT_CO_Batch_Run_Request__c brr = new BT_CO_Batch_Run_Request__c();
        brr.Interface_ID__c = 'IntID123';
        brr.End_Time__c = null;
        database.insert(brr);
        //end custom settings
    
        test.startTest();
            SP_CreditCardFailureRequestBatch batch = new SP_CreditCardFailureRequestBatch('Email', 1, 'SESSIONID', extPaymentIds, date.today());
            ID batchProcessID = Database.executeBatch(batch, 200);
            system.assertNotEquals(batchProcessID, null);
            
            String shortID = string.valueOf(batchProcessID).subString(0,15);
            
            BATCH_JOB_SCHEDULER__c batchJobScheduler = new BATCH_JOB_SCHEDULER__c();
            batchJobScheduler.Batch_Run_Date__c = System.today();
            batchJobScheduler.SFDC_Job_id__c = shortID;
            batchJobScheduler.Batch_Code__c = 'SP028';
            batchJobScheduler.End_Time__c = null;
            insert batchJobScheduler; 
            
            BATCH_JOB_SCHEDULER__c bq = [SELECT Id, Status__c, Batch_Code__c, Batch_Run_Date__c, 
                SFDC_Job_id__c FROM BATCH_JOB_SCHEDULER__c WHERE id=:batchJobScheduler.Id];
               // system.assertEquals(bq.SFDC_Job_id__c, shortID);
            
            BatchJobHelper.updateJobStatus(batchProcessID);
            BatchJobHelper.updateJobStatus(bq.SFDC_Job_id__c, true);
            BatchJobHelper.getNumberOfParallelJobs('SP028');
            BatchJobHelper.isJobSucesss(batchProcessID);
            BatchJobHelper.delegateBatchCall(bq.SFDC_Job_id__c, true);
            BatchJobHelper.runJobCleaners(batchJobScheduler);
            
            try{
                insert batchJobScheduler;
            }
            catch(Exception e){
                error=e;
            }
            BatchJobHelper.handleException(lstRecords, error, '', '', bq.SFDC_Job_id__c, batchProcessID,true);
            BatchJobHelper.handleException(lstRecords, error, '', '', batchProcessID, batchProcessID,false);
        test.stopTest();
    }
}