src/objects/BT_INT_PARAM_CONFIG__c.object
<CustomObject>
    <description>custom object to dynamically generate query for batch interfaces</description>
    <fields>
        <fullName>field_name__c</fullName>
        <description>field to be pulled from the sObject</description>
        <label>field_name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>field_sequence__c</fullName>
        <description>sequence in which the field should appear in the query</description>
        <label>field_sequence</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>from_object__c</fullName>
        <description>the object from which the field data needs to be pulled</description>
        <label>from_object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>interface_name__c</fullName>
        <label>interface_name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>postOpFieldName__c</fullName>
        <label>postOpFieldName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>BT_INT_PARAM_CONFIG</label>
    <nameField>
        <label>name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BT_INT_PARAM_CONFIGS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BT_INT_UTILITY.cls
global with sharing class BT_INT_UTILITY {

	global static String createSimpleQuery(String interfaceName, String whereClause){
		String queryString0 = 'select field_name__c, from_object__c from bt_int_param_config__c where interface_name__c = :interfaceName order by field_sequence__C';
		List<bt_int_param_config__c> fieldList = Database.query(queryString0);
		
		String batchQueryString = 'Select ';
		String fromObject = '';
		
		for(bt_int_param_config__c temp : fieldList){
			if(fromObject != ''){
				batchQueryString += ' ,' + temp.field_name__c;
			}else{
				batchQueryString += temp.field_name__c;
			}
			fromObject = temp.from_object__c;
		}
		
		batchQueryString += ' from ' + fromObject;
		
		if(whereClause != ''){
			batchQueryString += ' where '+ whereClause;
		}
		
		System.debug('##############' + batchQueryString);
		return batchQueryString;
	}
	
	global static List<String> getQueryFields(String interfaceName){
		String queryString0 = 'select postOpFieldName__c from bt_int_param_config__c where interface_name__c = :interfaceName order by field_sequence__C';
		List<bt_int_param_config__c> fieldList = Database.query(queryString0);
		List<String> returnList = new List<String>();
		
		for(bt_int_param_config__c temp : fieldList){
			returnList.add(temp.postOpFieldName__c);
		}
		
		System.debug('fieldList size : ' + returnList.size());
		System.debug(returnList);
		
		return returnList;
	}
}