src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Current_Date_for_Year_To_Date__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Current Date for Year To Date</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Next_Year_for_Year_To_Date__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Next Year for Year To Date</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Restart_Date__c</fullName>
        <label>Restart Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Temp_Stop_Date__c</fullName>
        <label>Temp Stop Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Temp_Stop_Sub__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Temp Stop Sub</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Cases (Temp Stop Sub)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Subscription__c.object
<CustomObject>
    <description>Junction object between Case and Subscription</description>
    <fields>
        <fullName>CASE_Subscription_Legacy_Id__c</fullName>
        <externalId>true</externalId>
        <label>CASE Subscription Legacy Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Subscriptions (Direct)</relationshipLabel>
        <relationshipName>Case_Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (1 AND 3 AND 4)</booleanFilter>
            <filterItems>
                <field>Zuora__Subscription__c.Zuora__Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.isComplaint__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>$Source.isComplaint__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Zuora__Subscription__c.Subscription_Type_1__c</field>
                <operation>equals</operation>
                <value>Publication</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Case Subscriptions</relationshipLabel>
        <relationshipName>Case_Subscriptions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Case Subscription</label>
    <nameField>
        <displayFormat>CS{0000000000}</displayFormat>
        <label>Case Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MigrationCaseSubTriggerHandler.cls
/**
 * Class Name: <MigrationCaseSubTriggerHandler>
 * @author: <Christopher Camilon>
 * Date: <04/19/2016>
 * Requirement/Project Name: <SPH>
 * @description<To populate the necesarry fields for Case temp Stop> 
 *
 */
public class MigrationCaseSubTriggerHandler implements TriggerHandlerInterface{

    public static Boolean preventExecution = FALSE;
    public static Boolean isBeforeUpdateTriggerCalled = FALSE;
    public static Boolean isBeforeDeleteTriggerCalled = FALSE;
    public static Boolean isBeforeInsertTriggerCalled = FALSE;
    public static Boolean isAfterUpdateTriggerCalled = FALSE;
    public static Boolean isAfterDeleteTriggerCalled = FALSE;
    public static Boolean isAfterInsertTriggerCalled = FALSE;

    Id CASE_TEMP_STOP_TYPE_ID  = (Id) ConstantsSLB.getKeyId('Case_Temp Stop');
    Static Set<Id> caseIds = new Set<Id>();
    Static Map<Id, Case> caseMap = new Map<Id, Case>();
    Static List<Case> caseUpdList = new List<Case>();
    public Boolean runBeforeInsertTrigger() {
        Boolean returnVar = !MigrationCaseSubTriggerHandler.isBeforeInsertTriggerCalled;
        MigrationCaseSubTriggerHandler.isBeforeInsertTriggerCalled = TRUE;
        return returnVar;
    }
    
    public Boolean runBeforeUpdateTrigger() {
        Boolean returnVar = !MigrationCaseSubTriggerHandler.isBeforeUpdateTriggerCalled;
        MigrationCaseSubTriggerHandler.isBeforeUpdateTriggerCalled = TRUE;
        return returnVar;        
    }
    
    public Boolean runBeforeDeleteTrigger() {
        Boolean returnVar = !MigrationCaseSubTriggerHandler.isBeforeDeleteTriggerCalled;
        MigrationCaseSubTriggerHandler.isBeforeDeleteTriggerCalled = TRUE;
        return returnVar;
    }
    
    public Boolean runAfterInsertTrigger() {
        Boolean returnVar = !MigrationCaseSubTriggerHandler.isAfterInsertTriggerCalled;
        MigrationCaseSubTriggerHandler.isAfterInsertTriggerCalled = TRUE;
        return returnVar;
    }
    
    public Boolean runAfterUpdateTrigger() {
        Boolean returnVar = !MigrationCaseSubTriggerHandler.isAfterUpdateTriggerCalled;
        MigrationCaseSubTriggerHandler.isAfterUpdateTriggerCalled = TRUE;
        return returnVar;
    }
    
    public Boolean runAfterDeleteTrigger() {
        Boolean returnVar = !MigrationCaseSubTriggerHandler.isAfterDeleteTriggerCalled;
        MigrationCaseSubTriggerHandler.isAfterDeleteTriggerCalled = TRUE;
        return returnVar;
    }
    
    public void bulkBefore() {
    
        
        if (Trigger.isUpdate) {
        
            for (Case_Subscription__c caseSub : (list<Case_Subscription__c>)trigger.new) {
                if(caseSub.CASE_Subscription_Legacy_Id__c != null){
                    caseIds.add(caseSub.Case__c);        
                }
            }    
            List<Case> caseList = new List<Case>();
            caseList = [Select Id, Temp_Stop_Date__c, Restart_Date__c, Current_Date_for_Year_To_Date__c, Next_Year_for_Year_To_Date__c From Case Where Id in : caseIds];
            for(Case c : caseList){
                
                caseMap.put(c.id, c);
            
            }
        } 
        
                                             
        
    }
    
    public void bulkAfter() {
        
    }
    public void afterUpdate(SObject oldSo, SObject so) {
    
       
    
    }
    
    public void beforeUpdate(SObject oldSo, SObject so) {
    
       
    
    }
    public void afterDelete(SObject so) {
    
       
    
    }
    public void beforeDelete(SObject so) {
    
       
    
    }
    
    public void beforeInsert(SObject so) {
    
       
    
    }
    
    public void afterInsert(SObject so) {
    
        Case_Subscription__c caseSub = (Case_Subscription__c)so;
        if(caseSub.Case__r.RecordTypeId == CASE_TEMP_STOP_TYPE_ID && caseSub.CASE_Subscription_Legacy_Id__c != null){
            Case updCase = caseMap.get(caseSub.Case__c);
            updCase.Temp_Stop_Sub__c = caseSub.Subscription__c;
            caseUpdList.add(updCase);                   
        } 
    
    }
    public void andFinally() {
    
        if(!caseUpdList.isEmpty()){
            update caseUpdList;
        }
    }
 
}