src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stop_Request_Date__c</fullName>
        <label>Stop Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <picklist>
            <controllingField>Category__c</controllingField>
            <picklistValues>
                <fullName>App Crash / Slow Loading / Sys Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Dispute (Direct Sub)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Dispute (Vendor Sub)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Casual Sales (Buzz, Newsstand, Outlet)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change/Reset Password</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Credit Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Particulars</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Subscription Packages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivate User Id</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gift Redemption Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gift Redemption Status</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Late Delivery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Magazine Late Delivery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Magazine Non Delivery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miscellaneous</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Inserts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newspapers - Gift Redemption Status</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Circulation Related Matters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Delivery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Start (Temp-Stop)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Stop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Stop (Temp Stop)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchase of Backdated Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchase of Receptacle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requests to Vendor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Flag Not Updated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Delivery</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <label>Sub Status</label>
        <picklist>
            <controllingField>Category__c</controllingField>
            <picklistValues>
                <fullName>Assess for Goodwill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complaint Resolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>For Retention Offer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goodwill Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goodwill Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newspaper Redelivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provisioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reclassification Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reclassification Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Reclassification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to CSO Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to CSO to Initiate Courier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Mailing Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Ops Rep/Cir-Planner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Technical CSO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Vendor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subscription Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subscription Stop Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temp Stop Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temp Stop Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urgent Start Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urgent Start Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urgent Stop Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urgent Stop Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Goodwill Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Reclassification Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Urgent Start Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Urgent Stop Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zuora Issue - Subscription Cancellation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provisioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Vendor Assignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Void</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stop_Request_Date__c</fullName>
        <label>Stop Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <picklist>
            <picklistValues>
                <fullName>Stop Subscription</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND NOT 5) OR (1 AND 2 AND 3 AND 4 AND 5)</booleanFilter>
            <filterItems>
                <field>Zuora__Subscription__c.Subscription_Type_1__c</field>
                <operation>equals</operation>
                <value>Publication</value>
            </filterItems>
            <filterItems>
                <field>Zuora__Subscription__c.Zuora__Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Zuora__Subscription__c.Zuora__Status__c</field>
                <operation>notEqual</operation>
                <value>Cancelled</value>
            </filterItems>
            <filterItems>
                <field>$Source.Order_Type1__c</field>
                <operation>contains</operation>
                <value>Change of Subscription</value>
            </filterItems>
            <filterItems>
                <field>$Source.isChangeOfSubEntry__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Order Line Items (Direct)</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Line_Item__c</fullName>
        <displayFormat>A-{000000}</displayFormat>
        <label>Order Line Item #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items_Direct</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stop_Request_Date__c</fullName>
        <label>Stop Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI{0000000000}</displayFormat>
        <label>Order Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SP_CancelFuturePStop.cls
/*
* Class Name: SP_CancelFuturePStop
* @Author: Wenjun Zhu
* Date: 21 June 2015
* Requirement/Project Name: CRSM Project
* @Description Batch Apex Class to cancel Subscriptions at PStop Request Date - 1
* @History D-3150 21/06/15 Wenjun - Created batchable class
* @History SIT Hotfix 23/06/15 Wenjun - Add on-demand sync
*
*/
global class SP_CancelFuturePStop implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts{ 
    Date referenceDate; 
    final Static String STOP_SUB_CATEGORY = GlobalVariableClass.SUBCATEGORY_STOP_SUBCRIPTION;
    final Static String STOP_SUB_STATUS = GlobalVariableClass.SUB_STATUS_READY_FOR_SUBMISSION;
    //START D-3194 07/01/2015 Added by J.Sarion - Added criteria for Sub Status equals Provisioning
    final Static String STOP_SUB_STATUS_PROVISIONING = GlobalVariableClass.SUB_STATUS_PROVISIONING;
	//END D-3194 07/01/2015 Added by J.Sarion - Added criteria for Sub Status equals Provisioning
	
    Set<Id> setBillingAccountId;
    
    //Default Constructor
    global SP_CancelFuturePStop()
    {
        referenceDate = Date.today().addDays(1);
        setBillingAccountId = new Set<Id>();
    }
    
    //Constructor with input of PSTOP Date to process
    global SP_CancelFuturePStop(Date inputDt)
    {
        referenceDate = inputDt;
        setBillingAccountId = new Set<Id>();
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        //Query all the PStop Cases with Sub Status as "Ready For Submission"
        String query = 'SELECT Id, Case__c, Order__c, Subscription__c, Subscription__r.Zuora__CustomerAccount__c,Stop_Request_Date__c ';
        query       += 'FROM Order_Line_Item__c ';
        query       += 'WHERE Case__r.Sub_Category__c = : STOP_SUB_CATEGORY ';
        query       += 'AND (Case__r.Sub_Status__c = :STOP_SUB_STATUS OR Case__r.Sub_Status__c = :STOP_SUB_STATUS_PROVISIONING)'; //START-END D-3194 07/01/2015 Added by J.Sarion - Added criteria for Sub Status equals Provisioning
        query       += 'AND Stop_Request_Date__c <= : referenceDate AND Stop_Request_Date__c > TODAY';
        
        return Database.getQueryLocator(query);
    }
    
    //Logic copied from StopSubscriptionButton
    global void execute(Database.BatchableContext BC, List<Order_Line_Item__c> lstOlis){
        Map<ID, Date> mapSubIDToStopDate = new Map<ID, Date>();
        List<Case> lstCasesToUpd = new List<Case>();
        List<Order__c> lstOrdersToUpd = new List<Order__c>();
        List<exception> lstExceptions = new List<exception>();
        
        for(Order_Line_Item__c oli : lstOlis)  
        {
            mapSubIDToStopDate.put(oli.Subscription__c, oli.Stop_Request_Date__c);
            setBillingAccountId.add(oli.Subscription__r.Zuora__CustomerAccount__c);
        }
            
        if (!mapSubIDToStopDate.isEmpty()) 
        {
            try {
                SM_SubscriptionCancellationHelper.cancelSubscriptions(mapSubIDToStopDate, GlobalVariableClass.SUBJECT_STOP_SUBSCRIPTION);
                
                if (SM_SubscriptionCancellationHelper.isSuccess == false) 
                {
                    for(Order_Line_Item__c oli : lstOlis) 
                    {
                        Case stopCase = new Case (ID = oli.Case__c);
                        stopCase.Sub_Status__c = 'Zuora Issue - Subscription Cancellation';
                        lstCasesToUpd.add(stopCase);
                        
                        Order__c order = new Order__c(ID = oli.Order__c);
                        order.Status__c = GlobalVariableClass.SUB_STATUS_CLOSE;
                        lstOrdersToUpd.add(order);
                    }
                    
                    try {
                        if(!lstCasesToUpd.isEmpty())
                            update lstCasesToUpd;
                        if(!lstOrdersToUpd.isEmpty())
                            update lstOrdersToUpd;
                    } catch (Exception dmlException) {
                        lstExceptions.add(dmlException);
                    } 
                }
            } catch (Exception e){
                lstExceptions.add(e);
            }
        }
        
        if(!lstExceptions.isEmpty())
            ExceptionLogger.log(lstExceptions);
    }
    
    global void finish (Database.BatchableContext BC){ 
        //Perform Zuora Sync
        Zuora.OnDemandSyncManager syncManager = new Zuora.OnDemandSyncManager();
        syncManager.syncObjectType = Zuora.OnDemandSyncManager.ObjectType.BILLING_ACCOUNT;
        syncManager.syncObjectIdSet  = setBillingAccountId;
        syncManager.emailNotificationEnabled = false;
        
        List<Zuora.SyncResult> syncResult = syncManager.sendRequest();
        System.debug('>>>>> Sync Result:' + syncResult);
        
        //Update Job Status
        BatchJobHelper.updateJobStatus(BC.getJobId());
    } 
}