src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account field that is not read-only to be used in Adjustment Case. Field Value will be copied into Account Standard field and will not be exposed in detail page layout.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Account) (Do Not Use)</relationshipLabel>
        <relationshipName>Cases_Do_Not_Use</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notify_Vendor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Notify Vendor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Remarks__c</fullName>
        <label>Remarks</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stop_Date__c</fullName>
        <label>Stop/Complaint Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Informed_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Informed Customer?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Prefer Vendor Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prefer Cash Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Odd Subscription Patterns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPH Policy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miscellaneous</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Recipient_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recipient Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.Recipient_Indicator__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Recipient Contact)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Remarks__c</fullName>
        <label>Remarks</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Vendor_Sms_Remarks__c</fullName>
        <label>Vendor Sms Remarks</label>
        <type>TextArea</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order_Line_Item_Vendor__c.object
<CustomObject>
    <description>The Order Line Item Object will represent the item selected during Order Entry. 
The record looks up to Order record.</description>
    <fields>
        <fullName>Fri__c</fullName>
        <label>Fri</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mon__c</fullName>
        <label>Mon</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Notify_Vendor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Notify Vendor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Line Items (Vendor)</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PHd__c</fullName>
        <label>PHd</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PHe__c</fullName>
        <label>PHe</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Vendor Subscription can only select Newspapers</errorMessage>
            <filterItems>
                <field>Publication__c.Publication_Type__c</field>
                <operation>equals</operation>
                <value>N</value>
            </filterItems>
            <filterItems>
                <field>Publication__c.Platform_Type__c</field>
                <operation>equals</operation>
                <value>Print</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Prefer Vendor Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prefer Cash Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Odd Subscription Patterns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPH Policy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miscellaneous</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Remarks__c</fullName>
        <label>Remarks</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sat__c</fullName>
        <label>Sat</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Stop_Date__c</fullName>
        <label>Stop Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sun__c</fullName>
        <label>Sun</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Thu__c</fullName>
        <label>Thu</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tue__c</fullName>
        <label>Tue</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vendor_Sms_Remarks__c</fullName>
        <label>Vendor Sms Remarks</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Wed__c</fullName>
        <label>Wed</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order Line Item (Vendor)</label>
    <nameField>
        <displayFormat>OLIV{0000000000}</displayFormat>
        <label>Order Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items (Vendor)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product_Family__c.object
<CustomObject>
    <fields>
        <fullName>Product_Family__c</fullName>
        <inlineHelpText>Product Family Code</inlineHelpText>
        <label>Product Family</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Product Family</label>
    <nameField>
        <displayFormat>PF-{00000000}</displayFormat>
        <label>Product Family Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Families</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Publication__c.object
<CustomObject>
    <fields>
        <fullName>Product_Family__c</fullName>
        <label>Product Family</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <label>Publication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Subscription_Vendor__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions (Vendor)</relationshipLabel>
        <relationshipName>Subscriptions_Vendor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <type>TextArea</type>
    </fields>
    <label>Subscription (Vendor)</label>
    <nameField>
        <displayFormat>SV-{0000000000}</displayFormat>
        <label>Subscription (Vendor) Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions (Vendor)</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Subscription_Vendor_Publication__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscription (Vendor) Publications</relationshipLabel>
        <relationshipName>Subscription_Vendor_Publications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fri__c</fullName>
        <label>Fri</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mon__c</fullName>
        <label>Mon</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Subscription (Vendor) Publications</relationshipLabel>
        <relationshipName>Subscription_Vendor_Publications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PHd__c</fullName>
        <label>PHd</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PHe__c</fullName>
        <label>PHe</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Subscription (Vendor) Publications</relationshipLabel>
        <relationshipName>Subscription_Vendor_Publications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sat__c</fullName>
        <label>Sat</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sun__c</fullName>
        <label>Sun</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Thu__c</fullName>
        <label>Thu</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tue__c</fullName>
        <label>Tue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wed__c</fullName>
        <label>Wed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Subscription (Vendor) Publication</label>
    <nameField>
        <displayFormat>SVP{0000000000}</displayFormat>
        <label>Subscription (Vendor) Publication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription (Vendor) Publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ViewVendorOrderEntryController.cls
/**
 * Class Name: ViewVendorOrderEntryController
 * @author 
 * Date: 2014.07.31
 * Requirement: Start Subscription Order Entry
 * @description This class is use as an apex controller of ViewVendorOrderEntry VF page.
 *
 */


/*
* ------Revision------
* Version 1.0: Pilot Release
* By: <Glenn Garcia>
* Description:s
*/

public class ViewVendorOrderEntryController {

    
public Order__c order {get; set;}
public List<Order_Line_Item_Vendor__c> orders { get; set; }
public Publication__c pub {get; set; }
public Order_Line_Item_Vendor__c oli {get; set;}
public Integer counter {get; set;}
public String index {get; set;}
public List<OrWrapper> OrWrapperList {get;set;}
public Case objcase {get;set;}

    public ViewVendorOrderEntryController() {
        //string orderId = ApexPages.currentPage().getParameters().get('id');
        //system.assertequals(orderId, null);
        String orderId = ApexPages.currentPage().getParameters().get('id');               
        orders = new List<Order_Line_Item_Vendor__c>();
        Order_Line_Item_Vendor__c lineItem = new Order_Line_Item_Vendor__c();
        orders.add(lineItem);
        counter=0;
        
        //validation if the fields are not NULL
        OrWrapperList = new List<OrWrapper>();       
        if(orderId == NULL || orderId == '') {
        OrWrapper OrWrap = new OrWrapper(new Order_Line_Item_Vendor__c( Mon__c = 0, Tue__c = 0,Wed__c = 0,Thu__c = 0, 
                                         Fri__c = 0, Sat__c = 0, Sun__c = 0, PHe__c = 0, PHd__c = 0  
        ));
        counter++;
        OrWrap.counterWrap = counter; 
        OrWrapperList.add(OrWrap);
        order = new Order__c();       
        }

        else {           
             order = [SELECT Id, Account__c, Recipient_Contact__c, Reason__c,  Remarks__c, Vendor_Sms_Remarks__c, Informed_Customer__c  
                     FROM Order__c 
                     WHERE Id = :orderId];
                     
              LIST<Order_Line_Item_Vendor__c> vLineItems = [SELECT Id, Mon__c, Tue__c, Wed__c, Thu__c, Fri__c, Sat__c, Sun__c,
                     PHe__c, PHd__c, Start_Date__c, Notify_Vendor__c, Stop_Date__c, Publication__c
                     FROM Order_Line_Item_Vendor__c
                     WHERE Order__c = :orderId];                    
             for(Order_Line_Item_Vendor__c vli : vLineItems) {
                OrWrapper OrWrap = new OrWrapper(vli);
                counter++;
                OrWrap.counterWrap = counter; 
                OrWrapperList.add(OrWrap);
             }
    }
 }
     
     public class OrWrapper{
        public Order_Line_Item_Vendor__c oLine {get;set;}
        public Integer counterWrap {get;set;}
        
        public OrWrapper(Order_Line_Item_Vendor__c ol){
            this.oLine = ol;         
        }
    }

    public void initializeData() {
            oli = new Order_Line_Item_Vendor__c();
            }
            
    
    
    public void addOrder() {
        OrWrapper OrWrap = new OrWrapper(new Order_Line_Item_Vendor__c(
            Mon__c = 0,
            Tue__c = 0,
            Wed__c = 0,
            Thu__c = 0,
            Fri__c = 0,
            Sat__c = 0,
            Sun__c = 0,
            PHe__c = 0,
            PHd__c = 0            
        ));
        counter++;
        OrWrap.counterWrap = counter; 
        OrWrapperList.add(OrWrap);
   }

   
    public void removePub(){
        Integer param = Integer.valueOf(index);
        
        for(Integer i=0; i<OrWrapperList.size(); i++){
            if(OrWrapperList[i].counterWrap == param){
                OrWrapperList.remove(i);  
            }
        }
        
        counter--;      
    }
              
        
    public List<SelectOption> getItems() {
        
        List<SelectOption> options = new List<SelectOption>();
        list<Id> lPubID = new list<id>();
        list<string> lPubName = new list<string>();
        
        
        
        for (Publication__c pub : [select Id, Name, Product_Family__c from Publication__c]) 
        {     
             lPubID.add(pub.Id);
             lPubName.add(pub.Name);
             options.add(new SelectOption(pub.Id, pub.Name));
        }  
     
        return options;
        
        
    }

    public PageReference saveDraft() {                 
                order.Billing_Account__c = 'a0MN00000015tBeMAI';
                //order.Total_Full_Prepaid_Charge__c = 1;
                //order.Total_Monthly_Recurring_Charge__c = 1;
                order.Credit_Balance__c = 1;
                //order.Postage_Charge__c = 1;
                order.Delivery_Charge__c = 1;
                order.Monthly_Delivery_Charge_for_Full_Payment__c = 1;
                insert order;
                                
                // list that holds the Order_Line_Item_Vendor__c records
                // to be inserted
                List<Order_Line_Item_Vendor__c> OrList = new List<Order_Line_Item_Vendor__c>();
                for (OrWrapper ow : OrWrapperList)
                 {
                     Order_Line_Item_Vendor__c OrLi = ow.oLine;
                     OrLi.Order__c = order.Id;                 
                     OrList.add(OrLi);                
                 }
                insert OrList;               

                PageReference page = new Pagereference('/'+order.Id);
            page.setRedirect(true);
            return page;
                 }   
                 
        public pageReference cancelAction(){
    return returnToOrigination();
  }
        
        public PageReference cancel() {
        PageReference pageRef = new PageReference('/');
        pageRef.setRedirect(true);
        return pageRef;
    }        
        
        public PageReference submit() {  
                order.Billing_Account__c = 'a0MN00000015tBeMAI';
                //order.Total_Full_Prepaid_Charge__c = 1;
                //order.Total_Monthly_Recurring_Charge__c = 1;
                order.Credit_Balance__c = 1;
                //order.Postage_Charge__c = 1;
                order.Delivery_Charge__c = 1;
                order.Monthly_Delivery_Charge_for_Full_Payment__c = 1;
                upsert order;
                                
                // list that holds the Order_Line_Item_Vendor__c records
                // to be inserted
                List<Order_Line_Item_Vendor__c> OrList = new List<Order_Line_Item_Vendor__c>();
                for (OrWrapper ow : OrWrapperList)
                 {
                     Order_Line_Item_Vendor__c OrLi = ow.oLine;
                     OrLi.Order__c = order.Id;                 
                     OrList.add(OrLi);                
                 }
                upsert OrList;               
          
                // create related publications based on order line item vendor records
                List<Subscription_Vendor_Publication__c> svList = new List<Subscription_Vendor_Publication__c>();
                //List<Subscription_Vendor__c> sv2List = new List<Subscription_Vendor__c>();                
                       for (Order_Line_Item_Vendor__c oliv : [SELECT Mon__c, Tue__c, Wed__c, Thu__c, Fri__c, Sat__c, Sun__c, 
                                                                     PHd__c, PHe__c, Publication__c, Order__c, Subscription_Vendor__c,
                                                                     Start_Date__c, Stop_Date__c
                                                              FROM Order_Line_Item_Vendor__c where Order__c = :order.Id]) {
                // create vendor subscription
                Subscription_Vendor__c sv = new Subscription_Vendor__c();
                sv.Order_Number__c = order.Id;
                sv.Account__c = order.Account__c;
                sv.Reason__c = order.Reason__c;
                sv.Recipient__c = order.Recipient_Contact__c;
                sv.Subscription_Start_Date__c = oliv.Start_Date__c;
                sv.Subscription_Stop_Date__c = oliv.Stop_Date__c;
                insert sv;                                     

                         Subscription_Vendor_Publication__c svp = new Subscription_Vendor_Publication__c();
                         svp.Subscription_Vendor__c = sv.Id;
                         svp.Publication__c = oliv.Publication__c;
                         svp.Order__c = oliv.Order__c;
                         svp.Mon__c = oliv.Mon__c;
                         svp.Tue__c = oliv.Tue__c;
                         svp.Wed__c = oliv.Wed__c;
                         svp.Thu__c = oliv.Thu__c;
                         svp.Fri__c = oliv.Fri__c;
                         svp.Sat__c = oliv.Sat__c;
                         svp.Sun__c = oliv.Sun__c;
                         svp.PHd__c = oliv.PHd__c;
                         svp.PHe__c = oliv.PHe__c;
                         svList.add(svp);
                }
                
                insert svList;
                //insert sv2List;
                
                PageReference page = new Pagereference('/');
            page.setRedirect(true);
            return page;
                 }            
        

        public PageReference edit() {
        string pId = ApexPages.currentPage().getParameters().get('id');
        PageReference page = new PageReference ('/apex/CreateVendorOrderEntry?id='+pId);
        page.setRedirect(true);
         return page;

        return null;
    }
        private pageReference returnToOrigination(){
        PageReference page = new PageReference('/' + order.Id);
        page.setRedirect(true);
        return page;
  }

}