src/objects/Delivery_Charge_Type__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Mapping for Address Type to Delivery Type</description>
    <label>Delivery Charge Type</label>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Base_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Subscription to be renewed.</description>
        <label>Base Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Orders (Subscription for Renewal)</relationshipLabel>
        <relationshipName>Orders_Renewal</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_Account_Creation_Mode__c</fullName>
        <label>Billing Account Creation Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Create New Billing Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Use existing Billing Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Delivery_Charge_Type__c</fullName>
        <inlineHelpText>H - HDB
L - Landed
C - Condo
N/Z - No Delivery Charge
S/9 - Special Delivery Charge</inlineHelpText>
        <label>Delivery Charge Type</label>
        <picklist>
            <picklistValues>
                <fullName>H</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Z</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order_Type__c</fullName>
        <label>Order Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Package_Name__c</fullName>
        <label>Package Name</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Vendor_Credit__c</fullName>
        <label>Vendor Credit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Case__r.Account.Name</formula>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Line_Item__c</fullName>
        <displayFormat>A-{000000}</displayFormat>
        <label>Order Line Item #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items_Direct</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI{0000000000}</displayFormat>
        <label>Order Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Package__c.object
<CustomObject>
    <fields>
        <fullName>Effective_End_Date__c</fullName>
        <label>Effective End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Start_Date__c</fullName>
        <label>Effective Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Promotion__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <description>User specified</description>
        <label>Contract</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Effective_End_Date__c</fullName>
        <description>User specified</description>
        <label>Effective End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Start_Date__c</fullName>
        <description>User specified</description>
        <label>Effective Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Promotion_Code__c</fullName>
        <description>The promotion code will be shared across multiple promotions to simulate grouping of promotions of different contract periods.</description>
        <externalId>true</externalId>
        <label>Promotion Code</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Promotion_Type__c</fullName>
        <description>This will be a read only field based on the Promotion Type selection on the Home page.</description>
        <label>Promotion Type</label>
        <picklist>
            <picklistValues>
                <fullName>Gift Promotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Gift Promotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add-On Promotion</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Promotion_Package__c.object
<CustomObject>
    <fields>
        <fullName>Package_Name__c</fullName>
        <label>Package Name</label>
        <referenceTo>Package__c</referenceTo>
        <relationshipLabel>Promotion Package</relationshipLabel>
        <relationshipName>Promotion_Package</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Promotion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion</label>
        <referenceTo>Promotion__c</referenceTo>
        <relationshipLabel>Promotion Package</relationshipLabel>
        <relationshipName>Promotion_Package</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promotion Package</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>Promotion Pack Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Package</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/StartStopTest.cls
@isTest(SeeAllData = True)
private class StartStopTest{
    static testmethod void startStopMethod1(){
        Map<String, SObject> sObjMap = new Map<String,SObject>();
        sObjMap = TestDataFactory.createSubscriptionPackage();
        Zuora__Subscription__c zSub = (Zuora__Subscription__c) sObjMap.get('Zuora__Subscription__c');
        Test.startTest();
        insert zSub;
        
        Order__c orderRec = (Order__c) sObjMap.get('Order__c');
        orderRec.Base_Subscription__c = zSub.id;
        orderRec.Order_Type__c = 'Start';
        orderRec.Delivery_Charge_Type__c = 'S';
        orderRec.Billing_Account_Creation_Mode__c = 'Use existing Billing Account';
        orderRec.Vendor_Credit__c = 10000;
        update orderRec;
        zqu__ProductRatePlanCharge__c zprp = new zqu__ProductRatePlanCharge__c();
        zprp.zqu__ProductRatePlan__c = sObjMap.get('zqu__ProductRatePlan__c').id;
        zprp.zqu__Type__c = 'Recurring';
        zprp.zqu__Discount_Level__c = 'RatePlan';
        zprp.zqu__Model__c = 'Discount-Percentage';
        zprp.zqu__ZuoraId__c = '1234567';
        //insert zprp;
        Promotion__c promo = new Promotion__c();
        promo.RecordTypeId = [Select Id From RecordType Where SObjectType = 'Promotion__c' And Name = 'Gift Promotion' LIMIT 1].id;
        promo.Name = 'Promo Name';
        promo.Promotion_Code__c = 'ABCDE';
        promo.Effective_Start_Date__c = date.today();
        promo.Contract__c = 'No';
        promo.Effective_End_Date__c = date.today().addDays(30);
        promo.Promotion_Type__c = 'Gift Promotion';
        //insert promo;
        insert new List<SObject>{zprp, promo};
        
        Promotion_Package__c proPack = new Promotion_Package__c();
        proPack.Promotion__c = promo.Id;
        proPack.Package_Name__c= sObjMap.get('Package__c').id;
        insert proPack;
        PageReference pRef = Page.startstop;
        Test.setCurrentPage(pRef);
        ApexPages.CurrentPage().getParameters().put('id', orderRec.id);
        ApexPages.CurrentPage().getParameters().put('accountId', orderRec.Account__c);
        startstop sStop = new startstop();
        sStop.initialize();
        sStop.selectedOrderLineItem = sObjMap.get('Order_Line_Item__c').id;
        sStop.retrieveOrderLineItem();
        sStop.addOrderLineItem();
        sStop.searchFrom = 'Package';
        sStop.searchText = 'Pack name';
        sStop.searchBillingType = 'Full Prepaid';
        sStop.executeSearch();
        sStop.searchFrom = 'Promotion';
        sStop.searchText = 'Promo Name';
        sStop.searchBillingType = 'Full Prepaid';
        sStop.executeSearch();
        sStop.getAcquisitionTypes();
        sStop.getDeliveryChargeTypes();
        sStop.getBillingAccountOptions();
        sStop.getSource();
        sStop.clearPaymentMethod();
        sStop.clearOtherPaymentMethod();
        sStop.getselectedchangeOfSubscriptionOptions();
        sStop.setchangeOfSubscriptionOptions('quantity');
        sStop.ChangeOrderAction();
        sStop.setchangeOfSubscriptionOptions('package');
        sStop.ChangeOrderAction();
        sStop.getListchangeOfSubscriptionOptions();
        sStop.populateSubscriptionDetail();
        sStop.populateAddOn();
        sStop.save();
        sStop.cancel();
        sStop.populatePromotionGifts();
        
        Test.stopTest();
    }
    static testmethod void startStopMethod2(){
        Map<String, SObject> sObjMap = new Map<String,SObject>();
        sObjMap = TestDataFactory.createSubscriptionPackage();
        Zuora__Subscription__c zSub = (Zuora__Subscription__c) sObjMap.get('Zuora__Subscription__c');
        Test.startTest();
        insert zSub;
        
        Order__c orderRec = (Order__c) sObjMap.get('Order__c');
        orderRec.Base_Subscription__c = zSub.id;
        orderRec.Order_Type__c = 'Start';
        orderRec.Delivery_Charge_Type__c = 'S';
        orderRec.Billing_Account_Creation_Mode__c = 'Use existing Billing Account';
        orderRec.Vendor_Credit__c = 10000;
        update orderRec;
        zqu__ProductRatePlanCharge__c zprp = new zqu__ProductRatePlanCharge__c();
        zprp.zqu__ProductRatePlan__c = sObjMap.get('zqu__ProductRatePlan__c').id;
        zprp.zqu__Type__c = 'Recurring';
        zprp.zqu__Discount_Level__c = 'RatePlan';
        zprp.zqu__Model__c = 'Discount-Percentage';
        zprp.zqu__ZuoraId__c = '1234567';
        //insert zprp;
        Promotion__c promo = new Promotion__c();
        promo.RecordTypeId = [Select Id From RecordType Where SObjectType = 'Promotion__c' And Name = 'Gift Promotion' LIMIT 1].id;
        promo.Name = 'Promo Name';
        promo.Promotion_Code__c = 'ABCDE';
        promo.Effective_Start_Date__c = date.today();
        promo.Contract__c = 'No';
        promo.Effective_End_Date__c = date.today().addDays(30);
        promo.Promotion_Type__c = 'Gift Promotion';
        //insert promo;
        insert new List<SObject>{zprp, promo};
        
        Promotion_Package__c proPack = new Promotion_Package__c();
        proPack.Promotion__c = promo.Id;
        proPack.Package_Name__c= sObjMap.get('Package__c').id;
        insert proPack;
        PageReference pRef = Page.startstop;
        Test.setCurrentPage(pRef);
        //ApexPages.CurrentPage().getParameters().put('id', orderRec.id);
        ApexPages.CurrentPage().getParameters().put('accountId', orderRec.Account__c);
        startstop sStop = new startstop();
        sStop.earliestStart(sObjMap.get('Package__c').id);
        Test.stopTest();
    }
}