src/objects/Delivery_Charge__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Mapping of Subscriber Charge and Vendor Credit based on Delivery Charge Type.

Please note that the Name is a combination of Address Type and Delivery Charge Type in that order.</description>
    <label>Delivery Charge</label>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_Balance__c</fullName>
        <label>Credit Balance</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Delivery_Charge__c</fullName>
        <label>Delivery Charge</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Case__r.Account.Name</formula>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Asia_1_creation_mode__c</fullName>
        <label>Asia 1 creation mode</label>
        <picklist>
            <picklistValues>
                <fullName>Individual</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Bulk</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Is_Digital__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicate if the associated package is digital. This is use in Order Entry functionality.</description>
        <label>Is Digital</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Main_Package_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Main Package ID</label>
        <referenceTo>Package__c</referenceTo>
        <relationshipLabel>Order Line Items (Main Package ID)</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Line_Item_Legacy_Id__c</fullName>
        <externalId>true</externalId>
        <label>Order Line Item Legacy Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Line_Item__c</fullName>
        <displayFormat>A-{000000}</displayFormat>
        <label>Order Line Item #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items_Direct</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ph_d__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Ph (d)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ph_e__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Ph (e)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI{0000000000}</displayFormat>
        <label>Order Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Package__c.object
<CustomObject>
    <fields>
        <fullName>Package_Price__c</fullName>
        <description>[Kristine Campang 10/15/2014] created field for Item #2 Line 4 Build Remaining Items v07</description>
        <label>Package Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Package_Type__c</fullName>
        <label>Package Type</label>
        <picklist>
            <picklistValues>
                <fullName>Add On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Base</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bundle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grace Period</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <inlineHelpText>Updated by workflow with value from product platform on package item, used for reporting</inlineHelpText>
        <label>Platform</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Period__c</fullName>
        <label>Subscription Period</label>
        <picklist>
            <controllingField>Subscription_Type__c</controllingField>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subscription_Type__c</fullName>
        <label>Subscription Type</label>
        <picklist>
            <picklistValues>
                <fullName>Termed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evergreen</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Package_Item__c.object
<CustomObject>
    <fields>
        <fullName>Is_Digital__c</fullName>
        <formula>IF(AND(TEXT(Product_Rate_Plan__r.zqu__ZProduct__r.ProductPlatform__c) != null, TEXT(Product_Rate_Plan__r.zqu__ZProduct__r.ProductPlatform__c) != &apos;Print&apos;), true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Digital?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Package__c</fullName>
        <description>The package name for which the package item is being created will be displayed.</description>
        <label>Package</label>
        <referenceTo>Package__c</referenceTo>
        <relationshipLabel>Package Items</relationshipLabel>
        <relationshipName>Package_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Family</label>
        <referenceTo>Product_Family__c</referenceTo>
        <relationshipLabel>Package Items</relationshipLabel>
        <relationshipName>Package_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Rate Plan</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>zqu__ProductRatePlan__c.zqu__Deleted__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>Package Items</relationshipLabel>
        <relationshipName>Package_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Package Item</label>
    <nameField>
        <label>Package Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Package Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product_Family__c.object
<CustomObject>
    <fields>
        <fullName>Product_Family__c</fullName>
        <inlineHelpText>Product Family Code</inlineHelpText>
        <label>Product Family</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Product Family</label>
    <nameField>
        <displayFormat>PF-{00000000}</displayFormat>
        <label>Product Family Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Families</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MigrationOLITriggerHandlerTest.cls
@IsTest (seeAllData = True)
private class MigrationOLITriggerHandlerTest {

            static Account testAccount;
            static Order__c testOrder;  
            static Order_Line_Item__c testOrderLineItem;
            static Package__c testPackage;
            static Package_Item__c testPackageItem; 
            static zqu__ProductRatePlan__c testProductRatePlan;
            static zqu__ZProduct__c testZProduct;
            static Product_Family__c testProductFamily;
            
    static testmethod void testOrderLineItem()
    {
            testAccount = TestDataFactory.createAccount(1, 'Direct Corporate')[0];
            insert testAccount;
            
            testProductFamily = new Product_Family__c();
            testProductFamily.Product_Family__c = 'testproductfamilysample';
            insert testProductFamily;
            
            testZProduct =  TestDataFactory.createZProduct(1)[0];
            testZProduct.ProductPlatform__c = 'Online';
            testZProduct.ProductSubType__c = 'Magazine';
            insert testZProduct;
            
            testProductRatePlan = TestDataFactory.createProductRatePlan(1)[0];
            testProductRatePlan.zqu__ZProduct__c = testZProduct.Id;
            testProductRatePlan.SubscriptionFrequency__c = '1';
            testProductRatePlan.RatePlanType__c = 'Proration';
            insert testProductRatePlan;
            
            testPackage = TestDataFactory.createPackage(1)[0];
            testPackage.Package_Price__c = 10;
            testPackage.Platform__c = 'test';
            testPackage.Subscription_Period__c = '1';
            testPackage.Subscription_Type__c = 'Termed';
            testPackage.Package_Type__c = 'Grace Period';
            insert testPackage;
            
            testPackageItem = TestDataFactory.createPackageItem(1,'Base Product')[0];
            testPackageItem.Product_Rate_Plan__c = testProductRatePlan.Id;
            testPackageItem.Product_Family__c = testProductFamily.Id;
            testPackageItem.Package__c = testPackage.Id;
            insert testPackageItem;
            
            testOrder = TestDataFactory.createOrder(1)[0];
            testOrder.Account__c = testAccount.Id; 
            testOrder.Credit_Balance__c = 100.00;
            testOrder.Delivery_Charge__c = 100.00;
            insert testOrder;

            testOrderLineItem = TestDataFactory.createOrderLineItem(1)[0];
            testOrderLineItem.Order_Line_Item_Legacy_Id__c = 'IANGAJKERNGIE';
            testOrderLineItem.Asia_1_creation_mode__c = 'Individual';
            testOrderLineItem.Ph_d__c = True;
            testOrderLineItem.Ph_e__c = True;
            testOrderLineItem.Main_Package_ID__c = testPackage.Id;
            testOrderLineItem.Order__c = testOrder.Id;
            insert testOrderLineItem; 
            
            //testPackageItem = [Select Id, Name, Is_Digital__c, Product_Family__r.Name, 
                             // Product_Rate_Plan__r.zqu__ZProduct__r.ProductPlatform__c, Product_Rate_Plan__r.SubscriptionFrequency__c, 
                             // Product_Rate_Plan__r.zqu__ZProduct__r.ProductSubType__c FROM Package_Item__c];
            
           // testPackage = [Select Id, Subscription_Period__c, Package_Price__c, Platform__c, Subscription_Type__c, 
                         // Package_Type__c 
                         // From Package__c ];
            
            Test.startTest();
            MigrationOLITriggerHandler molith = new MigrationOLITriggerHandler();
            molith.doBeforeInsert(new List<Order_Line_Item__c> { testOrderLineItem });
            Test.stopTest();
            
            System.assertEquals(testOrderLineItem.Order_Line_Item_Legacy_Id__c, 'IANGAJKERNGIE');
    }
    
    static testmethod void testOrderLineItem2()
    {
            testAccount = TestDataFactory.createAccount(1, 'Direct Corporate')[0];
            insert testAccount;
            
            testProductFamily = new Product_Family__c();
            testProductFamily.Product_Family__c = 'testproductfamilysample';
            insert testProductFamily;
            
            testZProduct =  TestDataFactory.createZProduct(1)[0];
            testZProduct.ProductPlatform__c = 'Online';
            testZProduct.ProductSubType__c = 'Magazine';
            insert testZProduct;
            
            testProductRatePlan = TestDataFactory.createProductRatePlan(1)[0];
            testProductRatePlan.zqu__ZProduct__c = testZProduct.Id;
            testProductRatePlan.SubscriptionFrequency__c = '1';
            testProductRatePlan.RatePlanType__c = 'Proration';
            insert testProductRatePlan;
            
            testPackage = TestDataFactory.createPackage(1)[0];
            testPackage.Package_Price__c = 10;
            testPackage.Platform__c = 'test';
            testPackage.Subscription_Period__c = '1';
            testPackage.Subscription_Type__c = 'Termed';
            testPackage.Package_Type__c = 'Grace Period';
            insert testPackage;
            
            testPackageItem = TestDataFactory.createPackageItem(1,'Base Product')[0];
            testPackageItem.Product_Rate_Plan__c = testProductRatePlan.Id;
            testPackageItem.Product_Family__c = testProductFamily.Id;
            testPackageItem.Package__c = testPackage.Id;
            insert testPackageItem;
            
            testOrder = TestDataFactory.createOrder(1)[0];
            testOrder.Account__c = testAccount.Id; 
            testOrder.Credit_Balance__c = 100.00;
            testOrder.Delivery_Charge__c = 100.00;
            insert testOrder;

            testOrderLineItem = TestDataFactory.createOrderLineItem(1)[0];
            testOrderLineItem.Order__c = testOrder.Id;
            testOrderLineItem.Order_Line_Item_Legacy_Id__c = 'IANGAJKERNGIE';
            testOrderLineItem.Asia_1_creation_mode__c = 'Individual';
            testOrderLineItem.Ph_d__c = True;
            testOrderLineItem.Ph_e__c = True;
            testOrderLineItem.Main_Package_ID__c = testPackage.Id;
            insert testOrderLineItem; 
            
            
            //testPackageItem = [Select Id, Name, Is_Digital__c, Product_Family__r.Name, 
                             // Product_Rate_Plan__r.zqu__ZProduct__r.ProductPlatform__c, Product_Rate_Plan__r.SubscriptionFrequency__c, 
                             // Product_Rate_Plan__r.zqu__ZProduct__r.ProductSubType__c FROM Package_Item__c];
            
           // testPackage = [Select Id, Subscription_Period__c, Package_Price__c, Platform__c, Subscription_Type__c, 
                         // Package_Type__c 
                         // From Package__c ];
                                      
            //testOrderLineItem = [SELECT Id, Name, Order_Line_Item_Legacy_Id__c FROM Order_Line_Item__c LIMIT 1];

            
            Map<Id, Order_Line_Item__c> orderLineItemMap = new Map<Id, Order_Line_Item__c>();
            orderLineItemMap.put(testOrderLineItem.id, testOrderLineItem);
            
            Map<Id, Order_Line_Item__c> orderLineItemMap2 = new Map<Id, Order_Line_Item__c>();
            orderLineItemMap2.put(testOrderLineItem.id, testOrderLineItem);
            
            Test.startTest();
            MigrationOLITriggerHandler molith = new MigrationOLITriggerHandler();
            molith.doBeforeUpdate(new List<Order_Line_Item__c> { testOrderLineItem }, orderLineItemMap, new List<Order_Line_Item__c> { testOrderLineItem }, orderLineItemMap2);
            Test.stopTest();
            
            System.assertEquals(testOrderLineItem.Asia_1_creation_mode__c, 'Individual');
            
    }
    
    static testmethod void testProductPlatformEqualsAllInOne()
    {
            testAccount = TestDataFactory.createAccount(1, 'Direct Corporate')[0];
            insert testAccount;
            
            testProductFamily = new Product_Family__c();
            testProductFamily.Product_Family__c = 'testproductfamilysample';
            insert testProductFamily;
            
            testZProduct =  TestDataFactory.createZProduct(1)[0];
            testZProduct.ProductPlatform__c = 'All-In-One';
            testZProduct.ProductSubType__c = 'Magazine';
            insert testZProduct;
            
            testProductRatePlan = TestDataFactory.createProductRatePlan(1)[0];
            testProductRatePlan.zqu__ZProduct__c = testZProduct.Id;
            testProductRatePlan.SubscriptionFrequency__c = '1';
            testProductRatePlan.RatePlanType__c = 'Proration';
            insert testProductRatePlan;
            
            testPackage = TestDataFactory.createPackage(1)[0];
            testPackage.Package_Price__c = 10;
            testPackage.Platform__c = 'test';
            testPackage.Subscription_Period__c = '1';
            testPackage.Subscription_Type__c = 'Termed';
            testPackage.Package_Type__c = 'Grace Period';
            insert testPackage;
            
            testPackageItem = TestDataFactory.createPackageItem(1,'Base Product')[0];
            testPackageItem.Product_Rate_Plan__c = testProductRatePlan.Id;
            testPackageItem.Product_Family__c = testProductFamily.Id;
            testPackageItem.Package__c = testPackage.Id;
            insert testPackageItem;
            
            testOrder = TestDataFactory.createOrder(1)[0];
            testOrder.Account__c = testAccount.Id; 
            testOrder.Credit_Balance__c = 100.00;
            testOrder.Delivery_Charge__c = 100.00;
            insert testOrder;

            testOrderLineItem = TestDataFactory.createOrderLineItem(1)[0];
            testOrderLineItem.Order__c = testOrder.Id;
            testOrderLineItem.Order_Line_Item_Legacy_Id__c = 'IANGAJKERNGIE';
            testOrderLineItem.Asia_1_creation_mode__c = 'Individual';
            testOrderLineItem.Ph_d__c = True;
            testOrderLineItem.Ph_e__c = True;
            testOrderLineItem.Main_Package_ID__c = testPackage.Id;
            insert testOrderLineItem; 
            
            
            //testPackageItem = [Select Id, Name, Is_Digital__c, Product_Family__r.Name, 
                             // Product_Rate_Plan__r.zqu__ZProduct__r.ProductPlatform__c, Product_Rate_Plan__r.SubscriptionFrequency__c, 
                             // Product_Rate_Plan__r.zqu__ZProduct__r.ProductSubType__c FROM Package_Item__c];
            
           // testPackage = [Select Id, Subscription_Period__c, Package_Price__c, Platform__c, Subscription_Type__c, 
                         // Package_Type__c 
                         // From Package__c ];
                                      
            //testOrderLineItem = [SELECT Id, Name, Order_Line_Item_Legacy_Id__c FROM Order_Line_Item__c LIMIT 1];

            
            Map<Id, Order_Line_Item__c> orderLineItemMap = new Map<Id, Order_Line_Item__c>();
            orderLineItemMap.put(testOrderLineItem.id, testOrderLineItem);
            
            Map<Id, Order_Line_Item__c> orderLineItemMap2 = new Map<Id, Order_Line_Item__c>();
            orderLineItemMap2.put(testOrderLineItem.id, testOrderLineItem);
            
            Test.startTest();
            MigrationOLITriggerHandler molith = new MigrationOLITriggerHandler();
            molith.doBeforeUpdate(new List<Order_Line_Item__c> { testOrderLineItem }, orderLineItemMap, new List<Order_Line_Item__c> { testOrderLineItem }, orderLineItemMap2);
            Test.stopTest();
            
            System.assertEquals(testZProduct.ProductPlatform__c, 'All-In-One');
            
    }
    
    static testmethod void testSubscriptionFrequencyEqualsZero()
    {
            testAccount = TestDataFactory.createAccount(1, 'Direct Corporate')[0];
            insert testAccount;
            
            testProductFamily = new Product_Family__c();
            testProductFamily.Product_Family__c = 'testproductfamilysample';
            insert testProductFamily;
            
            testZProduct =  TestDataFactory.createZProduct(1)[0];
            testZProduct.ProductPlatform__c = 'All-In-One';
            testZProduct.ProductSubType__c = 'Magazine';
            insert testZProduct;
            
            testProductRatePlan = TestDataFactory.createProductRatePlan(1)[0];
            testProductRatePlan.zqu__ZProduct__c = testZProduct.Id;
            testProductRatePlan.SubscriptionFrequency__c = '0';
            testProductRatePlan.RatePlanType__c = 'Proration';
            insert testProductRatePlan;
            
            testPackage = TestDataFactory.createPackage(1)[0];
            testPackage.Package_Price__c = 10;
            testPackage.Platform__c = 'test';
            testPackage.Subscription_Period__c = '1';
            testPackage.Subscription_Type__c = 'Termed';
            testPackage.Package_Type__c = 'Grace Period';
            insert testPackage;
            
            testPackageItem = TestDataFactory.createPackageItem(1,'Base Product')[0];
            testPackageItem.Product_Rate_Plan__c = testProductRatePlan.Id;
            testPackageItem.Product_Family__c = testProductFamily.Id;
            testPackageItem.Package__c = testPackage.Id;
            insert testPackageItem;
            
            testOrder = TestDataFactory.createOrder(1)[0];
            testOrder.Account__c = testAccount.Id; 
            testOrder.Credit_Balance__c = 100.00;
            testOrder.Delivery_Charge__c = 100.00;
            insert testOrder;

            testOrderLineItem = TestDataFactory.createOrderLineItem(1)[0];
            testOrderLineItem.Order__c = testOrder.Id;
            testOrderLineItem.Start_Date__c=date.today().addDays(1);
            testOrderLineItem.Order_Line_Item_Legacy_Id__c = 'IANGAJKERNGIE';
            testOrderLineItem.Asia_1_creation_mode__c = 'Individual';
            testOrderLineItem.Ph_d__c = True;
            testOrderLineItem.Ph_e__c = True;
            testOrderLineItem.Main_Package_ID__c = testPackage.Id;
            insert testOrderLineItem; 
            
            
            //testPackageItem = [Select Id, Name, Is_Digital__c, Product_Family__r.Name, 
                             // Product_Rate_Plan__r.zqu__ZProduct__r.ProductPlatform__c, Product_Rate_Plan__r.SubscriptionFrequency__c, 
                             // Product_Rate_Plan__r.zqu__ZProduct__r.ProductSubType__c FROM Package_Item__c];
            
           // testPackage = [Select Id, Subscription_Period__c, Package_Price__c, Platform__c, Subscription_Type__c, 
                         // Package_Type__c 
                         // From Package__c ];
                                      
            //testOrderLineItem = [SELECT Id, Name, Order_Line_Item_Legacy_Id__c FROM Order_Line_Item__c LIMIT 1];

            
            Map<Id, Order_Line_Item__c> orderLineItemMap = new Map<Id, Order_Line_Item__c>();
            orderLineItemMap.put(testOrderLineItem.id, testOrderLineItem);
            
            Map<Id, Order_Line_Item__c> orderLineItemMap2 = new Map<Id, Order_Line_Item__c>();
            orderLineItemMap2.put(testOrderLineItem.id, testOrderLineItem);
            
            Test.startTest();
            MigrationOLITriggerHandler molith = new MigrationOLITriggerHandler();
            molith.doBeforeUpdate(new List<Order_Line_Item__c> { testOrderLineItem }, orderLineItemMap, new List<Order_Line_Item__c> { testOrderLineItem }, orderLineItemMap2);
            Test.stopTest();
            
            System.assertEquals(testProductRatePlan.SubscriptionFrequency__c, '0');
       }
       
       static testmethod void testSubscriptionFrequencyEqualsTwo()
        {
            testAccount = TestDataFactory.createAccount(1, 'Direct Corporate')[0];
            insert testAccount;
            
            testProductFamily = new Product_Family__c();
            testProductFamily.Product_Family__c = 'testproductfamilysample';
            insert testProductFamily;
            
            testZProduct =  TestDataFactory.createZProduct(1)[0];
            testZProduct.ProductPlatform__c = 'All-In-One';
            testZProduct.ProductSubType__c = 'Magazine';
            insert testZProduct;
            
            testProductRatePlan = TestDataFactory.createProductRatePlan(1)[0];
            testProductRatePlan.zqu__ZProduct__c = testZProduct.Id;
            testProductRatePlan.SubscriptionFrequency__c = '2';
            testProductRatePlan.RatePlanType__c = 'Proration';
            insert testProductRatePlan;
            
            testPackage = TestDataFactory.createPackage(1)[0];
            testPackage.Package_Price__c = 10;
            testPackage.Platform__c = 'test';
            testPackage.Subscription_Period__c = '1';
            testPackage.Subscription_Type__c = 'Termed';
            testPackage.Package_Type__c = 'Grace Period';
            insert testPackage;
            
            testPackageItem = TestDataFactory.createPackageItem(1,'Base Product')[0];
            testPackageItem.Product_Rate_Plan__c = testProductRatePlan.Id;
            testPackageItem.Product_Family__c = testProductFamily.Id;
            testPackageItem.Package__c = testPackage.Id;
            insert testPackageItem;
            
            testOrder = TestDataFactory.createOrder(1)[0];
            testOrder.Account__c = testAccount.Id; 
            testOrder.Credit_Balance__c = 100.00;
            testOrder.Delivery_Charge__c = 100.00;
            insert testOrder;

            testOrderLineItem = TestDataFactory.createOrderLineItem(1)[0];
            testOrderLineItem.Order__c = testOrder.Id;
            testOrderLineItem.Order_Line_Item_Legacy_Id__c = 'IANGAJKERNGIE';
            testOrderLineItem.Asia_1_creation_mode__c = 'Individual';
            testOrderLineItem.Ph_d__c = True;
            testOrderLineItem.Ph_e__c = True;
            testOrderLineItem.Main_Package_ID__c = testPackage.Id;
            insert testOrderLineItem; 
            
            
            //testPackageItem = [Select Id, Name, Is_Digital__c, Product_Family__r.Name, 
                             // Product_Rate_Plan__r.zqu__ZProduct__r.ProductPlatform__c, Product_Rate_Plan__r.SubscriptionFrequency__c, 
                             // Product_Rate_Plan__r.zqu__ZProduct__r.ProductSubType__c FROM Package_Item__c];
            
           // testPackage = [Select Id, Subscription_Period__c, Package_Price__c, Platform__c, Subscription_Type__c, 
                         // Package_Type__c 
                         // From Package__c ];
                                      
            //testOrderLineItem = [SELECT Id, Name, Order_Line_Item_Legacy_Id__c FROM Order_Line_Item__c LIMIT 1];

            
            Map<Id, Order_Line_Item__c> orderLineItemMap = new Map<Id, Order_Line_Item__c>();
            orderLineItemMap.put(testOrderLineItem.id, testOrderLineItem);
            
            Map<Id, Order_Line_Item__c> orderLineItemMap2 = new Map<Id, Order_Line_Item__c>();
            orderLineItemMap2.put(testOrderLineItem.id, testOrderLineItem);
            
            Test.startTest();
            MigrationOLITriggerHandler molith = new MigrationOLITriggerHandler();
            molith.doBeforeUpdate(new List<Order_Line_Item__c> { testOrderLineItem }, orderLineItemMap, new List<Order_Line_Item__c> { testOrderLineItem }, orderLineItemMap2);
            Test.stopTest();
            
            System.assertEquals(testProductRatePlan.SubscriptionFrequency__c, '2');
       }
       
       static testmethod void testSubscriptionFrequencyEqualsThree()
        {
            testAccount = TestDataFactory.createAccount(1, 'Direct Corporate')[0];
            insert testAccount;
            
            testProductFamily = new Product_Family__c();
            testProductFamily.Product_Family__c = 'testproductfamilysample';
            insert testProductFamily;
            
            testZProduct =  TestDataFactory.createZProduct(1)[0];
            testZProduct.ProductPlatform__c = 'All-In-One';
            testZProduct.ProductSubType__c = 'Magazine';
            insert testZProduct;
            
            testProductRatePlan = TestDataFactory.createProductRatePlan(1)[0];
            testProductRatePlan.zqu__ZProduct__c = testZProduct.Id;
            testProductRatePlan.SubscriptionFrequency__c = '3';
            testProductRatePlan.RatePlanType__c = 'Proration';
            insert testProductRatePlan;
            
            testPackage = TestDataFactory.createPackage(1)[0];
            testPackage.Package_Price__c = 10;
            testPackage.Platform__c = 'test';
            testPackage.Subscription_Period__c = '1';
            testPackage.Subscription_Type__c = 'Termed';
            testPackage.Package_Type__c = 'Grace Period';
            insert testPackage;
            
            testPackageItem = TestDataFactory.createPackageItem(1,'Base Product')[0];
            testPackageItem.Product_Rate_Plan__c = testProductRatePlan.Id;
            testPackageItem.Product_Family__c = testProductFamily.Id;
            testPackageItem.Package__c = testPackage.Id;
            insert testPackageItem;
            
            testOrder = TestDataFactory.createOrder(1)[0];
            testOrder.Account__c = testAccount.Id; 
            testOrder.Credit_Balance__c = 100.00;
            testOrder.Delivery_Charge__c = 100.00;
            insert testOrder;

            testOrderLineItem = TestDataFactory.createOrderLineItem(1)[0];
            testOrderLineItem.Order__c = testOrder.Id;
            testOrderLineItem.Order_Line_Item_Legacy_Id__c = 'IANGAJKERNGIE';
            testOrderLineItem.Asia_1_creation_mode__c = 'Individual';
            testOrderLineItem.Ph_d__c = True;
            testOrderLineItem.Ph_e__c = True;
            testOrderLineItem.Main_Package_ID__c = testPackage.Id;
            insert testOrderLineItem; 
            
            
            //testPackageItem = [Select Id, Name, Is_Digital__c, Product_Family__r.Name, 
                             // Product_Rate_Plan__r.zqu__ZProduct__r.ProductPlatform__c, Product_Rate_Plan__r.SubscriptionFrequency__c, 
                             // Product_Rate_Plan__r.zqu__ZProduct__r.ProductSubType__c FROM Package_Item__c];
            
           // testPackage = [Select Id, Subscription_Period__c, Package_Price__c, Platform__c, Subscription_Type__c, 
                         // Package_Type__c 
                         // From Package__c ];
                                      
            //testOrderLineItem = [SELECT Id, Name, Order_Line_Item_Legacy_Id__c FROM Order_Line_Item__c LIMIT 1];

            
            Map<Id, Order_Line_Item__c> orderLineItemMap = new Map<Id, Order_Line_Item__c>();
            orderLineItemMap.put(testOrderLineItem.id, testOrderLineItem);
            
            Map<Id, Order_Line_Item__c> orderLineItemMap2 = new Map<Id, Order_Line_Item__c>();
            orderLineItemMap2.put(testOrderLineItem.id, testOrderLineItem);
            
            Test.startTest();
            MigrationOLITriggerHandler molith = new MigrationOLITriggerHandler();
            molith.doBeforeUpdate(new List<Order_Line_Item__c> { testOrderLineItem }, orderLineItemMap, new List<Order_Line_Item__c> { testOrderLineItem }, orderLineItemMap2);
            Test.stopTest();
            
            System.assertEquals(testProductRatePlan.SubscriptionFrequency__c, '3');
       }
       
       static testmethod void testSubscriptionFrequencyIsNull()
        {
            testAccount = TestDataFactory.createAccount(1, 'Direct Corporate')[0];
            insert testAccount;
            
            testProductFamily = new Product_Family__c();
            testProductFamily.Product_Family__c = 'testproductfamilysample';
            insert testProductFamily;
            
            testZProduct =  TestDataFactory.createZProduct(1)[0];
            testZProduct.ProductPlatform__c = 'All-In-One';
            testZProduct.ProductSubType__c = 'Magazine';
            insert testZProduct;
            
            testProductRatePlan = TestDataFactory.createProductRatePlan(1)[0];
            testProductRatePlan.zqu__ZProduct__c = testZProduct.Id;
            testProductRatePlan.SubscriptionFrequency__c = '';
            testProductRatePlan.RatePlanType__c = 'Proration';
            insert testProductRatePlan;
            
            testPackage = TestDataFactory.createPackage(1)[0];
            testPackage.Package_Price__c = 10;
            testPackage.Platform__c = 'test';
            testPackage.Subscription_Period__c = '1';
            testPackage.Subscription_Type__c = 'Termed';
            testPackage.Package_Type__c = 'Grace Period';
            insert testPackage;
            
            testPackageItem = TestDataFactory.createPackageItem(1,'Base Product')[0];
            testPackageItem.Product_Rate_Plan__c = testProductRatePlan.Id;
            testPackageItem.Product_Family__c = testProductFamily.Id;
            testPackageItem.Package__c = testPackage.Id;
            insert testPackageItem;
            
            testOrder = TestDataFactory.createOrder(1)[0];
            testOrder.Account__c = testAccount.Id; 
            testOrder.Credit_Balance__c = 100.00;
            testOrder.Delivery_Charge__c = 100.00;
            insert testOrder;

            testOrderLineItem = TestDataFactory.createOrderLineItem(1)[0];
            testOrderLineItem.Order__c = testOrder.Id;
            testOrderLineItem.Order_Line_Item_Legacy_Id__c = 'IANGAJKERNGIE';
            testOrderLineItem.Asia_1_creation_mode__c = 'Individual';
            testOrderLineItem.Ph_d__c = True;
            testOrderLineItem.Ph_e__c = True;
            testOrderLineItem.Main_Package_ID__c = testPackage.Id;
            insert testOrderLineItem; 
            
            
            //testPackageItem = [Select Id, Name, Is_Digital__c, Product_Family__r.Name, 
                             // Product_Rate_Plan__r.zqu__ZProduct__r.ProductPlatform__c, Product_Rate_Plan__r.SubscriptionFrequency__c, 
                             // Product_Rate_Plan__r.zqu__ZProduct__r.ProductSubType__c FROM Package_Item__c];
            
           // testPackage = [Select Id, Subscription_Period__c, Package_Price__c, Platform__c, Subscription_Type__c, 
                         // Package_Type__c 
                         // From Package__c ];
                                      
            //testOrderLineItem = [SELECT Id, Name, Order_Line_Item_Legacy_Id__c FROM Order_Line_Item__c LIMIT 1];

            
            Map<Id, Order_Line_Item__c> orderLineItemMap = new Map<Id, Order_Line_Item__c>();
            orderLineItemMap.put(testOrderLineItem.id, testOrderLineItem);
            
            Map<Id, Order_Line_Item__c> orderLineItemMap2 = new Map<Id, Order_Line_Item__c>();
            orderLineItemMap2.put(testOrderLineItem.id, testOrderLineItem);
            
            Test.startTest();
            MigrationOLITriggerHandler molith = new MigrationOLITriggerHandler();
            molith.doBeforeUpdate(new List<Order_Line_Item__c> { testOrderLineItem }, orderLineItemMap, new List<Order_Line_Item__c> { testOrderLineItem }, orderLineItemMap2);
            Test.stopTest();
            
            System.assertEquals('', testProductRatePlan.SubscriptionFrequency__c);
       }
}