src/objects/Eligibility_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Condition__c</fullName>
        <label>Condition</label>
        <picklist>
            <picklistValues>
                <fullName>&lt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&lt;=</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&gt;=</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_Platform__c</fullName>
        <label>Current Platform</label>
        <picklist>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Smartphone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tablet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All-In-One</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Customer_Status__c</fullName>
        <label>Customer Status</label>
        <picklist>
            <picklistValues>
                <fullName>New customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vendor customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Existing customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Days__c</fullName>
        <label>Days</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_End_Date__c</fullName>
        <label>Effective End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Start_Date__c</fullName>
        <label>Effective Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Eligibility_Rule__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Eligibility Rule</label>
        <referenceTo>Promotion_Eligibility_Rule__c</referenceTo>
        <relationshipLabel>Eligibility Rules</relationshipLabel>
        <relationshipName>Eligibility_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <label>Product Family</label>
        <picklist>
            <picklistValues>
                <fullName>BH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TUP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TUPJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TABL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WSJA</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Eligibility Rule</label>
    <nameField>
        <label>Eligibility Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eligibility Rules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Package__c.object
<CustomObject>
    <fields>
        <fullName>Effective_End_Date__c</fullName>
        <label>Effective End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Start_Date__c</fullName>
        <label>Effective Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Package_Code__c</fullName>
        <externalId>true</externalId>
        <label>Package Code</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Tagged_to_Promo_for_Add_On_Discount__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tagged to Promo</label>
        <type>Checkbox</type>
    </fields>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product_Family__c.object
<CustomObject>
    <fields>
        <fullName>Product_Family__c</fullName>
        <inlineHelpText>Product Family Code</inlineHelpText>
        <label>Product Family</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Product Family</label>
    <nameField>
        <displayFormat>PF-{00000000}</displayFormat>
        <label>Product Family Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Families</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Promotion__c.object
<CustomObject>
    <fields>
        <fullName>Effective_End_Date__c</fullName>
        <description>User specified</description>
        <label>Effective End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Start_Date__c</fullName>
        <description>User specified</description>
        <label>Effective Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Promotion_Code__c</fullName>
        <description>The promotion code will be shared across multiple promotions to simulate grouping of promotions of different contract periods.</description>
        <externalId>true</externalId>
        <label>Promotion Code</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Promotion_Eligibility_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Current_Platform__c</fullName>
        <label>Current Platform</label>
        <picklist>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Smartphone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tablet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All-In-One</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Days__c</fullName>
        <label>Days</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Eligibility_Rule__c</fullName>
        <label>Eligibility Rule</label>
        <referenceTo>Eligibility_Rule__c</referenceTo>
        <relationshipLabel>Promotion Eligibility Rules</relationshipLabel>
        <relationshipName>Promotion_Eligibility_Rules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <label>Product Family</label>
        <picklist>
            <picklistValues>
                <fullName>ST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TUP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TUPJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TABL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WSJA</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Promotion__c</fullName>
        <label>Promotion</label>
        <referenceTo>Promotion__c</referenceTo>
        <relationshipLabel>Promotion Eligibility Rules</relationshipLabel>
        <relationshipName>Promotion_Eligibility_Rules</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Promotion Eligibility Rule</label>
    <nameField>
        <displayFormat>PER-{00000000}</displayFormat>
        <label>Promotion Eligibility Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Eligibility Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Promotion_Package__c.object
<CustomObject>
    <fields>
        <fullName>Package_Name__c</fullName>
        <label>Package Name</label>
        <referenceTo>Package__c</referenceTo>
        <relationshipLabel>Promotion Package</relationshipLabel>
        <relationshipName>Promotion_Package</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Promotion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion</label>
        <referenceTo>Promotion__c</referenceTo>
        <relationshipLabel>Promotion Package</relationshipLabel>
        <relationshipName>Promotion_Package</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promotion Package</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>Promotion Pack Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Package</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AttachEligibilityRuleExtensionTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(seeAllData =  false)
private class AttachEligibilityRuleExtensionTest {

    static list<Package__c> packages;
    static Promotion__c promotion;
    static Promotion_Package__c promotionPackage;
    static Eligibility_Rule__c eligibilityRule;

    static testMethod void myUnitTest1() {
        // TO DO: implement unit test
        
        // create package
        generatePackages();

        // create promotion
        generatePromotion();
        
        // create promotion package
        generatePromotionPackage(packages[0].Id, promotion.Id);        
        
        // create elibility rule
        generateEligibilityRule();
        
        // instantiate promotion eligibility rule
        Promotion_Eligibility_Rule__c promotionEligibilityRule = new Promotion_Eligibility_Rule__c();
        promotionEligibilityRule.Current_Platform__c = 'Print';
        promotionEligibilityRule.Eligibility_Rule__c = eligibilityRule.Id;
        promotionEligibilityRule.Promotion__c = promotion.Id;
        promotionEligibilityRule.Days__c = null;
        promotionEligibilityRule.Date__c = null;
        promotionEligibilityRule.Product_Family__c = 'ST';
        
        
        // instantiate attacheligibilityrule vf page
        PageReference pageRef = new PageReference('/apex/AttachEligibilityRule');
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('promotionId', promotion.Id);
        ApexPages.currentPage().getParameters().put('promotionName', promotion.Name);
        
        ApexPages.StandardController promotionEligibilityRuleStd = new ApexPages.StandardController(promotionEligibilityRule);        
        
        // instantiate attachelibilityruleextension apex class
        AttachEligibilityRuleExtension extension = new AttachEligibilityRuleExtension(promotionEligibilityRuleStd);
             
        // create promotion elibility rule
        extension.getItems();
        system.assertEquals(extension.getItems().size(), 1);
        
        // save without date and days
        extension.save();
        system.assertEquals(extension.save(), null);
        
        // save with both date and days
        promotionEligibilityRule.Days__c = '2';    
        promotionEligibilityRule.Date__c = date.today();
        extension.promotionEligibilityRule = promotionEligibilityRule;
        extension.save();

        // save without packageListSelected
        promotionEligibilityRule.Days__c = null;
        promotionEligibilityRule.Date__c = date.today();
        extension.promotionEligibilityRule = promotionEligibilityRule;
        extension.save();
                
        // save with packageListSelected
        extension.packageListSelected = ';' + promotion.Promotion_Code__c;
        extension.save();
        
        // cancel
        extension.cancel();        
    }



    private static void generatePackages() {
        /*
            require fields:
            1. Effective Start Date
            2. Effective End Date
            3. Package Code
        */
        Package__c cpackage1 = new Package__c();
        cpackage1.Name = 'Package Test 0001';
        cpackage1.Effective_Start_Date__c = date.today();
        cpackage1.Effective_End_Date__c = date.today().addDays(30);
        cpackage1.Package_Code__c = 'PC0001';
        
        Package__c cpackage2 = new Package__c();
        cpackage2.Name = 'Package Test 0002';
        cpackage2.Effective_Start_Date__c = date.today();
        cpackage2.Effective_End_Date__c = date.today().addDays(30);
        cpackage2.Package_Code__c = 'PC0002';
        cpackage2.Tagged_to_Promo_for_Add_On_Discount__c = true;        
        
        packages = new list<Package__c>();
        packages.add(cpackage1);
        packages.add(cpackage2);
        
        insert packages;
    }
    
    
    private static void generatePromotion() {
        /* 
            require fields:
            1. Effective Start Date
            2. Effective End Date
            3. Promotion Code
        */
        
        promotion = new Promotion__c();
        promotion.Name = 'Promotion Test 0001';
        promotion.Effective_Start_Date__c = date.today();
        promotion.Effective_End_Date__c = date.today().addDays(30);
        promotion.Promotion_Code__c = 'PRO0001';
        
        insert promotion;
    }
    
    
    private static void generatePromotionPackage(id packageId, id promotionId) {
        /* 
            require fields:
            1. Package Name
            2. Promotion
        */
        
        promotionPackage = new Promotion_Package__c();
        promotionPackage.Package_Name__c = packageId;
        promotionPackage.Promotion__c = promotionId;
        
        insert promotionPackage;
        
        string packageName = [select Package_Name__r.Name from Promotion_Package__c where Id = :promotionPackage.Id].Package_Name__r.Name;
        system.assertEquals(packageName, 'Package Test 0001');
    }
    
    
    private static void generateEligibilityRule() {
        /* 
            require fields:
            1. Effective Start Date
            2. Effective End Date
        */
        
        eligibilityRule = new Eligibility_Rule__c();
        eligibilityRule.Name = 'Eligibility Rule Test 0001';
        eligibilityRule.Effective_Start_Date__c = date.today();
        eligibilityRule.Effective_End_Date__c = date.today().addDays(30);
        eligibilityRule.Current_Platform__c = 'Print';
        eligibilityRule.Condition__c = '=';
        eligibilityRule.Customer_Status__c = 'New customer';
        
        insert eligibilityRule;
        
    }
}