src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Zoura_Amendment__c.object
<CustomObject>
    <fields>
        <fullName>Amendment_Id__c</fullName>
        <description>Zuora Amendment Id</description>
        <label>Amendment Id</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Zoura Amendments</relationshipLabel>
        <relationshipName>Zoura_Amendments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Zoura Amendment</label>
    <nameField>
        <displayFormat>ZA-{000000}</displayFormat>
        <label>Zoura Amendment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zoura Amendments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ZuoraAmendmentHelperTest.cls
@isTest (seeAllData = True)
private class ZuoraAmendmentHelperTest {

    static testmethod void test() {
        try{
        Test.setMock(WebServiceMock.class, new zLoginMock());
        
        Account acct = TestDataFactory.createAccount(1, 'Direct Corporate')[0];
        Database.insert(acct);
        
        Order__c order = TestDataFactory.createOrder(1)[0];
        order.Account__c = acct.Id;
        Database.insert(order);
        
        Zoura_Amendment__c amendment = new Zoura_Amendment__c();
        amendment.Amendment_Id__c = 'test';
        amendment.Order__c = order.Id;
        Database.insert(amendment);
        
        Test.startTest();
        Set<ID> orderID = new Set<Id>();
        orderID.add(order.id);
        ZuoraAmendmentHelper.deleteAmendment(orderID);
        Test.stopTest();
        
        System.assertNotEquals(null, orderId.size());
        System.assertEquals(amendment.Order__c, order.id);
        
    }catch (Exception e) {
       }
    }
    
    static testmethod void testListOfZuoraAmendmentIds() {
        try{
        Test.setMock(WebServiceMock.class, new zLoginMock());
        
        Account acct = TestDataFactory.createAccount(1, 'Direct Corporate')[0];
        Database.insert(acct);
        
        Order__c order = TestDataFactory.createOrder(1)[0];
        order.Account__c = acct.Id;
        Database.insert(order);
        
        Zoura_Amendment__c amendment = new Zoura_Amendment__c();
        amendment.Amendment_Id__c = 'Amendment';
        amendment.Order__c = order.Id;
        Database.insert(amendment); 
        
        Test.startTest();
        List<string> amendmentID = new List<String>();
        amendmentID.add(amendment.id);
        ZuoraAmendmentHelper.deleteAmendment(amendmentID);
        Test.stopTest();
        
        System.assertNotEquals(null, amendmentID.size());
        System.assertEquals(order.Account__c, acct.Id);
        
    }catch (Exception e) {
       }
    }
}