src/objects/Product_Code__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Product Codes to bypass creation of Delivery Subscription</description>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>8</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Product Code</label>
</CustomObject>

src/objects/Product_Publication__c.object
<CustomObject>
    <fields>
        <fullName>Product_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Code</label>
        <referenceTo>Zuora__Product__c</referenceTo>
        <relationshipLabel>Product Publications</relationshipLabel>
        <relationshipName>Product_Publications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Product Publications</relationshipLabel>
        <relationshipName>Product_Publications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Publication</label>
    <nameField>
        <displayFormat>PPUB-{00000000}</displayFormat>
        <label>Product Publication Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Publication__c.object
<CustomObject>
    <fields>
        <fullName>Earliest_Start_Date__c</fullName>
        <label>Earliest Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Frequency_Code__c</fullName>
        <label>Frequency Code</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <picklist>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Magazine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All in One (AIO)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Public_Holiday_Weekday_Pub_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Public Holiday (Weekday) Pub Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Public_Holiday_Weekend_Pub_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Public Holiday (Weekend) Pub Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Publication_Code__c</fullName>
        <externalId>true</externalId>
        <label>Publication Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication_Next_Start_Date__c</fullName>
        <label>Publication Next Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Publication_Type__c</fullName>
        <description>[KCampang 9162014] Created for Stop Subscription based on QL-292 File: Publication Table v0.5</description>
        <label>Publication Type</label>
        <length>1</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Published_Days__c</fullName>
        <label>Published Days</label>
        <length>7</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <label>Publication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SP_PopConsolidationBatchMainTest.cls
/**
 * Class Name: <SP_PopConsolidationBatchMainTest>
 * @author: <Marjorie Gaelo>
 * Date: <2/26/2015>
 * Requirement/Project Name: <SPH>
 * @description: Test Class for SP_PopConsolidationBatchMain
 */
 
 @isTest //(Seealldata = TRUE)
private class SP_PopConsolidationBatchMainTest{
    static testMethod void TestPopConBatchMain(){
    
    Id jobId; 
    
    Publication__c pub = TestDataFactory.createPublication(1)[0];
        pub.Published_Days__c = '2';
        pub.Publication_Type__c = 'N';
        pub.Product_Category__c = 'Print';
        pub.Publication_Code__c = '1234';
        pub.Earliest_Start_Date__c = date.today().addDays(1);
        pub.Published_Days__c = 'YYYYYYY';
        pub.Frequency_Code__c = 'W';
        pub.Public_Holiday_Weekend_Pub_Indicator__c = TRUE;
        pub.Public_Holiday_Weekday_Pub_Indicator__c = FALSE;
        pub.Publication_Next_Start_Date__c = date.today();
        insert pub;
        
    zqu__ZProduct__c zProduct = TestDataFactory.createZProduct(1)[0];
        zProduct.ProductCode__c = 'BI';
        insert zProduct;
        
    Product_Publication__c prodPub = TestDataFactory.createProductPublication(1)[0];
        prodPub.Publication_Code__c = pub.id;
        //prodPub.Product_Code__c = zProduct.id;
        Test.StartTest();
        insert prodPub;
        Test.StopTest();    
    /*Test.StartTest();
    SP_PopConsolidationBatchMain batch = new SP_PopConsolidationBatchMain(jobID); 
    ID batchprocessid = Database.executeBatch(batch, 200);
    Test.StopTest();*/
        
    }
}