src/objects/Promotion__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Period__c</fullName>
        <description>If Contract field is Yes, this field must be between 1 and 36. 
If the Contract field is No, this field must be NA.</description>
        <label>Contract Period</label>
        <picklist>
            <controllingField>Contract__c</controllingField>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Terms_Conditions_Detail__c</fullName>
        <description>User specified</description>
        <label>Terms &amp; Conditions (Detail)</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Terms_Conditions_Summary__c</fullName>
        <description>User specified</description>
        <label>Terms &amp; Conditions (Summary)</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TermsandConditionControllerTest.cls
/*
 * Class Name: TermsandConditionControllerTest
 * @author: Rom Edison Reyes
 * Date: 4/14/2016
 * Project/Requirement:  <SPH>
 * @description Test Class for TermsandConditionController

 */

@isTest(seeAllData = true)
public class TermsandConditionControllerTest {
    static testMethod void testTermsAndConditionPage(){
        
        Promotion__c promo = TestDataFactory.createPromotion(1)[0];
        promo.Name = 'Promotion Name';
        promo.Terms_Conditions_Summary__c = 'Terms and Conditions Summary';
        promo.Terms_Conditions_Detail__c = 'Terms and Conditions Details';
        promo.Contract_Period__c = '12';
        insert promo;
        
        Id promoId = promo.id;
        PageReference pageRef = Page.TermsandCondition;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id',promoId);
        
        test.starttest();
        TermsandConditionController terms = new TermsandConditionController();
        test.stoptest();
    }
}