src/objects/Promo_Eligibility_Rule_Product_Family__c.object
<CustomObject>
    <fields>
        <fullName>Promotion_Eligibility_Rule__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Promotion Eligibility Rule</label>
        <referenceTo>Promotion_Eligibility_Rule__c</referenceTo>
        <relationshipLabel>Promo Eligibility Rule Product Families</relationshipLabel>
        <relationshipName>Promo_Eligibility_Rule_Product_Families</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Promo Eligibility Rule Product Family</label>
    <nameField>
        <label>Promo ER Product Family</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promo Eligibility Rule Product Families</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Promotion_Eligibility_Rule__c.object
<CustomObject>
    <label>Promotion Eligibility Rule</label>
    <nameField>
        <displayFormat>PER-{00000000}</displayFormat>
        <label>Promotion Eligibility Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Eligibility Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DeleteProductFamiliesClass.cls
public class DeleteProductFamiliesClass
{
    String perId;
    List<Promo_Eligibility_Rule_Product_Family__c> perpfStoDelete;
    
    public void DeleteProductFamilies(List<Promotion_Eligibility_Rule__c> oldPromotionEligibilityRules)
    {
        perpfStoDelete = new List<Promo_Eligibility_Rule_Product_Family__c>();
        for (Promotion_Eligibility_Rule__c per : oldPromotionEligibilityRules)
        {
            perId = per.Id;
        }
        
        perpfStoDelete = [SELECT Name, Promotion_Eligibility_Rule__c FROM Promo_Eligibility_Rule_Product_Family__c WHERE Promotion_Eligibility_Rule__c =: perId];
        if(!perpfStoDelete.isEmpty())
        {
            delete perpfStoDelete;
        }
    }
}