src/objects/Publication__c.object
<CustomObject>
    <label>Publication</label>
    <nameField>
        <label>Publication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Publication_Commission_Rates__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Start_Date__c</fullName>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Look-up to Publication</description>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Publication Commission Rates</relationshipLabel>
        <relationshipName>Publication_Commission_Rates</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Publication Commission Rate</label>
    <nameField>
        <label>Publication Commission Rates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publication Commission Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SP_LoadPublicationRatesTest.cls
@isTest
private class SP_LoadPublicationRatesTest{

    static testmethod void unitTest1(){
        
        Publication__c pub = TestDataFactory.createPublication(1)[0];
        insert pub;
        
        System.assertNotEquals(null, pub.id);
        
        Publication_Commission_Rates__c  pubComRate = new Publication_Commission_Rates__c ();
        pubComRate.Effective_Start_Date__c = Date.today();
        pubComRate.Publication__c = pub.id;
        insert pubComRate;
        
        System.assertNotEquals(null, pubComRate.id);
        
        SP_LoadPublicationRates batch = new SP_LoadPublicationRates();
        ID batchprocessid = Database.executeBatch(batch,200);
        System.assertNotEquals(null, batchprocessid);
    }
    
    static testmethod void unitTest2(){
        
        Publication__c pub = TestDataFactory.createPublication(1)[0];
        insert pub;
        
        System.assertNotEquals(null, pub.id);
        
        Publication_Commission_Rates__c  pubComRate = new Publication_Commission_Rates__c ();
        pubComRate.Effective_Start_Date__c = Date.today();
        pubComRate.Publication__c = pub.id;
        insert pubComRate;
        
        System.assertNotEquals(null, pubComRate.id);
        
        SP_LoadPublicationRates batch = new SP_LoadPublicationRates(Date.today());
        ID batchprocessid = Database.executeBatch(batch,200);
        System.assertNotEquals(null, batchprocessid);
    }
}