src/objects/Zone__c.object
<CustomObject>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zone_Product__c.object
<CustomObject>
    <description>The postage zone is used to determine the postage charge the customer needs to pay for the subscription.</description>
    <fields>
        <fullName>Effective_Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>The date when the Postage Charge for the Product under a particular zone takes effect.</description>
        <label>Effective Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>ZProduct</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>zqu__ZProduct__c.zqu__Deleted__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>Zone Mappings</relationshipLabel>
        <relationshipName>Zone_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <label>Zone</label>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>ZProducts</relationshipLabel>
        <relationshipName>Zone_Product</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Zone Product</label>
    <nameField>
        <displayFormat>ZP-{00000000}</displayFormat>
        <label>Zone Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zone Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ZoneProductTriggerHandler.cls
/**
 * Class Name: ZoneProductTriggerHandler
 * @author: Manolo Valena
 * Date: 2/2/2015
 * Requirement/Project Name: SPH
 * @description Trigger Handler for Zone Product Object
 */

public class ZoneProductTriggerHandler implements TriggerHandlerInterface{
    
    //recursion flags
    public static Boolean isBeforeUpdateTriggerCalled = FALSE;
    public static Boolean isBeforeDeleteTriggerCalled = FALSE;
    public static Boolean isBeforeInsertTriggerCalled = FALSE;
    public static Boolean isAfterUpdateTriggerCalled = FALSE;
    public static Boolean isAfterDeleteTriggerCalled = FALSE;
    public static Boolean isAfterInsertTriggerCalled = FALSE;
    
    Map<Id, List<Id>> mapProductToZones;
    Map<Id, List<Date>> mapZoneProductToStartDate;
    List<Zone_Product__c> existingZoneProductList;
    
    public Boolean runBeforeInsertTrigger() {
        Boolean returnVar = !ZoneProductTriggerHandler.isBeforeInsertTriggerCalled;
        ZoneProductTriggerHandler.isBeforeInsertTriggerCalled = TRUE;
        return returnVar;        
    }
    
    public Boolean runBeforeUpdateTrigger() {
        Boolean returnVar = !ZoneProductTriggerHandler.isBeforeUpdateTriggerCalled;
        ZoneProductTriggerHandler.isBeforeUpdateTriggerCalled = TRUE;
        return returnVar;        
    }
    
    public Boolean runBeforeDeleteTrigger() {
        Boolean returnVar = !ZoneProductTriggerHandler.isBeforeDeleteTriggerCalled;
        ZoneProductTriggerHandler.isBeforeDeleteTriggerCalled = TRUE;
        return returnVar;        
    }
    
    public Boolean runAfterInsertTrigger() {
        Boolean returnVar = !ZoneProductTriggerHandler.isAfterInsertTriggerCalled;
        ZoneProductTriggerHandler.isAfterInsertTriggerCalled = TRUE;
        return returnVar;        
    }
    
    public Boolean runAfterUpdateTrigger() {
        Boolean returnVar = !ZoneProductTriggerHandler.isAfterUpdateTriggerCalled;
        ZoneProductTriggerHandler.isAfterUpdateTriggerCalled = TRUE;
        return returnVar;        
    }
    
    public Boolean runAfterDeleteTrigger() {
        Boolean returnVar = !ZoneProductTriggerHandler.isAfterDeleteTriggerCalled;
        ZoneProductTriggerHandler.isAfterDeleteTriggerCalled = TRUE;
        return returnVar;        
    }
        
    public void bulkBefore() 
    {
        //START:D-1894 2/2/15 Added by Manolo Valeña - Passes all new Zone Product records to the CheckZoneProductRecords method.
        if(trigger.isInsert)
        {
            CheckZoneProductRecords(trigger.new);
        }    
        //END:D-1894 2/2/15 Added by Manolo Valeña
    }
        
    public void bulkAfter() {
        
    }
    
    public void beforeInsert(SObject so) {
       
    }
    
    public void beforeUpdate(SObject oldSo, SObject so) {
        
    }
    
    public void beforeDelete(SObject so) {
    
    }
    
    public void afterInsert(SObject so) {
        
    }

    public void afterUpdate(SObject oldSo, SObject so) {
        
    }

    public void afterDelete(SObject so) {
        
    }

    public void andFinally() {
        
    }
    
    /*
     *Checks Zone Product records being inserted. If there are already 2 existing record having the same product and zone of a record to be inserted,
     *an error will be shown. If there is only 1 existing record of the same product and zone, the new record is only added if its effective
     *start date is a future date compared to the existing one.
     */
    //START:D-1894 2/2/15 Added by Manolo Valeña - Added new method that validates the Zone Product records being inserted.
    public void CheckZoneProductRecords(List <Zone_Product__c> newZoneProductRecords)
    {
        mapProductToZones = new Map<Id, List<Id>>();
        mapZoneProductToStartDate = new Map<Id, List<Date>>();
        existingZoneProductList = new List<Zone_Product__c>();
        
        existingZoneProductList = [SELECT Id, Product__c, Zone__c, Effective_Start_Date__c FROM Zone_Product__c];
        
        for(Zone_Product__c zoneProd : existingZoneProductList)
        {
            if(mapProductToZones.containsKey(zoneProd.Product__c))
            {
                mapProductToZones.get(zoneProd.Product__c).add(zoneProd.Zone__c);
                mapZoneProductToStartDate.get(zoneProd.Product__c).add(zoneProd.Effective_Start_Date__c); 
            }
            else
            {
                mapProductToZones.put(zoneProd.Product__c, new List<Id>{zoneProd.Zone__c});
                mapZoneProductToStartDate.put(zoneProd.Product__c, new List<Date>{zoneProd.Effective_Start_Date__c});
            }
        }
        
        for(Zone_Product__c newZoneProd : newZoneProductRecords)
        {
            if(mapProductToZones.containsKey(newZoneProd.Product__c))
            {
                Integer count = 0;
                Boolean sameStartDate = false;
                for(Id zone : mapProductToZones.get(newZoneProd.Product__c))
                {
                    if(newZoneProd.Zone__c == zone)
                    {
                        count = count + 1;
                        if(count == 1)
                        {
                            for(Date startDate : mapZoneProductToStartDate.get(newZoneProd.Product__c))
                            {
                                if(newZoneProd.Effective_Start_Date__c == startDate)
                                {
                                    sameStartDate = true;
                                    newZoneProd.addError('There is already an existing record with the same ZProduct, Zone, and Effective Start Date. Please change the start date with a future date');
                                }
                            }
                        }
                        else if(count == 2 && sameStartDate == false)
                        {
                            newZoneProd.addError('There is already a record with a future-dated effective start date having the same ZProduct and Zone');
                        }
                    }
                }
            }
        }
    }
    //END:D-1894 2/2/15 Added by Manolo Valeña
}